### ISSUE TITLE
shorten.sh

### ISSUE THREAD

**Issue by githubuser615** [Sainan/Universal-Bypass#1130]
example link https://shorten.sh/DubeOFz8

**Comment by timmyRS** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by githubuser615** [comment]
@timmyRS I added a new line https://shorten.sh/kB2LGi
I can't pass this page.
![Untitled](https://user-images.githubusercontent.com/61451525/78972931-738e0780-7b41-11ea-8edd-68964809f4c7.jpg)
