### ISSUE TITLE
Why does Universal Bypass occasionally go to dev mode?

### ISSUE THREAD

**Issue by doio** [Sainan/Universal-Bypass#1135]
This has happened a couple of times and I have to reinstall it to make it update definitions and not in dev mode.
![20200411190352](https://user-images.githubusercontent.com/4461202/79042073-369c4080-7c27-11ea-972a-d707d9a641c5.png)

Browser: Firefox 68.7.0esr (64-bit)

**Comment by timmyRS** [comment]
I've been looking at the logic, and this really shouldn't happen in the normal build of Universal Bypass. Are you using the AMO or self-hosted version?

**Comment by doio** [comment]
Been using AMO version. Don’t know what is happening. 🤷‍♀️

**Comment by timmyRS** [comment]
Using the AMO version, even when I inspect the background script and trigger dev mode, clicking "Check for Updates" fixes this state.

**Comment by doio** [comment]
I have clicked “Check for Updates” numerous times but nothing seems to be working. That’s bizarre. 😕

**Comment by timmyRS** [comment]
Does it say anything when click it?

**Comment by Uranite** [comment]
just use self hosted version, problem solved

**Comment by doio** [comment]
Nope, the text persisted and nothing happened.

**Comment by Uranite** [comment]
> Nope, the text persisted and nothing happened.

remove the AMO and install self hosted version

**Comment by timmyRS** [comment]
In theory the AMO version is identical to the self-hosted version.
