### ISSUE TITLE
totaldebrid.org

### ISSUE THREAD

**Issue by ghajini** [Sainan/Universal-Bypass#1139]
UB 13.10,  firefox 
Hello during bypass of ads (from linkvertise)
http://totaldebrid.org/lien/?file=aaaff64540547df

Bypass occurs then error occurs =

Oups ! Il semblerait que quelque chose ne vas pas...
Passez-vous correctement les pubs ?
(ceci est une erreur liée au fait que les pubs ont été sautées, si vous avez une extension qui bypass les pubs, merci de la désactiver.)

Essayez de retourner sur le lien précédent , si le problème persiste, contacter nous via le chat

***Which translates to***
Oops! Something seems to be wrong ...
Are you advertising correctly?
(this is an error related to the fact that the ads have been skipped, if you have an extension that bypasses the ads, please deactivate it.)

Try to return to the previous link, if the problem persists, contact us via chat.
![IMG_20200411_235649](https://user-images.githubusercontent.com/20338483/79051868-2ea4c680-7c50-11ea-8442-3aa0cb9e0be8.jpg)

**Comment by Sainan** [comment]
What's the linkvertise link?

**Comment by ghajini** [comment]
Try to generate your own link
goto totaldebrid.org
enter any link https://1fichier.com/?rfau2awubaie72c5l7zy

**Comment by ghajini** [comment]
Try to generate your own link
Go to totaldebrid.org
enter any link eg https://1fichier.com/?rfau2awubaie72c5l7zy
Follow procedures you will get error after bypass

**Comment by Sainan** [comment]
This will be fixed in the next release.

**Comment by ghajini** [comment]
Verified working using self hosted version
