### ISSUE TITLE
linkvertise.com

### ISSUE THREAD

**Issue by LGLTeam** [Sainan/Universal-Bypass#1142]
https://linkvertise.com/95811/angryisgreat

Bypass works but it will force you to download the malcious exe if you are on PC. I must open inspector and select toggle device toolbar to make it think i'm on phone to bypass the exe requirement.
Can it be bypassed via universal bypass?

**Comment by Sainan** [comment]
What makes you think the exe is malicious?

**Comment by Uranite** [comment]
its not malicious but its filled with adware thing just decline them its not that hard

**Comment by Sainan** [comment]
And you're sure this adware is not related to the software itself being shady but rather Universal Bypass having done something?

**Comment by LGLTeam** [comment]
Sorry for late reply. It wants me to use linkvertise.com downloader which is kind of suspecious.

But this commit is solved now
