### ISSUE TITLE
req: semawur links

### ISSUE THREAD

**Issue by XANADIUMMOXXY** [Sainan/Universal-Bypass#1144]
https://semawur.com/6sBgJh3hu3 and https://semawur.com/EYtFDBY75wy

both of them leads the same mod file, i left both of them here instead one link just to be sure if one of the links doesn't work.

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by XANADIUMMOXXY** [comment]
I'm sorry but when i clicked the first link, it says "Unfotunately, you're the first to encounter this link..." and yes it also goes to the second link.

https://gyazo.com/555366e326f037f28ddd111c94a41cf0
