### ISSUE TITLE
fc.lc

### ISSUE THREAD

**Issue by Ciccio90x** [Sainan/Universal-Bypass#1147]
You are no longer automatically redirected without the crowdfunding option activated.
Until yesterday it worked automatically

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by Ciccio90x** [comment]
> 
> 
> Could you provide an example link?

https://fc.lc/kmIev

**Comment by Sainan** [comment]
Well, there is an automatic bypass for older versions of the template, and it seems they have just updated, so you will have to enable crowd bypass, which still works as intended.
