### ISSUE TITLE
gerspriorate.info

### ISSUE THREAD

**Issue by Nasho0101** [Sainan/Universal-Bypass#1149]
Bypass doesn't work in this page
https://gerspriorate.info/

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by Nasho0101** [comment]
https://gerspriorate.info/EOFPJ?tag_id=737124&sub_id1=addsk_15227928&sub_id2=6119670391299361443&cookie_id=2ed4abab-a11a-4a43-89ca-e88cf45624f3&lp=black_screen_arrow&convert=Your%20Video%20Is%20Ready%20To%20Stream&allb=redirect&ob=redirect&href=https%3A%2F%2Fwww.predictionds.com%2Fjump%2Fnext.php%3Fr%3D2160135%26sub1%3D%5BWEBSITEID%5D&hop=6&info=&geo=AR

**Comment by Sainan** [comment]
What is the intended destination there?

**Comment by Nasho0101** [comment]
I'm sorry, that link isn't working anymore for some reason
