### ISSUE TITLE
Bypass analytics.twitter.com

### ISSUE THREAD

**Issue by teohhanhui** [Sainan/Universal-Bypass#1161]
The link is of this form: https://analytics.twitter.com/mob_idsync_click?slug=VZKWeYY6e3&idb=AAAAEIAgMsreFR1-HgruiLeN3gnHwb5f46UtGH5JgwO9J0EEzBhDGYUzWg8qdyePsIH-SDPqRqqdeBIbM26Kyyo-FNdcxLKL4DBNB06okB3TkIZ0TmocRNXr8AcBGy9dy9lrBPxukr4O7vtArEAi9d60LfbkFuTZ&tailored_ads=true&ad_tracking=true

**Comment by teohhanhui** [comment]
Perhaps I've misunderstood...

I did see the redirect message if I whitelist analytics.twitter.com on NextDNS.

So the question is more of, whether it's possible to intercept before DNS query (or when DNS query has failed)?

**Comment by llacb47** [comment]
It redirects to `t.co/`the slug parameter.

**Comment by FireMasterK** [comment]
`https://t.co` links aren't bypassed.
Example Link: `https://t.co/JeNDiEP89a?amp=1`

**Comment by Sainan** [comment]
They are bypassed by the "tracker bypass"...

**Comment by teohhanhui** [comment]
Hmm... Actually the user experience is not ideal. The user still sees multiple flashes of redirection, which is kinda annoying. It'd be better if there's only a single loading screen which doesn't result in any flashes.

**Comment by Sainan** [comment]
An extension is on only as good as the platform its built on. Browsers decided to be "clever" and break redirects, so I needed to "fix" the redirects...

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/82009526-33183100-968d-11ea-8cf9-b0b7315e5deb.png)
It doesn't seem to be working for `t.co` but the tracker bypass works for `analytics.twitter.com`.
