### ISSUE TITLE
Request adz7short.space

### ISSUE THREAD

**Issue by Boyrules** [Sainan/Universal-Bypass#1162]
Please add https://www.adz7short.space to universal bypass . Test link https://www.adz7short.space/mFBi16

**Comment by Sainan** [comment]
That link doesn't seem to work anymore. Does anyone even use that site? A quick Google search had this issue at the first page with no other real references.

**Comment by Mioni** [comment]
https://www.adz7short.space/pFiwdG
PTC site uses this site for money
