### ISSUE TITLE
GetHatch.com bypass/isn't added

### ISSUE THREAD

**Issue by HyperLemons** [Sainan/Universal-Bypass#1163]
You can see an example [here](https://i.imgur.com/jbXWnmc.gif).

Website: https://www.asus.com/us/Phone/ROG-Phone-II/wheretobuy/
Domain (?): GetHatch.com

**Comment by Sainan** [comment]
I don't see any links on the asus.com side, could you provide the `gethatch.com` link?

**Comment by SnowPyon** [comment]
Here's the link:
https://gethatch.com/iceleads_tracking/inbetween.xhtml?tag=52421_iceleadscom-20&ascsubtag=s1588790526758zz2fa52421&region=US&merch_id=87755&affiliate_id=52421&prod_id=671657449&core_id=100122241

It was shown when you tried to buy the second item in Amazon.

**Comment by DineshSolanki** [comment]
> 
> 
> Here's the link:
> https://gethatch.com/iceleads_tracking/inbetween.xhtml?tag=52421_iceleadscom-20&ascsubtag=s1588790526758zz2fa52421&region=US&merch_id=87755&affiliate_id=52421&prod_id=671657449&core_id=100122241
> 
> It was shown when you tried to buy the second item on Amazon.

This is just a redirection, I cannot see need for a bypass.

**Comment by HyperLemons** [comment]
Only took close to 7 months... lmao

Thanks anyways, god bless and godspeed! You Sai and everyone else is doing an amazing job.
