### ISSUE TITLE
Idea4cash & shrtbtc

### ISSUE THREAD

**Issue by arbarbosa1979** [Sainan/Universal-Bypass#1166]
Both sites are from the same company, one redirects to the other

`https://idea4cash.com/`
`https://shrtbtc.com/AGWxebNe`

**Comment by KT315E** [comment]
I like how the timer melts before my eyes, haha)

**Comment by Sainan** [comment]
Your example link doesn't seem to work anymore. Could you provide a new one?

**Comment by arbarbosa1979** [comment]
`https://idea4cash.com/index.php?a=8ZlNRnpD&av=1960PTB11HJRZ26TX6`

The links on the `shrtbtc.com` website expire very quickly, I think it is some measure to prevent them from being skipped. I haven't found any more active links, if I do I will post here.

**Comment by Sainan** [comment]
Where did you get that link from then?

**Comment by arbarbosa1979** [comment]
a faucet site that has already closed, so I couldn't get another link so fast.

**Comment by arbarbosa1979** [comment]
https://shrtbtc.com/ANn4Ax1l?av=ziP2kcKS04
