### ISSUE TITLE
ouo.io issue

### ISSUE THREAD

**Issue by BedBug2479** [Sainan/Universal-Bypass#1168]
Sometimes the shortened links in ouo doesnot get bypassed but redirects to ouo.io site. But after retrying 2 to 3 times it gets to the original link.

**Comment by Sainan** [comment]
Could you provide an example link where this issue occurs?

**Comment by BedBug2479** [comment]
> Could you provide an example link where this issue occurs?

sry for little late reply
https://ouo.press/304DvL

**Comment by Uranite** [comment]
i think this isn't universal bypass issue because like months ago this always happend and i have to run ouo a few times until it gives me the right site before i knew universal bypass
