### ISSUE TITLE
https://ljutkeunvpn.blogspot.com

### ISSUE THREAD

**Issue by Mreror404** [Sainan/Universal-Bypass#1171]
this bypassed on this domain can't work again
example shortlink :
https://ljutkeunvpn.blogspot.com/p/vpn.html?url=aHR0cHM6Ly93d3cua3V5aGFhLW1lLmNvbS9pbnRlcm5ldC1kb3dubG9hZC1tYW5hZ2VyLWZ1bGwtdmVyc2lvbi5odG1sL2NvbW1lbnQtcGFnZS02MiNjb21tZW50cw==

she saved url destination from parameter url from she site,and this encode from "?url" is base64encode,you can decode this using base64decode
example code to bypass on php 
`<?php
// entering the url after "?url="
/* example : aHR0cHM6Ly93d3cua3V5aGFhLW1lLmNvbS9pbnRlcm5ldC1kb3dubG9hZC1tYW5hZ2VyLWZ1bGwtdmVyc2lvbi5odG1sL2NvbW1lbnQtcGFnZS02MiNjb21tZW50cw== */
$dest = $_REQUEST["url"];
/*
run the program :
localhost/filename.php?url=aHR0cHM6Ly93d3cua3V5aGFhLW1lLmNvbS9pbnRlcm5ldC1kb3dubG9hZC1tYW5hZ2VyLWZ1bGwtdmVyc2lvbi5odG1sL2NvbW1lbnQtcGFnZS02MiNjb21tZW50cw== 
*/
$decrypt = base64_decode($dest);
echo $decrypt;
?>
`

**Comment by Sainan** [comment]
This is already bypassed.

**Comment by Mreror404** [comment]
![ads](https://user-images.githubusercontent.com/33925496/79892786-3bce6c00-842d-11ea-8c1b-7909a5be2350.png)
not working sir

**Comment by Sainan** [comment]
Which version of Universal Bypass?

**Comment by Mreror404** [comment]
13.11.0 sir

**Comment by Sainan** [comment]
That should work fine, and it does work fine for me in Chrome, so it's probably another extension that you're using.

**Comment by Mreror404** [comment]
okey thank you very much sir,it's no problem
