### ISSUE TITLE
lewat.club new domain

### ISSUE THREAD

**Issue by Recehan-Slayer** [Sainan/Universal-Bypass#1177]
https://www.autoratio.com/jGS0qmd3o
https://www.autoratio.com/Ws6nsgDPPB

**Comment by Recehan-Slayer** [comment]
@Sainan new domain www.onlinecorp.me

**Comment by Recehan-Slayer** [comment]
@Sainan new domain apk.miuiku.com

**Comment by exodius48** [comment]
Example link for miuiku: `https://apk.miuiku.com/p2cHKf7Ud9`

**Comment by LOMEO1** [comment]
plz fix apk.miuiku.com
