### ISSUE TITLE
(Not a website) A Program I installed detects it inside chrome by its extension id. Can anything be done?

### ISSUE THREAD

**Issue by skylerspark** [Sainan/Universal-Bypass#1179]
I installed a program that relies on opening chrome, it has this stupid ad network you have to get by.

Universal Bypass has worked for the longest time, but he updated the program on windows, and it starts closing itself and saying it detected universal bypass.

I think its going off this key in chrome://extensions: 

"id": "{5f4ga810-9c36-bb61-89e2-de97c8f9g267}",

Its always the same, no matter if I reinstall or whatnot.

Im curious if you can show me how to make a custom personal version with a different name and key so I can get around these annoying click ads

I work with webdev and programming in my off time, but Ive never worked with extensions, so I have no idea how to build it from source

**Comment by skylerspark** [comment]
I see the build php scripts, Ill try seeing if I can get them running on my pc, help would be appreciated

**Comment by Sainan** [comment]
You could just drag this into your chrome://extensions page if you have developer mode on but that results in all sorts of complications because Google:

[Universal Bypass for Chromium-based browsers.zip](https://github.com/Sainan/Universal-Bypass/files/4533660/Universal.Bypass.for.Chromium-based.browsers.zip)

**Comment by skylerspark** [comment]
> You could just drag this into your chrome://extensions page if you have developer mode on but that results in all sorts of complications because Google:
> 
> [Universal Bypass for Chromium-based browsers.zip](https://github.com/Sainan/Universal-Bypass/files/4533660/Universal.Bypass.for.Chromium-based.browsers.zip)

But does that remove its ability to bypass ads? Or will it not function correctly?

**Comment by Sainan** [comment]
It will function as intended but Google will annoy the shit out of you for using an extension in developer mode

**Comment by skylerspark** [comment]
Thats fine. Thankyou, it does work for what I need so I can deal with some "dialogs" or whatnot
