### ISSUE TITLE
Twitch.tv Bonus auto clicker

### ISSUE THREAD

**Issue by Domiuns** [Sainan/Universal-Bypass#1181]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

Hi, you can add a script or a bypass that automatically clicks the bonus (it's a heavenly chest) it comes out every 10 minutes.

**Comment by Sainan** [comment]
That's not within the scope of this project.

**Comment by Domiuns** [comment]
Ok, thanks band sorry for disturb.
