### ISSUE TITLE
[Request] techrfour.com

### ISSUE THREAD

**Issue by KT315E** [Sainan/Universal-Bypass#1184]
Request _[m.techrfour.com](techrfour.com)_  from [urlshortx.com ](url) to be supported.

**Example::** https://m.techrfour.com/rQwYw
- After solving the captcha. we have to click the button manually to go to the next site. The re-direction is not happening automatically.
- The timer is not getting killed.

_______Since the site uses regular constant expressions when crawling on intermediate pages:_______
**For example, a view link when crawling ::** 
https://techrfour.com/how-to-earn-money-from-whatsapp-without-investment/#wpsafegenerate
may apply to this [https://xpshort.com/1RuY0](https://xpshort.com/1RuY0) and to this [https://xpshort.com/dZIy](https://xpshort.com/dZIy) , 
as well this [https://xpshort.com/OjsIxB](https://xpshort.com/OjsIxB) and even this [https://xpshort.com/a0mykR](https://xpshort.com/a0mykR) .....

same as link https://techrfour.com/how-to-earn-money-with-url-shortener-network/#wpsafegenerate
applies to all of the above links.

##### Therefore, our "Universal-Bypass" gets confused in the transitions and does not correctly produce the result.
Please fix it.

Thanks.

**Comment by anuuu16** [comment]
Someone please fix this, it's not working
