### ISSUE TITLE
pahe.in

### ISSUE THREAD

**Issue by SuperMarioMakerII** [Sainan/Universal-Bypass#1187]
https://pahe.in/the-rookie-s02/
crowd bypass doesn't works when using left click on the button

Univesal Bypass Version 13.11.2 · Bypass definitions 8bf110b
Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by KT315E** [comment]
> https://pahe.in/the-rookie-s02/
> crowd bypass doesn't works when using left click on the button
> 
> Univesal Bypass Version 13.11.2 · Bypass definitions [8bf110b](https://github.com/Sainan/Universal-Bypass/commit/8bf110b9484a5dbbf0a3928da6ffed3e9b3d518c)
> Google Chrome Version 81.0.4044.129 (Official Build) (64-bit)

Change [pahe.**in**](pahe.in) to [pahe.**me**](pahe.me) and no bypass is needed. )
