### ISSUE TITLE
https://instant-hack.to/ 

### ISSUE THREAD

**Issue by ABOATDev** [Sainan/Universal-Bypass#1191]
For https://instant-hack.to/  (french hack forum)

`// Some examples of what you can do with custom bypasses:
domainBypass("instant-hack.to", () => {
    // Triggered on example.com and subdomains (e.g. www.example.com)
    ensureDomLoaded(() => {
        // Triggered as soon as the DOM is ready
    })
    // You can use ifElement to check if an element is available via document.querySelector:
    ifElement(".forward", a => {
        safelyNavigate(a.href)
        // safelyNavigate asserts that given URL is valid before navigating and returns false if not
    }, () => {
        // Optional function to be called if the given element is not available
    })
    // You can also use awaitElement to wait until an element is available via a query selector:
    awaitElement(".forward", a => {
        safelyAssign(a.href)
        // safelyAssign is the same as safelyNavigate but skips the
        // "You're almost at your destination" page, should the user have it enabled
    })
})
domainBypass(/redirect\.(com|org)/, () => {
    // Triggered if the regex matches any part of the hostname
})
hrefBypass(/redirect\.(com|org)/, () => {
    // Triggered if the regex matches any part of the URL
})
// Enjoy! Your changes will be saved automatically.`

Nice extension thanks to the developer

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by ABOATDev** [comment]
This is  : 
https://instant-hack.to/redirect/?to=aHR0cHM6Ly91bml2ZXJzYWwtYnlwYXNzLm9yZy8%3D

**Comment by ABOATDev** [comment]
Hello 
The system has changed: 
https://instant-hack.to/redirect?to=aHR0cHM6Ly9tZWdhLm56L2ZvbGRlci9xM3dtbVlySyM5dUhVNDNUb1lHNnJrUUpFbnQwQkx3L2ZvbGRlci8zMjVsakFaSw==

Can you update it? Thank you very much.
