### ISSUE TITLE
litepaste.com

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1192]
Eg link: https://litepaste.com/view/Y8bOmM916s

**Comment by Cyberavater** [comment]
How about creating a page that shows all the links/texts presented there?
[Like UB creates for all Crowd Bypass, but for this, it'll be a little different, containing all the text/links itself?]
@Sainan

**Comment by Sainan** [comment]
Would probably take too much server space and not be reliable, but as it stands, Universal Bypass doesn't bypass captchas.

**Comment by Cyberavater** [comment]
I get your point, but UB helps the user from completing repeated captchas, So...
I've another suggestion, how about pasting them to throwbin.io (or your favorite easiest one) and then Crowd Bypass to that?? Eg; https://litepaste.com/view/Y8bOmM916s to https://throwbin.io/686TWWg
Also, it's not only for this one, there are tons of others (some of which has really annoying captchas). So creating a template will help to cover them all.
