### ISSUE TITLE
Bypass intercelestial link?

### ISSUE THREAD

**Issue by lionel0013** [Sainan/Universal-Bypass#1193]
is there anyway to bypass intercelestial link to go for my downloads? i was trying to download a file but before i reach the original link for the file i need to go over on that link several clicks

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by lionel0013** [comment]
https://pahe.ph/?85f8c8f639=Y3VlalV5RXNFOUlOVkJIN2dmbnErQStYZEFRZUt6WDZnL3F5WWZkcmRhc1VQSzJTYWVoMkYwWmRzTVFVRUsrSTBWSVhHd2VWcE5Yak96ZHNLb2Q1V0E9PQ==

everytime i download files on that site it always has that link i already use universal bypass and says "Unfortunately youre the first to encounter this link,but after you've waited, Other universal bypass users will no longer have to.

but after i try to download that link again to test if the bypass is working the same happens it only bypass the spacetica link but the intercelestial link is not hope you understand me im not that good in english thank you
