### ISSUE TITLE
Breaks some websites

### ISSUE THREAD

**Issue by SnakePin** [Sainan/Universal-Bypass#1197]
I'm using Firefox 75.0 and Universal Bypass 13.11.1.0.

I think this addon is changing the CSP and it breaks some websites, 
here's the original CSP header value of a website that I'm trying to access and Universal Bypass breaks it:
`default-src 'self' https://0.0.0.0:9090; connect-src 'self' https://0.0.0.0:9090 wss://0.0.0.0:9090; form-action 'self' https://0.0.0.0:9090; base-uri 'self' https://0.0.0.0:9090; object-src 'none'; font-src 'self' https://0.0.0.0:9090 data:; img-src 'self' https://0.0.0.0:9090 data:; block-all-mixed-content`
and after the addon does some things the website can't load some of its javascript files.
And here's a error that appears in the console when the extension is enabled: 
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).`

**Comment by Sainan** [comment]
Could you provide a link? Also, even if I fix the issue, Mozilla are cunts and are not allowing any further updates to Universal Bypass, so, yeah.

**Comment by SnakePin** [comment]
Uh I actually can't provide a link because it happens on the latest https://github.com/cockpit-project/cockpit web interface, they have very strict CSP settings as mentioned here https://github.com/cockpit-project/cockpit/wiki/Content-Security-Policy
Also may I ask what happened with the Mozilla and you so that they disallow future updates?

**Comment by Sainan** [comment]
Mozilla didn't like auto-updating, I removed it, they still blocked it.

Anyway, UB only loosens the CSP so it can inject itself, because Firefox doesn't allow extensions to just inject anyway, like Chrome does, so I'm not sure how exactly this breaks, unless you could give me a before and after of the CSP header?

**Comment by SnakePin** [comment]
The original CSP header with the extension disabled is the one provided in the first comment(I've edited that comment) and here's the one after the extension edits it:
`default-src 'self' https://0.0.0.0:9090 'unsafe-inline'; connect-src 'self' https://0.0.0.0:9090 wss://0.0.0.0:9090; form-action 'self' https://0.0.0.0:9090; base-uri 'self' https://0.0.0.0:9090; object-src 'none'; font-src 'self' https://0.0.0.0:9090 data:; img-src 'self' https://0.0.0.0:9090 data:; block-all-mixed-content ; script-src 'self' https://0.0.0.0:9090 'unsafe-inline'`

**Comment by Sainan** [comment]
So, I assume the issue is that UB adds a `script-src` that wasn't there before, but
> If this directive is absent, the user agent will look for the default-src directive.
and UB did just copy the `default-src``, so that's probably just an issue in Cockpit not conforming to CSP guidelines and instead leveraging a browser quirk.

**Comment by SnakePin** [comment]
Actually Cockpit is conforming to CSP well and `default-src` is defined in the CSP draft as well https://www.w3.org/TR/2018/WD-CSP3-20181015/#directive-default-src

**Comment by Sainan** [comment]
I know how CSP works. The changed policy is the same but with more exceptions. If that doesn't work, but the original does work, there's a bug in Firefox's CSP implementation (which wouldn't surprise me).

**Comment by SnakePin** [comment]
Maybe you should try removing the other sources like `'self' https://0.0.0.0:9090` and only have `'unsafe-inline'` as that should allow the other sources as well.

**Comment by Sainan** [comment]
But that would make the script-src stricter.

**Comment by alexolog** [comment]
Sounds similar to #1342
