### ISSUE TITLE
wanna a new bypass.

### ISSUE THREAD

**Issue by iMohamedAhmed** [Sainan/Universal-Bypass#1201]
the site is https://pluslive.live/
and there is an example https://pluslive.live/link/14669

**Comment by KT315E** [comment]
These from the same owner::

https://palsweet.live/link/14013

https://lefturl.com/link/14014

**Comment by FireMasterK** [comment]
```
domainBypass("palsweet.live", () => {
	ifElement("a.download-link[href]", a => {
		safelyNavigate(a.href);
	})
})
```
