### ISSUE TITLE
Don't open issues if you're using Firefox

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1206]
As it stands, Mozilla has disabled Universal Bypass and disallowed any updates and is not communicating with me, despite that fact that no terms are being violated and that I have been cooperative.

For you, this means, if you're using Firefox, there's no point in reporting issues as they
1. might already be fixed, or
2. if they aren't, you won't be able to get the fix.

**Comment by Cyberavater** [comment]
Well, can you do something about it? I noticed it recently that I can't bypass things on my phone that can easily do on my PC. Or, is there any alternative for firefox on android?

**Comment by Sainan** [comment]
I've contacted Mozilla using various ways, they are simply not willing to respond, even though I complied with their policies and reviewers' requests. I think there are some Chromium-based Android browsers that support addons? Kiwi?

**Comment by Cyberavater** [comment]
>I've contacted Mozilla using various ways, they are simply not willing to respond, even though I complied with their policies and reviewers' requests. I think there are some Chromium-based Android browsers that support addons? Kiwi?

Thanks for your hard work and advice. <3
