### ISSUE TITLE
[Update?] ouo.press

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1212]
Eg link: http://ouo.press/CCeJxb
I see Crowd bypass applied for this site, but there is no reCaptcha, only click, shouldn't there be a normal bypass for this site?

**Comment by Sainan** [comment]
I think it's an invisible captcha

**Comment by Cyberavater** [comment]
Can't invisible captcha be bypassed via auto-click?

**Comment by Sainan** [comment]
No, that would be detected
