### ISSUE TITLE
I was using linkvertise and skipping some things up and this happend

### ISSUE THREAD

**Issue by KrstenGames4** [Sainan/Universal-Bypass#1214]
Universal Bypass is not supposed to bring you here.

Make sure that you have allowed Universal Bypass access to all websites and not just when you click the extension. If that didn't fix it, please open an issue with reproducable steps and information about your browser. Note that only Google Chrome, Firefox, Edge, and Opera are supported.

Ummmmm Help...

**Comment by Sainan** [comment]
Did you read the actual message?
> please open an issue with reproducable steps and information about your browser
