### ISSUE TITLE
cshort.org crowd bypass not working

### ISSUE THREAD

**Issue by leumasme** [Sainan/Universal-Bypass#1215]
Example Link: https://cshort.org/d5Q9T8mVZO (Visited by me and 1 other user)
On every visit, the universal bypass infopopup shows up that informs you that you are the first visitor on an unskippable link. This is not true as a friend visited the link before, and the popup remains even after locally solving the shortlink and visiting the shortlink link again.
Both users have share&take crowd bypass enabled.

**Comment by Sainan** [comment]
Works for me

**Comment by leumasme** [comment]
Weird, works for me too now. Does the Crowdsourced bypass server have some sort of Delay before posted destinations go live?

**Comment by Sainan** [comment]
It shouldn't have. Maybe you both did the link at about the same time?

**Comment by authcs** [comment]
same for me.
