### ISSUE TITLE
cutdl.xyz seems will ban IP for few mins

### ISSUE THREAD

**Issue by 424778940z** [Sainan/Universal-Bypass#1216]
Sometime it works (if the link visited with this plugin before), sometime it will stuck there forever then got a cloudflare says host timeout.

Here are some links
https://cutdl.xyz/68Yq34qo
https://cutdl.xyz/gzpBzwQN
https://cutdl.xyz/gxks7Gba

You could find more from nxbrew.com, all their downloads are go through 1link.cloub then cutdl.xyz

**Comment by Sainan** [comment]
That's just the website being broken.

**Comment by 424778940z** [comment]
I know it may sounds like that, but trust me, it's not...
as soon as I click the button after recaptcha, im being banned for few mins
If I disable the this plugin it will go to next page...
