### ISSUE TITLE
FIREFOX USERS: Make sure your Universal Bypass is up-to-date!

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1219]
Mozilla has disabled Universal Bypass for no reason. I tried getting them to re-enable it, but they didn't respond for over a week. As a result, you may now not have Universal Bypass at all or an outdated version. I have created a new self-hosted version (13.12.0) which you can get at https://universal-bypass.org/install. Please don't open issues if you're using anything older than that.

**Comment by lorcalhost** [comment]
Currently unable to download and install the add-on. Could you provide a bypass `.xpi` again?
`The add-on could not be downloaded because of a connection failure.`

**Comment by keibebe** [comment]
> 
> 
> Currently unable to download and install the add-on. Could you provide a bypass `.xpi` again?
> `The add-on could not be downloaded because of a connection failure.`

I'm having the same issue when trying to install.

**Comment by Sainan** [comment]
You might have to download the xpi file and drag it into your extensions page.

**Comment by lorcalhost** [comment]
Manually downloading the `.xpi` and opening it with Firefox works. Thanks.

**Comment by Sainan** [comment]
Universal Bypass is on AMO again: https://addons.mozilla.org/en-US/firefox/addon/universal-bypass/
