### ISSUE TITLE
[req] https://www.detik.com

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1225]
![image](https://user-images.githubusercontent.com/19517680/81606300-ffbf7300-93fc-11ea-89cf-cb72e35aa0a3.png)

https://www.detik.com

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by 3xploiton3** [comment]
![image](https://user-images.githubusercontent.com/19517680/81607019-31850980-93fe-11ea-84cd-a6a77e37716f.png)

**Comment by 3xploiton3** [comment]
problem solved, my dns block this domain cdnstatic.detik.com
