### ISSUE TITLE
https://newstomat.com/#

### ISSUE THREAD

**Issue by sanGtH** [Sainan/Universal-Bypass#1227]
This site https://shotly.io/FBBw2RKo after solving captcha
redirects to :  https://newstomat.com/# 
![image](https://user-images.githubusercontent.com/13797193/81826254-39a38d00-9555-11ea-9bd8-9c3eabafa3df.png)
Please skip this page.
**Environment : 
Chrome v80+
Unviersal Bypasser v13.12.0
Win7 64**

**Comment by Uranite** [comment]
it leads to http://185.153.231.222/jetapi/mali.php?go=aHR0cHM6Ly9zaHR4LnB3L0ROUWpFT08=

**Comment by Sainan** [comment]
Not gonna bypass captchas 🙃
