### ISSUE TITLE
add techmirror.in to bypassed

### ISSUE THREAD

**Issue by alone543256** [Sainan/Universal-Bypass#1228]
add techmirror.in to bypassed

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by alone543256** [comment]
https://techmirror.in/?id=aWxEWVZaTTcrN3I1eTJUWFh4SkorRUhnY0x4Tjd4U1RUaVUyS0RGOURaR0VhYmtGYlhOQkY3VmRwN2R6SUp3c0hJYXUyWGltK0hndnBZejByNXY0UnV5Z0JQbjAxUE8ydFBwczZINGp4bjQ9

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
