### ISSUE TITLE
http://raboninco.com/

### ISSUE THREAD

**Issue by NateTheL0ser** [Sainan/Universal-Bypass#1230]
Here is an example link: http://raboninco.com/O33U

It is supposed to send to a sims 4 cc set, but because Universal Bypass is not skipping it, it is sending me all over the place to something called fiaharam.

**Comment by Sainan** [comment]
That link seems to download a `[novvvas] Safari Toddler Bedroom Furniture.zip` for me.

**Comment by Uranite** [comment]
raboninco seems to redirect to fiaharam or adfly (fiaharam is adfly) and after the adfly it goes to simfileshare
