### ISSUE TITLE
WHAT? "this site is bypassed by crowd bypass, which you have disabled"

### ISSUE THREAD

**Issue by gabri25ele** [Sainan/Universal-Bypass#1231]
From today (update) the addon show me: **this site is bypassed by crowd bypass, which you have disabled in the options**
But I don't disable anything in the option... 
By the way in the options I do not see a section to disable certain sites.
so what does it mean? why does this warning come up?
example links:
https://cu6.io/mvgb
https://cpmlink.net/IzlfAQ

**Comment by Sainan** [comment]
Mozilla asked me to disable this important feature by default (and retroactively by default) for Firefox users, so you'll have to manually enable it in the options now.
