### ISSUE TITLE
Chrome Web Store

### ISSUE THREAD

**Issue by smaragdus** [Sainan/Universal-Bypass#1232]
[Universal Bypass](https://universal-bypass.org/) was removed from [Chrome Web Store](https://chrome.google.com/webstore/detail/universal-bypass/aihomhdbhpnpmcnnbckjjcebjoikpihj). I would like to know- does the developer know why it was removed and will it come back again in the foreseeable future.

**Comment by Sainan** [comment]
![image](https://user-images.githubusercontent.com/63328889/81943525-cbfe6c00-95fb-11ea-8663-d61eea08925f.png)
I've reached out to Google, not sure if and when they will respond and what they'll say. ¯\_(ツ)_/¯

**Comment by flappysquirrel** [comment]
Banned addons aren't restored when you login to a new computer, I assume?

Has anyone managed to transfer their chrome profile to a VM without their addons getting nuked?

Because I sure as hell did not. Sorry for the rant.

**Comment by Sainan** [comment]
@flappysquirrel You're better off using the manual install, because the chrome version is (unsurprisingly) no longer maintained.
