### ISSUE TITLE
How to install universal bypass for chrome users

### ISSUE THREAD

**Issue by Uranite** [Sainan/Universal-Bypass#1234]
So universal bypass got removed from chrome web store, heres how to install it without chrome web store.
1. Download latest universal bypass on github.
2. Remove injection_script.js and rules.json.
3. Go to extensions enable developer mode.
4. Now press load unpacked and select universal bypass.
5. profit.

or here if u too lazy to delete injection script and rules manually
https://cdn.discordapp.com/attachments/353779949838270475/710903246373257376/Universal-Bypass-master.zip

**Comment by Sainan** [comment]
I've literally provided the Chromium build on Github and provided instructions at https://universal-bypass.org/install

**Comment by Uranite** [comment]
oh didn't see that
