### ISSUE TITLE
Migadu admin panel

### ISSUE THREAD

**Issue by Dymstro** [Sainan/Universal-Bypass#1237]
When trying to go to the [Migadu](https://migadu.com) admin panel (located at https://admin.migadu.com/public/login) I just get the text show, and when I click anywhere in the page it changes to hide (see attached screenshot). 

When I disabled Universal Bypass it worked fine again.

![image](https://user-images.githubusercontent.com/9049164/82134484-bf933280-97f8-11ea-9191-dd58755c3470.png)

**Comment by Sainan** [comment]
Works fine for me in Chrome & Firefox.

**Comment by Dymstro** [comment]
I tried it on chromium and firefox, I even created a clean firefox profile to test if it wasn't because of other extensions and still had the same issue. A friend of mine also reported having the same issue

**Comment by Sainan** [comment]
Seems like it's random whenever I reload if the page will work or not. I'd say the website is weirdly broken, since Universal Bypass doesn't seem to be doing anything other than having an error because the website is broken.

**Comment by FireMasterK** [comment]
I'm able to replicate this issue too.
I see this in the logs:
https://paste.ubuntu.com/p/t7pNNmZmqY/
It works perfectly without the extension, however.

**Comment by Sainan** [comment]
Yeah, but that issue is because the website is broken, and apparently have no document element. Universal Bypass would never remove the document element, so I'm blaming it on the website.
