### ISSUE TITLE
https://linkvertise.com/48331/491.87979748139276/dynamic

### ISSUE THREAD

**Issue by S1monuwu** [Sainan/Universal-Bypass#1238]
When trying to use Universal bypass on H-gen.xyz, I can get by the video and article, but when I get to the 'direct link to site', it says 'Content provided by  ??e', and when I press the direct link to site button it sends me to this 'http://lnk.thinksuggest.org/redir/clickGate.php?u=58U9s81D&m=15&p=6A9n9br68J&t=658&s=j-d677616ce4&url=%3F%3Fe&q=_clickout&r=https%3A%2F%2Fapi.thinksuggest.org%2F%3Fm%3Dc%26t%3Dj%26h%3DJump%26q%3D_clickout%26pid%3Dlinkvertisenet%26k%3D%253F%253Fe%26subid%3Dklickouts'. "There was an error during the redirection."

**Comment by Sainan** [comment]
Looks like an issue with Linkvertise.

**Comment by S1monuwu** [comment]
it works without universal bypass tho

**Comment by Sainan** [comment]
I tried both of the links you provided without Universal Bypass enabled.
