### ISSUE TITLE
"Disable developer mode extensions" popup after installing Universal Bypass

### ISSUE THREAD

**Issue by ElJaviLuki** [Sainan/Universal-Bypass#1239]
![Meh](https://user-images.githubusercontent.com/42473691/82215273-71c11c00-9917-11ea-90d8-0e37e8279fb2.png)

Basically this annoying popup appears every time I open Chrome with Universal Bypass installed. 

I have tried converting it to .crx but doing this way, Chrome blocks the extension because it says it's not available on the Chrome Web Store.

Any suggestions? Thanks!

**Comment by Sainan** [comment]
1. Complain to Google.
2. Deal with it.
3. Don't use Chrome or Universal Bypass.
