### ISSUE TITLE
click.linksynergy.com

### ISSUE THREAD

**Issue by arcasinky** [Sainan/Universal-Bypass#1240]
Used by a large 'hot deals' site to track clicks to some stores.

Example link:
https://click.linksynergy.com/deeplink?u1=033f97f6998111ea898f2a70558bfcd60INT&id=lw9MynSeamY&mid=44583&murl=https%3A%2F%2Fwww.newegg.com%2Famd-ryzen-7-3700x%2Fp%2FN82E16819113567%3Fsdtid%3D14060435%26Item%3DN82E16819113567

The ultimate destination link:
https://www.newegg.com/amd-ryzen-7-3700x/p/N82E16819113567?Item=N82E16819113567

**Comment by Sainan** [comment]
What is there to be bypassed?

**Comment by FireMasterK** [comment]
A tracker bypass could be added. It would be possible to directly redirect without using apimon by using the URL in the `murl` parameter.

**Comment by arcasinky** [comment]
Hi.  Yeah, I was hoping for something along the lines of what FireMasterK said: bypass the click-tracker and go directly to the redirect.

**Comment by MaxJW** [comment]
I would also love this to be implemented! I mainly use Universal-Bypass as I have a pihole setup, which therefore blocks the click.linksynergy domain entirely, would be great to be able to bypass this if possible! Sorry to be reviving a slightly old issue here

**Comment by FireMasterK** [comment]
Can we have rules for parameters in `background.js`?
We can have a `regex` for matching and a `parameter` to get the destination from.
Many issues can be solved with this.
```
var url = new URL(tracker_url);
getRedirect(url.searchParams.get("murl"));
```

**Comment by Sainan** [comment]
I'm pretty sure this issue is as easy as adding it to the "trackers" list in rules.json ¯\_(ツ)_/¯

**Comment by MaxJW** [comment]
Thanks for your really quick fix! Problem is they also use "https://click.linksynergy.com/**link**" as well as **deeplink**, could this also be added? If there is a way to test and request these manually as well I'd love to help :+1:

**Comment by Sainan** [comment]
You can clone Universal Bypass and fool around with the injection_script.js & rules.json and submit a PR if it works, but could you provide an example link for the other link type?

**Comment by FireMasterK** [comment]
> I'm pretty sure this issue is as easy as adding it to the "tracker" list in rules.json ¯\\\_(ツ)_/¯

But, that contacts your servers, whenever it's possible to bypass without contacting your server, we should do that. My idea could be applicable to many different tracking services

**Comment by Sainan** [comment]
I understand that. Ideally, I would not like Universal Bypass to be misused as a privacy extension. But, the real problem is that the background script isn't very well integrated with the whole auto-updating, so adding a rule for that would probably require an extension update.

**Comment by FireMasterK** [comment]
> I understand that. Ideally, I would not like Universal Bypass to be misused as a privacy extension. But, the real problem is that the background script isn't very well integrated with the whole auto-updating, so adding a rule for that would probably require an extension update.

Well, I don't think anyone uses Universal Bypass solely to improve their privacy, adblockers cookie deleters do a much better job for that. If you add a rule system for this (regex and parameter) in your next release, it would speed up bypassing. And, you're right, this would require an extension update as the injection_script.js is not executed on 30x's.

**Comment by MaxJW** [comment]
Sorry for the late reply, here's the link example: https://click.linksynergy.com/link?id=8BacdVP0GFs&offerid=345517.293003&type=15&murl=https%3A%2F%2Fwww.cclonline.com%2Fproduct%2F293003%2FB450-GAMING-PLUS-MAX%2FMotherboards%2FMSI-B450-GAMING-PLUS-MAX-AMD-Socket-AM4-B450-Chipset-ATX-Motherboard%2FMBD2684%2F
