### ISSUE TITLE
https://files.pw/

### ISSUE THREAD

**Issue by rsileasp** [Sainan/Universal-Bypass#1242]
can you add this site in your extension

https://files.pw/
https://files.pw/vz7ycd8o82es

Thanks

**Comment by Dibbyo456** [comment]
yeah, the timer needs to be bypass.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/86172869-a8a46780-bb3c-11ea-9a08-72960c684d9e.png)
Site has server side countdown checking
