### ISSUE TITLE
https://discord.kim/

### ISSUE THREAD

**Issue by peckingduck101** [Sainan/Universal-Bypass#1246]
this doesn't redirect anywhere, just logs your IP with a discord webhook,
![image](https://user-images.githubusercontent.com/51399074/82722375-8b90a380-9d09-11ea-8317-dca153b6a2f4.png)
this is an image my friend had provided me after he logged my ip :/

**Comment by Uranite** [comment]
wow nice website im gonna use it to ip log my friend and suprise him

**Comment by peckingduck101** [comment]
> wow nice website im gonna use it to ip log my friend and suprise him

im pretty sure its private :kekw:

**Comment by AwesomeMaster** [comment]
How is this supposed to be a bypass though? You just have to be careful and not click on shady links, even if your friend sends it.

**Comment by Uranite** [comment]
well, universal bypass has a feature to "Block IP loggers if they can't be bypassed."
