### ISSUE TITLE
a link in linkvertise detects bypass

### ISSUE THREAD

**Issue by ixPROx3** [Sainan/Universal-Bypass#1250]
universal bypass i need help universal bypass works on every website but it doesnt work in this site or link
https://linkvertise.com/61080/KeyySystem they just caught me using bypass help me! and thanks!

**Comment by Uranite** [comment]
fluxus key system: https://fluxteam.xyz/ks/checkpoint/checkpoint1.php

**Comment by Uranite** [comment]
seems to work, it doesn't detect bypassing.

**Comment by ixPROx3** [comment]
how? it doesnt work for me

**Comment by ixPROx3** [comment]
https://user-images.githubusercontent.com/50840859/82942846-4be3e900-9fa1-11ea-8d51-e553ce02c9dd.png heres a picture that its detecting it
