### ISSUE TITLE
h-gen.xyz

### ISSUE THREAD

**Issue by SimplePog** [Sainan/Universal-Bypass#1251]
Before you report a website that detects Universal Bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE
I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.

If that is not the case, please **provide an example link.** We need to be able to see what has gone wrong in order to fix it.

**Comment by SimplePog** [comment]
https://vagina.guru/1ttCIF.png

**Comment by Sainan** [comment]
Could you provide the link(s) before that?

**Comment by Uranite** [comment]
> Could you provide the link(s) before that?

its h-gen.xyz and it detects universal bypass
