### ISSUE TITLE
swatchseries

### ISSUE THREAD

**Issue by mark05e** [Sainan/Universal-Bypass#1252]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=swatchseries

> If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

1. [Stage 1 - Example link - Provider List page](https://www1.swatchseries.to/episode/mister_winner_s1_e3.html)
This page lists providers. Select a random provider
![image](https://user-images.githubusercontent.com/1783193/82823240-e19f4b80-9eaf-11ea-8926-d6d8e27cf7a5.png)

2. [Stage 2 - Provider intermediate page](https://www1.swatchseries.to/freecale.html?r=gejyJgjdCI6Inh4aUdZVtGZrd1k3VTpNjQVhkaDdhscWN1cGVNTWlNbGxTd0N4UjdiTWJyc1d3TVlPZG5uMUQ5YjlpVVpCckxcL0l3bFY4dFEwYWMySmNraFZQSVF5ZGJwZUVFNEpRRE5iTmZhRk9Xa3dpUFVUQWplUVBFaWlcL1V1VzR3b0c3Znh4MmciLCJpdiI6ImM2NTEzMmM4ZWJlZDlkZjlhODYzOTlhZWY4YmIzYzVmIiwicyI6IjI4YzYwMWM4YmU2MWY4MTQifQ==)
There is a large "Click here to play" button that needs to be clicked.
![image](https://user-images.githubusercontent.com/1783193/82823343-10b5bd00-9eb0-11ea-9e12-b29790456283.png)

3. [Stage 3 - Provider Page](https://clipwatching.com/ab0pawr6h2vg/mister.winner.s01e03.hdtv.x264-river.mkv.html)
 
My assumption is that the extension can help automate pass Stage 2 automatically.

**Comment by Uranite** [comment]
website doesn't work i cant open it

**Comment by mark05e** [comment]
Which one? Maybe there is a geo-block?
I just checked and all links work for me.

**Comment by mark05e** [comment]
@Sainan thank you! ❤️

**Comment by mark05e** [comment]
hi. with the adblock turned on, it automatically closes the popup. any idea how I can make this work with universal bypass?

Adblock rule:
![image](https://user-images.githubusercontent.com/1783193/83737138-48b0c300-a65b-11ea-93de-d883bb927af0.png)

UB settings:
![image](https://user-images.githubusercontent.com/1783193/83737429-a8a76980-a65b-11ea-8fcd-03fdd3735577.png)

**Comment by Sainan** [comment]
Make an exception for `https://universal-bypass.org/*` ?

**Comment by mark05e** [comment]
After setting it to below parameters, it worked but I still have to wait for the timer to finish.

1. Adblock - Custom filter to allow popup - **`@@||universal-bypass.org/bypassed$popup`**
2. UB - Take me to destination after **10 seconds** (anything less than 10 seconds does not work)

![image](https://user-images.githubusercontent.com/1783193/83749170-f330e200-a66b-11ea-8b46-e50afbf3ec49.png)
