### ISSUE TITLE
https://www.nexusmods.com

### ISSUE THREAD

**Issue by dlfsjdfjodifjsodifjsdo** [Sainan/Universal-Bypass#1253]
no longer working for me on 'slow download' 

Version 13.12.1 on firefox.

**Comment by Sainan** [comment]
Works for me in Chrome & Firefox.

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
is not working for me on freshly installed browsers with only universal bypass extension. Is there any reason for this?

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
update: it does not work with 'Mod Manager download' like it used to but does work with manual download.

**Comment by PhantomGamers** [comment]
Not sure if this is the same issue but when I click on any of the links on https://twitter.com/NexusSites on Firefox with Universal Bypass enabled it takes me to a page saying "Firefox can’t establish a connection to the server at 2nex.us."

The links work fine with Universal Bypass disabled

**Comment by Sainan** [comment]
I don't see any 2nex.us links, but you could try disabling the tracker bypass.
