### ISSUE TITLE
SSL Error on t.co / tl.gd

### ISSUE THREAD

**Issue by Stream5710** [Sainan/Universal-Bypass#1254]
When I try to open tl.gd (Twitlonger) link posted on Twitter, while tracker bypass is on, Firefox stops to open it as tl.gd has invalid SSL certificate. (Error code: SSL_ERROR_BAD_CERT_DOMAIN) Even if I add the domain to the exception, Twitlonger returns 404. If tracker bypass is off, the website will open with no problem. 

Example link: https://t.co/gbKOo8Gang

**Comment by Sainan** [comment]
Okay, maybe inform the webmaster for tl.gd?
