### ISSUE TITLE
edoc.pub

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1256]
![image](https://user-images.githubusercontent.com/19517680/82958112-dc8cea00-9fde-11ea-8c91-8aaf6ab38c9a.png)

ex
https://edoc.pub/queue/jago-jualan-di-instagramcompressedpdf-pdf-free.html

**Comment by Uranite** [comment]
please provide the link before this, thanks.

**Comment by mark05e** [comment]
the example url provided - download button needs to be clicked
![image](https://user-images.githubusercontent.com/1783193/83749900-2162f180-a66d-11ea-926a-f6d186bf01c5.png)

which takes to : https://edoc.pub/download/jago-jualan-di-instagramcompressedpdf-pdf-free.html

this 2nd page has the timer (screenshot by OP)

**Comment by Sainan** [comment]
Unfortunately, the download server will ensure that you have waited before allowing you to download the file.
