### ISSUE TITLE
iir.ai

### ISSUE THREAD

**Issue by cronosunder** [Sainan/Universal-Bypass#1257]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=iir.ai

If that is not the case, please **https://iir.ai/n6lLlrE** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

**Comment by Uranite** [comment]
already has crowd bypass
