### ISSUE TITLE
adsrt.net

### ISSUE THREAD

**Issue by AwesomeMaster** [Sainan/Universal-Bypass#1260]
example link: https://adsrt.net/mz3IpPX
It might automatically bypass because I already went past it manually.
Thanks!

**Comment by AwesomeMaster** [comment]
Why did you close it?

**Comment by Sainan** [comment]
> It might automatically bypass because I already went past it manually.

**Comment by AwesomeMaster** [comment]
Yeah, but isn't the point of the extension to make it automatically bypass, without it going manually? this is from a leecher website, so all of the links are automatically generated.

**Comment by Sainan** [comment]
I try to do that, but for that website it doesn't work. When it's automatically generated, then it's just an integrated adwall, so either don't use the service, or accept it.
