### ISSUE TITLE
masihbelajar.com

### ISSUE THREAD

**Issue by FinderID** [Sainan/Universal-Bypass#1263]
https://masihbelajar.com/?id=c2dSWFFZbWFqV2hEZ3ZZeDdzODBrSlBmNGZKc0JuTm0wQmZUN1dFWitYU1Vyc29UZ01yajZUNGdOa1haenpUcUMrS0JGNmREeGdRcWNrU1lwa0JBLzZiODJwcXZqMUYwNFBGS0Q1MDlZM1k9#

**Comment by Uranite** [comment]
it already has crowd bypass
