### ISSUE TITLE
https://fluxteam.xyz/ks/checkpoint/checkpoint1.php

### ISSUE THREAD

**Issue by ixPROx3** [Sainan/Universal-Bypass#1264]
https://fluxteam.xyz/ks/checkpoint/checkpoint1.php it detects universal bypass and heres a proof this is a link of the picture https://user-images.githubusercontent.com/50840859/82942846-4be3e900-9fa1-11ea-8d51-e553ce02c9dd.png

**Comment by Uranite** [comment]
you need to wait 95 seconds to not make it detected
