### ISSUE TITLE
gplinks.co is not getting bypassed correctly 

### ISSUE THREAD

**Issue by ekampreet** [Sainan/Universal-Bypass#1267]
Dear Sainan, 

 I am facing problem while bypassing "**gplinks.co**" urls. 

 Can you help. 

 Regards, 
Ekam

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by ekampreet** [comment]
https://gplinks.co/QGbmV

You can try this .

Thanks

**Comment by Uranite** [comment]
seems to work with crowd bypass

**Comment by ekampreet** [comment]
Try this link - https://gplinks.co/pbvu 

Please check the error in following screenshot [https://ibb.co/xmMS6Dw](url)

The interesting part is that sometimes it works and sometimes it's not.

**Comment by Sainan** [comment]
That is not an error. Why don't you read the "error" message closely?
