### ISSUE TITLE
universal bypass update

### ISSUE THREAD

**Issue by spaghettx** [Sainan/Universal-Bypass#1269]
hi guys so it says that im using this version 
![image](https://user-images.githubusercontent.com/66182154/83337736-75b14e80-a2c6-11ea-8108-c306d7386e1c.png)
but i want the latest version but i dont know how to update it pls help 
![image](https://user-images.githubusercontent.com/66182154/83337755-95e10d80-a2c6-11ea-98ed-948fa720f13d.png)

**Comment by Uranite** [comment]
in chrome try pressing the "check for updates"

**Comment by Sainan** [comment]
They're probably on Firefox. I would have to push that update manually. Mozilla is just pissing me off.
