### ISSUE TITLE
url.rizaldi.web.id

### ISSUE THREAD

**Issue by rigaz29** [Sainan/Universal-Bypass#1275]
https://url.rizaldi.web.id/kode-lebaran-1-2~

**Comment by Lya-chan** [comment]
404

**Comment by Sainan** [comment]
Not a 404, just an issue with how Github detected the link. [https://url.rizaldi.web.id/kode-lebaran-1-2~](https://url.rizaldi.web.id/kode-lebaran-1-2~)
