### ISSUE TITLE
https://www.gate.fm

### ISSUE THREAD

**Issue by BanementI** [Sainan/Universal-Bypass#1278]
gate.fm is owned by Repost Network. On some downloads, there is more than one way to get a download; Soundcloud, Spotify or Apple Music.
3 methods: https://www.gate.fm/CwALT3826
1 method: https://www.gate.fm/BfCxYtt

**Comment by FireMasterK** [comment]
```
var elems = document.querySelectorAll(".play-link")
if(elems.length == 1) {
safelyNavigate(elems[0].href)
}
```
Not sure if I should use document.querySelectorAll in a bypass tho

**Comment by Sainan** [comment]
It seems to me like there's backend validation with all the login shit to esentially force to you follow the artist. I wonder if that's allowed by the ToS of SoundCloud, Spotify & Apple Music, but I'm not petty enough to launch a complaint.
