### ISSUE TITLE
wwwfotografgotlin.blogspot.com

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1279]
Eg link: https://wwwfotografgotlin.blogspot.com/2018/04/mental-wellness-awareness.html#?o=862fd83600fbefe09b63708889fbc216ae599dcda57d5ad72417165c347eb55936024acc3538223b1ca8047efec1ec64dc5e67aa803d638e8a8191bbe454c69814827238e110bd35805a2392f06dd2209bb6c952f84ba3b7a233d19baed1ea2ad4c7ee41085ab446

The original link doesn't auto closes as it should [Not Crowd Bypass].

**Comment by Sainan** [comment]
Funnily enough the website is not even bypassed, they just happen to use a template (I think) so Universal Bypass "pushes its buttons" and the handler for that just so happens to open the destination in a new tab. And the destination is actually `http://sh.st/st/d44396cad6ed9fa90031ae5310776b04/https://uploadbuzz.net/dpydm8cxi23h` but that _is_ bypassed so it looks like `https://uploadbuzz.net/dpydm8cxi23h` is the destination.
