### ISSUE TITLE
multifilemirror.com

### ISSUE THREAD

**Issue by vungsung** [Sainan/Universal-Bypass#1280]
**Requests:** Auto redirect a page that required users to press an unnecessary 'continue' button manually. 

**Example Links:**
https://multifilemirror.com/uq_7wdohp2j9ia2
https://multifilemirror.com/da_7wdohp2j9ia2

**Redirected Links:**
https://multifilemirror.com/uq_7wdohp2j9ia2?action=Download
https://multifilemirror.com/da_7wdohp2j9ia2?action=Download

**Comment by FireMasterK** [comment]
```
function resolveRedirect(url)
{
	let xhr=new XMLHttpRequest(),destination
	xhr.onload=()=>{
		let json=JSON.parse(xhr.responseText)
		if(json&&json.destination)
		{
			destination=json.destination
		}
	}
	xhr.open("GET","https://apimon.de/redirect/"+encodeURIComponent(url),false)
	xhr.send()
	return destination
}

domainBypass("multifilemirror.com", () => {
    safelyNavigate(resolveRedirect(window.location.toString() + "?action=Download"))
})
```
Unfortunately, `resolveRedirect` isn't available in injection_script

**Comment by vungsung** [comment]
```
domainBypass("multifilemirror.com", () => {
    safelyNavigate("https://multifilemirror.com" + location.pathname + "?action=Download")
})
```
Should be fine I guess. a resolver such as `apimon.de` that `resolveRedirct` connected to do nothing for this domain name. it just returns exactly the same url we pass to it.
For example: https://apimon.de/redirect/http%3A%2F%2Fmultifilemirror.com%2Fuq_7wdohp2j9ia2

**Comment by Sainan** [comment]
"resolveRedirect" might be a bit of a misnomer, but the Apimon "Redirect Lookup" only works for real redirects (301, etc.), so it's only used for trackers and ip loggers in the background script. By the time your custom bypass runs, you're already tracked, logged and redirected, so that would be pointless. :)

**Comment by vungsung** [comment]
thanks for clarifying this. my bad lacking knowledge about the service.
