### ISSUE TITLE
[Update?] ceesty.com

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1286]
Eg link: http://ceesty.com/w1xN87

Why there is Crowd Bypass here? It's normally bypassable by "https://adsbypasser.github.io/". And that takes me to the 2nd issue that I can't use both bypassers, as if I use Adsbypasser, UB (CB?) doesn't work while Adsbypasser works without any issue at all. So, I'm only using UB currently. But, can't you make UB compatible with AB?
[Note: Very lower version of UB was compatible with AB]

**Comment by FireMasterK** [comment]
relevant code in adsbypasser: https://github.com/adsbypasser/adsbypasser/blob/6e8e0491a7423d5bbca711c9921e462a2e7d50b6/src/sites/link/sh.st.js

**Comment by Sainan** [comment]
Didn't we have this already? The code in adsbypasser just seems to wait.

**Comment by Cyberavater** [comment]
Can you check it again plz?
https://streamable.com/4cdq6p

**Comment by Cyberavater** [comment]
You can check the time that it doesn't seem to wait all the way, (just takes one sec for loading script).
Link edited so you can take a look at the time;
https://streamable.com/3yr9w8

**Comment by Sainan** [comment]
That is a shit way of doing it but maybe it can be combined with crowd bypass.

**Comment by FireMasterK** [comment]
This portion is the relevant code for that I believe.
https://github.com/adsbypasser/adsbypasser/blob/6e8e0491a7423d5bbca711c9921e462a2e7d50b6/src/sites/link/sh.st.js#L55-L116

**Comment by ikancupang** [comment]
Please don't compare Universal Bypass and Adsbypasser :)

Universal Bypass is extension, Adsbypasser is userscript.
Extension works better than Userscript.
so if you don't want to use a Crowd bypass, and want to Universal Bypass faster than Adsbypasser, I will make a small commit :)

**Comment by Sainan** [comment]
What a cleanup
![image](https://user-images.githubusercontent.com/63328889/86132347-0c03aa80-bae7-11ea-909f-2e6b1c3b2172.png)
