### ISSUE TITLE
https://shorten.sh/

### ISSUE THREAD

**Issue by sanGtH** [Sainan/Universal-Bypass#1289]
**URL(s) where the issue occurs**
https://shorten.sh/NHcJGnBJ

**Description of the Issue**
Refer to the screenshot. When you click on that continue button, the site re-directs to a
new site in a new tab. No matter how many times you click that button, the site keeps
re-directing to other sites indefinitely. Those sites are malicious as reported by antivirus.

**Screenshot :**
![image](https://user-images.githubusercontent.com/13797193/84055800-f6610080-a9d2-11ea-9d13-760064344eb5.png)

**Versions**
    Browser/version: [here] **Chrome v83.x**
    uBlock Origin version: [here] **v1.27.10**
    Universal Bypass version : **Version 13.12.0**

**Comment by Sainan** [comment]
This seems to redirect to https://ouo.io/Rx6pnR
You might wanna install an ad blocker and uninstall any adware you might have collected
