### ISSUE TITLE
www.file-upload.com/

### ISSUE THREAD

**Issue by Vishalkoyalkar** [Sainan/Universal-Bypass#1290]
www.file-upload.com,  wait counter doesn't get bypass 

![image](https://user-images.githubusercontent.com/33306817/84163960-99357f80-aaa4-11ea-8c01-8d9dcbbc4a1d.png)

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by Vishalkoyalkar** [comment]
https://www.file-upload.com/vlfzwtbyqeg1
