### ISSUE TITLE
General Link Extraction from URL

### ISSUE THREAD

**Issue by UltraBlackLinux** [Sainan/Universal-Bypass#1291]
So basically, is it possible to make Universal Bypass bypassing pages like example.com/redirect?url=example.org
I kinda need that to be honest, but it doesnt seem to exitst yet...
Ty :)

You created a wonderful tool, continue working on it!

**Comment by Sainan** [comment]
Universal Bypass does have general rules, but those are applied when there's really a need to, and you didn't even supply a (real) example link.

**Comment by UltraBlackLinux** [comment]
@Sainan it isnt a real link cause I dont know one atm, but this example shows what I mean.
This is another example: https://en.wikipedia.org/wiki/URL_redirection#Removing_referrer_information
I mean its just extracting an url outta an url - why do you need an example? For testing?

**Comment by Sainan** [comment]
Here you go: https://addons.mozilla.org/en-US/firefox/addon/pure-url/
This used to be available for Chrome, but Google sux 🙃
