### ISSUE TITLE
mcaltdispenserwebsite.herokuapp.com

### ISSUE THREAD

**Issue by NamelessScripter** [Sainan/Universal-Bypass#1296]
Example:
http://mcaltdispenserwebsite.herokuapp.com/startGen.php#aHR0cDovL21jYWx0ZGlzcGVuc2Vyd2Vic2l0ZS5oZXJva3VhcHAuY29tL2dlbi5waHAjYW5Wc2FXRnVZUzV0YjI5eVpUSTBNalJBWjIxaGFXd3VZMjl0T2twMWJHbGhibUV5TkRJMA== 

My Code (bad):
```javascript
domainBypass("mcaltdispenserwebsite.herokuapp.com", () => {
    safelyNavigate("http://n4meless.cf/gen?q="+ atob(atob(document.location.href.split("#")[1]).split("#")[1]) );
})
```

**Comment by Sainan** [comment]
I'm sure this is a really important website. I've submitted an abuse report with heroku.

**Comment by Sainan** [comment]
Heroku was really quick to take that down lol
