### ISSUE TITLE
Recursive Bypass?

### ISSUE THREAD

**Issue by marcussacana** [Sainan/Universal-Bypass#1298]
The wrost thing in the link protectors, is how the uploader put multiple link shortners aiming a best remuneration.
I did this link to test, https://ouo.io/o0yxd1 that is basically a ouo.io over another ouo.io link,
and looks like the universal bypass navigate to each shortener in cases like this, why not do a feature that automatically detect when the target url is another protected link and continue the query in the server to do a recursive bypass?

**Comment by Sainan** [comment]
That would have very confusing issues. Crowd bypass is meant for you to be able to say "this is the wrong destination" and that requires you to be a bit attentive and you'd certainly need all information.
