### ISSUE TITLE
Sometimes when i open linkvertise i get this

### ISSUE THREAD

**Issue by darkfake555** [Sainan/Universal-Bypass#1299]
![image](https://user-images.githubusercontent.com/66800105/84430353-926b5180-abf7-11ea-8981-a703e61a442b.png)

**Comment by Sainan** [comment]
Are you using the latest version of Universal Bypass?

**Comment by darkfake555** [comment]
it says that i am up to date everytime i open it up.

**Comment by Sainan** [comment]
but what is the actual extension version?

**Comment by darkfake555** [comment]
13.12.1

**Comment by Sainan** [comment]
What do your settings look like?
