### ISSUE TITLE
exee.io

### ISSUE THREAD

**Issue by ccsimplyspolit** [Sainan/Universal-Bypass#1300]
https://exee.io/ekVKhNi

**Comment by Alphka** [comment]
Could you do something to block these messages https://prnt.sc/vqp56a ?
A code like this, for example: `document.getElementById("before-captcha").innerHTML += '<div class="procced" id="submitbtn"><button class="btn btn-primary btn-goo" type="submit">Click here to continue <i class="lnr lnr-arrow-right"></i></button></div></div>'`

**Comment by FireMasterK** [comment]
That's an adblocker issue, try using ublock origin.
