### ISSUE TITLE
Annoying Notification when Opening file-upload.com

### ISSUE THREAD

**Issue by abdoismail** [Sainan/Universal-Bypass#1305]
Every time I open file-upload.com, I get this annoying notification saying: "Unfortunately, the download server will ensure that you have waited before allowing you to download the file.". and I can't seem to find how to stop it from showing up every time I open the website.

Screenshot of the notification:
https://bit.ly/3hoqwzU

**Comment by abdoismail** [comment]
And if someone can tell me how to turn off all kinds of on-page notifications, I will appreciate it.

**Comment by Sainan** [comment]
It's to stop people asking for a bypass.

**Comment by abdoismail** [comment]
Can't there at least be a way to stop all on-page notifications, It's so annoying, and when ever I click on it to close it, it shows up again.

**Comment by abdoismail** [comment]
Never mind, I blocked it using uBlock Origin.
