### ISSUE TITLE
https://ph.tpaste.net

### ISSUE THREAD

**Issue by Tester31** [Sainan/Universal-Bypass#1307]
Hi, is it possible to make a bypass for ph.tpaste.net links please?

Here an example: https://ph.tpaste.net/2020/06/2.html#?o=ef99c4ee6c8ed5e50a802a532e1456259ba8854a670a140aa38113eb5f066c316a5bcf527e6837f2de4666ff1c9f6471ee5a1252356783a0

Thanks in advance

**Comment by SiebeDW** [comment]
```js
aesCrypto.decrypt(convertstr($.urlParam('o')), convertstr('root'));
```
Seems to return the link
