### ISSUE TITLE
how to hide this nottification when open browser?

### ISSUE THREAD

**Issue by FinderID** [Sainan/Universal-Bypass#1310]
i want to always hide this notif when open browser, any step?

![image](https://user-images.githubusercontent.com/57831066/84616668-7ed31b80-ae81-11ea-9dc5-b0704f6c8c50.png)

**Comment by Sainan** [comment]
Press "x" on the notification. Does pressing "x" every time you open your browser annoy you? Don't use Chrome. Edge and Firefox are viable alternatives.

**Comment by FinderID** [comment]
thank you @Sainan
