### ISSUE TITLE
How to deal with the pop-up on Chrome

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1311]
**Press "x" on the popup.**
Does pressing "x" every time you open your browser annoy you? Don't use Chrome. Edge and Firefox are viable alternatives.

**Comment by Cyberavater** [comment]
But what happened to the Chrome Web Store version?

**Comment by Sainan** [comment]
Got removed for "circumventing paywalls"

**Comment by Cyberavater** [comment]
After some research, it seems that using Chrome Canary is the easiest option to deal with the pop-up.
https://www.google.com/chrome/canary/
Alternatively, you could patch chrome.dll
https://www.ghacks.net/2017/07/04/hide-chromes-disable-developer-mode-extensions-warning/

**Comment by Cyberavater** [comment]
A tool patch chrome easily;
https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher

**Comment by Sainan** [comment]
Or you could just use Edge, which is pretty much Chrome, and allows you to get Universal Bypass from their extension store. ^^

**Comment by Cyberavater** [comment]
Ya, IK. But Edge doesn't give the Search feature in their setting, plus many users are already using Chrome to store their passwords, so switching might be hard for them. (Not to mention the difficulty of changing the default search engine).

**Comment by Anokris** [comment]
When to add Universal Bypass for Chrome Web Store?

**Comment by Sainan** [comment]
![image](https://user-images.githubusercontent.com/63328889/85189373-e7216300-b2ae-11ea-909d-34811e8eb556.png)

**Comment by Anokris** [comment]
linkvertise after deleting?
Does this mean it cannot be reloaded?

**Comment by lokka30** [comment]
Thanks a lot @Cyberavater, the Chrome Developer Mode Extension Warning Patcher application works perfectly. :)

**Comment by ElJaviLuki** [comment]
Certainly, Firefox is surprising me (positively) against Chrome
