### ISSUE TITLE
duit.cc

### ISSUE THREAD

**Issue by LGLTeam** [Sainan/Universal-Bypass#1313]
https://duit.cc/Ruw26S

I got this error when it tries to bypass

![image](https://user-images.githubusercontent.com/61142621/84678663-93222180-af30-11ea-84b8-3c506f642858.png)

**Comment by FireMasterK** [comment]
https://github.com/Sainan/Universal-Bypass/search?q=duit.cc&unscoped_q=duit.cc
There seems to be existing bypasses which are outdated and therefore cause this.
