### ISSUE TITLE
Universal Bypass breaks Instagram links(?)

### ISSUE THREAD

**Issue by mozkan007** [Sainan/Universal-Bypass#1314]
Hi, is it possible create a whitelist option for the extension? Because I want to add Instagram to whitelist because whenever I click on a picture the extension redirects to the only picture, so I can not see any message or comment for the picture.Thanks.

**Comment by Sainan** [comment]
Sorry, I'm a noob to instagram but how do you "click on a picture"?

**Comment by mozkan007** [comment]
Hi again, I just click a picture on someone's Instagram page and this extension redirects the picture to only image view so I can not view the picture inside of the Instagram frame with comments. That's all the problem. I hope that I could explain my problem clearly.

**Comment by Sainan** [comment]
I just clicked on a picture on a friend's IG page and it poped up with all comments and such.
