### ISSUE TITLE
[Request/Bug?-CB?] apk.miuiku.com

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1318]
Example Link: https://bit.ly/2F9DSOE

**Comment by Cyberavater** [comment]
You'll need to click "Click here to continue" 2 or 3 times.

**Comment by exodius48** [comment]
New link: `https://apk.miuiku.com/p2cHKf7Ud9`

**Comment by Sainan** [comment]
Duplicate of #1177
