### ISSUE TITLE
Is this allowed?

### ISSUE THREAD

**Issue by rainbow-glitch** [Sainan/Universal-Bypass#1319]
Since Universal Bypass no longer bypasses Linkvertise I wanted to ask is it allowed to make a custom bypass or anything else to be able to bypass Linkvertise for yourself? I do know that the video option for Linkvertise has been removed, still It's very annoying especially the Add-on_(And lots of people make things like checkpoints etc.)_ Yeah, that's everything. Thanks!

**Comment by HowToMakeFaceitAB** [comment]
would be cool if it was allowed to be honest

**Comment by Sainan** [comment]
_I_ am not allowed to help you with it, but I can't stop you either.

**Comment by FireMasterK** [comment]
https://raw.githubusercontent.com/FireMasterK/BypassAdditions/master/script.js
I made an extremely hacky userscript to do this.

**Comment by heywolf15** [comment]
@FireMasterK I'm haven't test it but pls make your own github

**Comment by rainbow-glitch** [comment]
Hey! Thanks for everything. The userscript did not work for me since the destination has something to check for universal bypass(That's the reason that universal bypass had the waiting part), but now i have found a version in development mode which stops it from automaticly updating and the version was saved before the removal of the linkvertise bypass. I at first was thinking of using the repository history to recrate an older version but now that i found this it's not needed since it works perfectly and if I really need an update that was released I can just add it myself by copying the code. Well I think that's it. If you want the download just comment on this thread! Have a nice day! Thank you! **<3**

**Comment by FireMasterK** [comment]
> Hey! Thanks for everything. The userscript did not work for me since the destination has something to check for universal bypass(That's the reason that universal bypass had the waiting part), but now i have found a version in development mode which stops it from automaticly updating and the version was saved before the removal of the linkvertise bypass. I at first was thinking of using the repository history to recrate an older version but now that i found this it's not needed since it works perfectly and if I really need an update that was released I can just add it myself by copying the code. Well I think that's it. If you want the download just comment on this thread! Have a nice day! Thank you! **<3**

https://github.com/StuffNoOneCaresAbout/Universal-Bypass
I made a fork which should have all the changes from this repo.
