### ISSUE TITLE
juba-get.com

### ISSUE THREAD

**Issue by ghajini** [Sainan/Universal-Bypass#1321]
Go to https://juba-get.com
enter this site 

https://www91.zippyshare.com/v/uyHwBwMD/file.html

Click leech, message ''universal bypass is not supposed to bring you here, make sure........''

**Comment by Sainan** [comment]
Works for me.

**Comment by ghajini** [comment]
It doesn't work on opera browser.....crowd bypass sucks

**Comment by Sainan** [comment]
Well, too bad I removed Opera from my computer for being adware ¯\_(ツ)_/¯
