### ISSUE TITLE
Regarding Linkvertise

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1323]
You may have noticed that Linkvertise is now no longer being bypassed, this is because we did not go to court, but instead ended in a compromise, like most legal cases do. The reason I opted for a compromise is that my lawyer had already charged me thousands of euros for mere communication with the opposition's lawyer and going to court would've easily gotten into the ten-thousands, which I could get back if I win, but that's quite an investment, and what I've gotten in donations barely covered half of what I had to pay already. So, I've lost over a thousand euros for a free, open-source project — we sure do live in a society. However, don't see this compromise as a loss; I've had an extensive talk wtih Linkvertise and they were willing to remove their minute-long video option which I had found most annoying and time-wasting in exchange for my removal of the bypass. Additionally, we will keep in touch about further options they add to ensure that their website doesn't become too annoying. However, that's just the limits of me and Linkvertise; you aren't limited on how many extensions or user scripts you can install.

**Comment by Cyberavater** [comment]
Might be stupid to ask, but how about transferring the ownership to a person who lives in a country where he is immune to such law? Surely, Linkvertise can't do anything if that's the case. (I'm no law student, it's just a thought).

**Comment by Sainan** [comment]
That's to say Universal Bypass is even against the law, I just don't wanna put up the money to test that theory. Honestly, I'm decently happy without resolution, and I don't wanna go and get sued again for whatever. And as I said, no one is forcing you to only install Universal Bypass.

**Comment by Anokris** [comment]
The internet is not just a site!

**Comment by Anokris** [comment]
Yes, Linkvertise died.

**Comment by Anokris** [comment]
This is a war:) ads vs anti ads

**Comment by baibav** [comment]
Can we make it work in our system though?
can someone help with the changes to revert and bundling the extension package for chromium.

**Comment by Cyberavater** [comment]
> Can we make it work in our system though?
> can someone help with the changes to revert and bundling the extension package for chromium.
> 
> or provide zip of an working version, I tried **13.12.1** didn't work.

I can do (done for myself) that for firefox but not for Chrome. The chrome version uses an automatic update channel. It might be wise to ask @Sainan for an automatic update disabled version for chromium-based browsers as well. ( Just my thought n opinion, I could be wrong tho).

**Comment by FireMasterK** [comment]
> > Can we make it work in our system though?
> > can someone help with the changes to revert and bundling the extension package for chromium.
> > or provide zip of an working version, I tried **13.12.1** didn't work.
> 
> I can do (done for myself) that for firefox but not for Chrome. The chrome version uses an automatic update channel. It might be wise to ask @Sainan for an automatic update disabled version for chromium-based browsers as well. ( Just my thought n opinion, I could be wrong tho).
> 
> There is another option too... Just get paste the Linkvertise bypass in custom bypass and you'll be done. (I haven't tried myself).

https://github.com/StuffNoOneCaresAbout/Universal-Bypass

I created a fork with those commits reverted and changed the updating mechanism to use my fork.

**Comment by anglophile** [comment]
One thing I wish was bypassed was the "Install Lookbox" option. This extension, from what I heard, is straight up malware that steals any passwords stored in your browser. Is there a way to do this?

**Comment by seengebr** [comment]
![image](https://user-images.githubusercontent.com/67361849/85512978-96419f80-b60b-11ea-87cb-9767747f1529.png)
 Lookbox is a damned virus, kind of scummy.

**Comment by HowToMakeFaceitAB** [comment]
hello @Sainan thank you for your excessive work and we dont mind the fact that it no longer bypasses link vertise, thanks for everything you've done

**Comment by Sainan** [comment]
@anglophile @seengebr I've already looked at Lookbox quite a while ago and all it does is change your search engine to Lookbox. I don't like it either, but it's certainly not a virus, and you can uninstall it again.

**Comment by bvneet** [comment]
> I created a fork with those commits reverted and changed the updating mechanism to use my fork.

How to change the updating mechanism?

**Comment by FireMasterK** [comment]
> How to change the updating mechanism?

Check out my fork, I have changed it there

**Comment by FireMasterK** [comment]
Hey @Sainan, how do I generate a build of the extension for Firefox? Is it possible create a build without php?

**Comment by Sainan** [comment]
@FireMasterK Bruh, just install PHP-CLI. I use PHP for all sorts of scripts when I'm not forced to use something else, like you're forced to use Javascript for an extension, just because you get shit done quickly.

**Comment by bvneet** [comment]
> 
> 
> > How to change the updating mechanism?
> 
> Check out my fork, I have changed it there

Still didn't get how to install your fork. I have 0 knowledge on this so please tell in a layman terms

**Comment by FireMasterK** [comment]
> > 
> > 
> > > How to change the updating mechanism?
> > 
> > Check out my fork, I have changed it there
> 
> Still didn't get how to install your fork. I have 0 knowledge on this so please tell in a layman terms

https://github.com/Sainan/Universal-Bypass/issues/1092#issuecomment-607381557
Except use [this](https://github.com/StuffNoOneCaresAbout/Universal-Bypass/archive/master.zip) link to download the zip

**Comment by Sainan** [comment]
Not a good idea. Master isn't built against Firefox (anymore).

**Comment by FireMasterK** [comment]
What's the best solution for Firefox then?

**Comment by Sainan** [comment]
The best solution is to get Universal Bypass from AMO. If you want to develop Universal Bypass, I would recommend using a Chromium-based browser. If you want to build your own version, I recommend you use the Firefox build script.

**Comment by LightWayUp** [comment]
First of all, I just want to say thanks to everyone who contributed to Universal Bypass, it's an awesome extension ❤.

Now regarding the Linkvertise bypass... although it can no longer be included by default in the bypass definitions, I tested that **adding it to the custom bypasses works fine** (for at least most links, if not all). So if you're willing to manually add it to your Universal Bypass installations, you can keep bypassing Linkvertise.

The solution was brought up a week ago but was untested:
> There is another option too... Just get paste the Linkvertise bypass in custom bypass and you'll be done. (I haven't tried myself).

*There is no need to build the extension from modified source or install from fork (if you're only looking to get the bypass back).* Instead, paste the following 40 lines into the "Custom Bypasses" section:

```js
domainBypass(/linkvertise\.(com|net)|link-to\.net/,()=>{
	let o={timestamp:new Date().getTime(),random:"375123"},
	url="https://linkvertise.net/api/v1/redirect/link/static"+location.pathname
	fetch(url).then(r=>r.json()).then(json=>{
		if(json&&json.data.link.id)
		{
			o.link_id=json.data.link.id
			url="https://linkvertise.net/api/v1/redirect/link"+location.pathname+"/target?serial="+btoa(JSON.stringify(o))
		}
	}).then(()=>fetch(url)).then(r=>r.json()).then(json=>{
		if(json&&json.data.target)
		{
			safelyNavigate(json.data.target)
		}
	})
	window.setTimeout=f=>setTimeout(f,1)
	window.setInterval=f=>setInterval(f,1)
	window.videojs={getAllPlayers:()=>[{
		on:(e,f)=>f(),
		controlBar:{
			progressControl:{
				disable:()=>{}
			}
		},
		pause:()=>{}
	}]}
	ensureDomLoaded(()=>{
		setInterval(()=>{
			ifElement(".modal.show .web-close-btn",b=>b.click())
		},1000)
		setTimeout(()=>{
			document.querySelectorAll(".todo-block .todo").forEach(d=>d.click())
			setTimeout(()=>ifElement(".todo-btn-nr",b=>{
				b.click()
				setTimeout(()=>ifElement(".btn.countdown-btn.first",a=>{
					countIt(()=>a.click())
				}),100)
			}),2000)
		},2000)
	})
})
```

The above is [taken directly from Sainan's commit to remove bypass of Linkvertise](https://github.com/Sainan/Universal-Bypass/commit/7379b1c8e594f53660693da2954f36169f805c6f#diff-2887743acf7994ba73802b2a328d8bc7L540-L580).

The benefits of this are:

* You can keep using the Universal Bypass you've already installed
* **It works across all browsers**: Chrome, Firefox, ...whatever you use

Of course, if Linkvertise changes their website in the future, this custom bypass could break, but for now it's working well 🙂.

**Comment by Cyberavater** [comment]
>**adding it to the custom bypasses works fine** 

No, just adding the domain bypass solves half of the problem; #1325
Try this link: https://linkvertise.com/95811/angryisgreat
Somehow you need to update "unsafelyNavigate=target=>{" with custom bypass (which should be possible as @Sainan said). But sadly, I'm no coder.

>Of course, if Linkvertise changes their website in the future, this custom bypass could break, but for now it's working well 🙂.

I personally don't want to give up to Linkvertise, We should create a GitHub page that handles Linkvertise custom bypass updates (maybe with help of @ikancupang ? or @FireMasterK ) Anyways, I would've created such a page and linked it here if I could figure it out fully.

**Comment by Shlushez** [comment]
@Sainan looks like they tricked you. I went on linkvertise and since we can't bypass we have to deal with the ads and stuff. So I did everything and then it accused me of bypassing but I didn't. So I infinitely does this. >:( WE WILL NOT FALL TO THEM

**Comment by Uranite** [comment]
> @Sainan looks like they tricked you. I went on linkvertise and since we can't bypass we have to deal with the ads and stuff. So I did everything and then it accused me of bypassing but I didn't. So I infinitely does this. >:( WE WILL NOT FALL TO THEM

what link is it? maybe someone added a retarded bypass check to it so you might need to wait extra 5-10 seconds even if u dont bypass

**Comment by ABOATDev** [comment]
Hello 
and if we use : 
https://online-coding.eu/api/LinkvertiseBypass.php?url=https://linkvertise.net/121383/codergauatammm1  In the Custom Bypasses? Universal-Bypass will not be responsible for the bypass but it will be https://online-coding.eu right ? 
From a legal point of view Universal-Bypass is not risking anything anymore, right?

Who could make a Custom Bypass from Linkvertise with the api online-coding.eu?


ps : Sorry, I'm French and I use a translator.

**Comment by Sainan** [comment]
You can use custom bypasses. I'm just not allowed to add it to Universal Bypass' bypass definitions.

**Comment by amhluk** [comment]
Not too familiar with Javascript but from the site ABOATDev found you can add the following custom bypass:

```
domainBypass(/linkvertise\.(com|net)|link-to\.net/, () => {
    url="https://online-coding.eu/api/LinkvertiseBypass.php?url=" + location
    safelyNavigate(url)
})

domainBypass(/online-coding\.eu/, () => {
    if(location.pathname.includes("LinkvertiseBypass")) {
        let xhr=new XMLHttpRequest()
        xhr.onload=()=>{
            safelyNavigate(xhr.responseText)
        }
        xhr.open("GET",location)
        xhr.send()
    }
})
```

Basically redirects linkvertise to online-coding, and from online coding loads the page again to get the response text, may try to optimize code later

**Comment by imakealol** [comment]
> Not too familiar with Javascript but from the site ABOATDev found you can add the following custom bypass:
> 
> ```
> domainBypass(/linkvertise\.(com|net)|link-to\.net/, () => {
>     url="https://online-coding.eu/api/LinkvertiseBypass.php?url=" + location
>     safelyNavigate(url)
> })
> 
> domainBypass(/online-coding\.eu/, () => {
>     if(location.pathname.includes("LinkvertiseBypass")) {
>         let xhr=new XMLHttpRequest()
>         xhr.onload=()=>{
>             safelyNavigate(xhr.responseText)
>         }
>         xhr.open("GET",location)
>         xhr.send()
>     }
> })
> ```
> 
> Basically redirects linkvertise to online-coding, and from online coding loads the page again to get the response text, may try to optimize code later

Wow that works extremely well. You saved me a lot of time. I think it can be closed now ... :)

**Comment by hamad12a** [comment]
how it works?

**Comment by Lack3** [comment]
nah its broken now!!

**Comment by Lack3** [comment]
online coding's api is broken it just says "Error". Can anyone fix?

**Comment by FireMasterK** [comment]
My [fork](https://github.com/StuffNoOneCaresAbout/Universal-Bypass) still works.

**Comment by Lack3** [comment]
nope

**Comment by Lack3** [comment]
FireMasterK fork does work

**Comment by amhluk** [comment]
@Lack3 Tested some links, still works. Could you provide a sample link that does not work?

**Comment by Cyberavater** [comment]
All methods are working perfectly. I also added a test link long before he complained. 

https://github.com/Sainan/Universal-Bypass/issues/1323#issuecomment-646942768

**Comment by Toshiba1127** [comment]
The script still work so far for me

**Comment by SH1FT3RX** [comment]
> > > Can we make it work in our system though?
> > > can someone help with the changes to revert and bundling the extension package for chromium.
> > > or provide zip of an working version, I tried **13.12.1** didn't work.
> > 
> > 
> > I can do (done for myself) that for firefox but not for Chrome. The chrome version uses an automatic update channel. It might be wise to ask @Sainan for an automatic update disabled version for chromium-based browsers as well. ( Just my thought n opinion, I could be wrong tho).
> > There is another option too... Just get paste the Linkvertise bypass in custom bypass and you'll be done. (I haven't tried myself).
> 
> https://github.com/StuffNoOneCaresAbout/Universal-Bypass
> 
> I created a fork with those commits reverted and changed the updating mechanism to use my fork.

THANK YOU SO MUCH LOVE <3

**Comment by SnowFK** [comment]
> Não estou muito familiarizado com Javascript, mas no site que ABOATDev encontrou, você pode adicionar o seguinte bypass personalizado:
> 
> ```
> domainBypass(/linkvertise\.(com|net)|link-to\.net/, () => {
>     url="https://online-coding.eu/api/LinkvertiseBypass.php?url=" + location
>     safelyNavigate(url)
> })
> 
> domainBypass(/online-coding\.eu/, () => {
>     if(location.pathname.includes("LinkvertiseBypass")) {
>         let xhr=new XMLHttpRequest()
>         xhr.onload=()=>{
>             safelyNavigate(xhr.responseText)
>         }
>         xhr.open("GET",location)
>         xhr.send()
>     }
> })
> ```
> 
> Basicamente, redireciona o linkvertise para a codificação online e, a partir da codificação online, carrega a página novamente para obter o texto de resposta, pode tentar otimizar o código mais tarde

What is the difference between this code and @FireMasterK ?

**Comment by FireMasterK** [comment]
> > Não estou muito familiarizado com Javascript, mas no site que ABOATDev encontrou, você pode adicionar o seguinte bypass personalizado:
> > 
> > ```
> > domainBypass(/linkvertise\.(com|net)|link-to\.net/, () => {
> >     url="https://online-coding.eu/api/LinkvertiseBypass.php?url=" + location
> >     safelyNavigate(url)
> > })
> > 
> > domainBypass(/online-coding\.eu/, () => {
> >     if(location.pathname.includes("LinkvertiseBypass")) {
> >         let xhr=new XMLHttpRequest()
> >         xhr.onload=()=>{
> >             safelyNavigate(xhr.responseText)
> >         }
> >         xhr.open("GET",location)
> >         xhr.send()
> >     }
> > })
> > ```
> > 
> > Basicamente, redireciona o linkvertise para a codificação online e, a partir da codificação online, carrega a página novamente para obter o texto de resposta, pode tentar otimizar o código mais tarde
> 
> What is the difference between this code and @FireMasterK ?

The code in that uses an external closed source server to bypass, I wouldn't recommend it due to a variety of privacy/transparency concerns.

**Comment by ajjmin** [comment]
Custom bypass from online coding api doesn't work anymore. It just shows error everytime.

**Comment by ajjmin** [comment]
Also @FireMasterK how to use your port on firefox for android?

**Comment by Uranite** [comment]
> Custom bypass from online coding api doesn't work anymore. It just shows error everytime.

Seems like that website is dead

**Comment by amhluk** [comment]
Hacked together something quick based on the other branch, does not rely on online coding:

```
domainBypass(/linkvertise\.(com|net)|link-to\.net/,()=>{
    // 64 bit decode
    if (window.location.href.toString().indexOf("?r=") != -1) {
        const urlParams = new URLSearchParams(window.location.search);
        const r = urlParams.get('r')
        safelyNavigate(atob(decodeURIComponent(r)));
    }
    
    // normal redirect
    let o={timestamp:new Date().getTime(),random:"6548307"},
	url="https://publisher.linkvertise.com/api/v1/redirect/link/static"+location.pathname;
	fetch(url).then(r=>r.json()).then(json=>{
		if(json&&json.data.link.id)
		{
			o.link_id=json.data.link.id
			url="https://publisher.linkvertise.com/api/v1/redirect/link"+location.pathname+"/target?serial="+btoa(JSON.stringify(o))
		}
	}).then(()=>fetch(url)).then(r=>r.json()).then(json=>{
		if(json&&json.data.target)
		{
			safelyNavigate(json.data.target)
		}
	})
})
```

Seems working for me. May have some bugs. Will probably clean up the code later.

**Comment by Cyberavater** [comment]
>Seems working for me. May have some bugs. Will probably clean up the code later.

Not working mate. Try this link; https://linkvertise.com/95811/angryisgreat

**Comment by amhluk** [comment]
> > Seems working for me. May have some bugs. Will probably clean up the code later.
> 
> Not working mate. Try this link; https://linkvertise.com/95811/angryisgreat

Weird, link works for me, what browser and os are you using?

**Comment by Cyberavater** [comment]
> > > Seems working for me. May have some bugs. Will probably clean up the code later.
> > 
> > 
> > Not working mate. Try this link; https://linkvertise.com/95811/angryisgreat
> 
> Weird, link works for me, what browser and os are you using?
> Could you also test this link if it works for you and the response from the link: https://publisher.linkvertise.com/api/v1/redirect/link/95811/angryisgreat/target?serial=eyJ0aW1lc3RhbXAiOjE2MDAyMzExMTkzNDAsInJhbmRvbSI6IjY1NDgzMDciLCJsaW5rX2lkIjoxMjI4MzgwMX0=

![Screenshot (6)](https://user-images.githubusercontent.com/32187927/93334066-1ca20200-f846-11ea-91c6-2db400f5c30e.png)

**Comment by FireMasterK** [comment]
> > > Seems working for me. May have some bugs. Will probably clean up the code later.
> > 
> > Not working mate. Try this link; https://linkvertise.com/95811/angryisgreat
> 
> Weird, link works for me, what browser and os are you using?
> Could you also test this link if it works for you and the response from the link: https://publisher.linkvertise.com/api/v1/redirect/link/95811/angryisgreat/target?serial=eyJ0aW1lc3RhbXAiOjE2MDAyMzExMTkzNDAsInJhbmRvbSI6IjY1NDgzMDciLCJsaW5rX2lkIjoxMjI4MzgwMX0=

This won't work for all links because of the "linkvertise downloader", you'll need to spoof the user agent to an IOS device to bypass that.

**Comment by amhluk** [comment]
ok, I see, gonna take more investigation. Doesn't seem like I can just add useragent directly to the script using fetch() api or XMLHttpRequest().

**Comment by Toshiba1127** [comment]
Can you bypass exe downloading? i don't want to download it, but download original file instead https://linkvertise.com/162287/thearmkingamongusiosmodmenu?o=sharing

**Comment by FireMasterK** [comment]
Yep, my [fork](https://github.com/StuffNoOneCaresAbout/Universal-Bypass) can do that :)

**Comment by Toshiba1127** [comment]
Ok, I will try
Would the extension still be updating even i use your fork? for example the original repo updated something

**Comment by FireMasterK** [comment]
Yes, you will still get updates from this repo.

**Comment by Toshiba1127** [comment]
Alright thanks
Working perfectly!

**Comment by Cyberavater** [comment]
@FireMasterK Do you need to manually update your fork or does it gets update automatically?

**Comment by FireMasterK** [comment]
Currently, it's manual atm, but I do plan on automating it sometime in the future, maybe with GitHub actions.

**Comment by SnowFK** [comment]
> Currently, it's manual atm, but I do plan on automating it sometime in the future, maybe with GitHub actions.

Your fork is the same of the Sainan or he has some bypass different? 🤨

**Comment by FireMasterK** [comment]
The only difference between my fork and this repository is that my fork has a few reverted commits which add back bypasses for Linkvertise and has some changes to the updating system to update from the fork.

**Comment by SnowFK** [comment]
> The only difference between my fork and this repository is that my fork has a few reverted commits which add back bypasses for Linkvertise and has some changes to the updating system to update from the fork.

Your fork is updated with the repository same version of Sainan or are different versions?

**Comment by FireMasterK** [comment]
It's based on the same version of this repository, you should have all the latest bypasses from here too.

**Comment by SnowFK** [comment]
> It's based on the same version of this repository, you should have all the latest bypasses from here too.

using you fork i dont need use the bypass addictions you did for the Link Vertise in the Tampermonkey extension?

**Comment by FireMasterK** [comment]
Yes, you don't need to.

**Comment by kevine2408** [comment]
Well is this bypass able? https://www.h-gen.xyz/jZJww9zL4SZf?fxyvexR=qSIEMCjYdpPx73MEV

**Comment by FaolanX** [comment]
> Well is this bypassable? https://www.h-gen.xyz/jZJww9zL4SZf?fxyvexR=qSIEMCjYdpPx73MEV

@kevine2408 Link expired, but yeah you can bypass h-gen, use [FireMasterK's userscript](https://github.com/FireMasterK/BypassAdditions/blob/master/script.js) or the [fork](https://github.com/StuffNoOneCaresAbout/Universal-Bypass) (it might detect the fork)

**Comment by 10Meisterbaelle** [comment]
this is stupid, because Linkvertise still has very annoying things, like the chrome extension and the notifications

**Comment by 10Meisterbaelle** [comment]
> @anglophile @seengebr I've already looked at Lookbox quite a while ago and all it does is change your search engine to Lookbox. I don't like it either, but it's certainly not a virus, and you can uninstall it again.

i dont like installing a sketchy browser extension
