### ISSUE TITLE
add bypass 10sec wait indihome homepage

### ISSUE THREAD

**Issue by ilhamepri** [Sainan/Universal-Bypass#1326]
link : https://welcome.indihome.co.id/indihome-smart

**Comment by Sainan** [comment]
Could you elaborate?

**Comment by ilhamepri** [comment]
my pleasure, where to start ?

**Comment by Sainan** [comment]
Maybe provide some information on what you need a bypass for?

**Comment by Uranite** [comment]
indihome is an interner provider, so sometimes when you browse the internet. the link will be changed to that for indihome to advertise themself, its like a redirect link but theres a button on bottom right you need to click but for some reason the link doesnt work if you copy and paste it like that

**Comment by Sainan** [comment]
My condolences for having such a shit internet provider, but because I don't have indihome, you're gonna have to put in a bit of effort here.

**Comment by Uranite** [comment]
yeah, its like a welcome message when u turn on ur pc and go to a website

**Comment by ilhamepri** [comment]
i'll provide the things soon

**Comment by 3xploiton3** [comment]
> link : https://welcome.indihome.co.id/indihome-smart

maybe you can block by dns level, its like GSM provider (XL/AXIS)

**Comment by Uranite** [comment]
> When I say "you're gonna have to put in a bit of effort here", I mean someone who uses indihome will have to add the bypass and submit a PR. I can't just make a guess about what might work and then break the internet for everyone who uses indihome.

i dont know about coding and also for some reason im not getting the indihome greet website thingy

**Comment by RobbyAJM** [comment]
I subscribe to indihome internet provider and that promotion page appears about 5 times a day on my computer to advertising their products. (which is annoying)

The skip button will always appear even its at the first countdown.
The button element is only like this
`div.button-lanjut`
So, simple js script like below is must be working on it and I've test it through console
```
document.querySelectorAll("div.button-lanjut").forEach(a=>{
  a.click();
})
```

@Sainan please provide documentation of injection_script.js functions or atleast tell me how to do debug? So I can contribute for anothers URLs

**Comment by Sainan** [comment]
@RobbyAJM The injection script is more or less the same as custom bypasses, and all differences are documented in the injection script.

**Comment by Sainan** [comment]
Anyway, you Indihome consumers might try this custom bypass:
```Javascript
domainBypass("welcome.indihome.co.id",ifElement("div.button-lanjut",a=>a.click()));
```

**Comment by RobbyAJM** [comment]
> Anyway, you Indihome consumers might try this custom bypass:
> 
> ```js
> domainBypass("welcome.indihome.co.id",ifElement("div.button-lanjut",a=>a.click()));
> ```

Works good, did you added/updated the bypass already? Its already redirected although I do nothing.

**Comment by Sainan** [comment]
If you add it to your custom bypasses, then it will execute (big shock, I know). I have not added it yet, as I am waiting for the people in this thread to say that it works.

**Comment by RobbyAJM** [comment]
Dude, wait... seems like something wrong.
I didn't even know how to run and where the injection_script.js can be executed, but yes I update the injection_script.js

update:
https://welcome.indihome.co.id/indihome-smart is now redirecting to www.indihome.co.id

**Comment by Sainan** [comment]
You don't need to use Universal Bypass in dev mode, you can just create a custom bypass in the options, and it will be executedi n the same context as the injection script.

**Comment by RobbyAJM** [comment]
Ah, yeah I forgot about that, I haven't check on the Universal Bypass icon, there's textarea to paste my custom scripts.
My bad. Thanks.

Update: I've tried the script that you share, its triggering alert like this:
![bypass](https://user-images.githubusercontent.com/29008865/86378524-f42d5180-bcb3-11ea-9035-1e712672e96c.png)

**Comment by Uranite** [comment]
> Ah, yeah I forgot about that, I haven't check on the Universal Bypass icon, there's textarea to paste my custom scripts.
> My bad. Thanks.
> 
> Update: I've tried the script that you share, its triggering alert like this:
> ![bypass](https://user-images.githubusercontent.com/29008865/86378524-f42d5180-bcb3-11ea-9035-1e712672e96c.png)

it might work when the website appears automatically rather than you visiting it because if you visit it it will redirect to indihome.co.id

**Comment by Sainan** [comment]
My bad, it should be like this:
```Javascript
domainBypass("welcome.indihome.co.id",()=>ifElement("div.button-lanjut",a=>a.click()));
```

**Comment by RobbyAJM** [comment]
No more alert... seems like its work as supposed to

**Comment by Sainan** [comment]
Sound good. Can anyone else confirm that this bypass works (ideally for several days) and doesn't break your internet?

**Comment by RobbyAJM** [comment]
I just met with the counter...
https://youtu.be/UHXyq7lbims
