### ISSUE TITLE
[Request] ur-ly.xyz

### ISSUE THREAD

**Issue by KT315E** [Sainan/Universal-Bypass#1328]
Request ur-ly.xyz to be supported.

Example:: https://ur-ly.xyz/YfbvM9b

After solving the captcha. we have to click the button manually to go to the next site. The re-direction is not happening automatically.
The timer is not getting killed.

THX.

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
