### ISSUE TITLE
linvertise.com

### ISSUE THREAD

**Issue by brqeden1234** [Sainan/Universal-Bypass#1332]
Hi there. I am part of a discord server that posts free accounts to a plethora of services however. these are all linkvertise links and its annoying as hell. Please please please fix this or link an old version that still bypasses

**Comment by Uranite** [comment]
d3af8c5259bd72a4557910d38f2e1ef0c68a8319

**Comment by Uranite** [comment]
and btw can you give me an invite to ur free account service discord? would be cool, i wont use universal bypass

**Comment by brqeden1234** [comment]
yes heres a discord link. https://discord.gg/cgMUj5g
also. how do i download that version? im new to github

**Comment by Uranite** [comment]
go to commits, scroll down until u see that version and press the <> button and click the download as zip

**Comment by Sainan** [comment]
Pro tip: Don't start your messages with "Hi there. I commit a lot of crimes."
