### ISSUE TITLE
[ASK] How to disable Universal bypass on spesific website?

### ISSUE THREAD

**Issue by Dhanamerdeka** [Sainan/Universal-Bypass#1333]
Hello anyone can you help me how to excluse any website so they not be skipped automatically with universal bypass?
example
i want only ouo.io run like normal without universal bypass...
how can i add that to whitelist?

**Comment by Sainan** [comment]
> i want only ouo.io
No you don't. If Universal Bypass is being detected and you're being forced to disable it, please create a "bypass detected" ticket.
