### ISSUE TITLE
tl.gd

### ISSUE THREAD

**Issue by dudeedud4** [Sainan/Universal-Bypass#1335]
Example Link: http://tl.gd/n_1sr9idp
 Where it goes: https://tl.gd/n_1sr9idp
Where it SHOULD go: https://www.twitlonger.com/show/n_1sr9idp

**Comment by Sainan** [comment]
Works for me

**Comment by alpcinar** [comment]
Doesn't work for me either. Same results as the OP.

**Comment by Sainan** [comment]
Well, provide more information.

**Comment by Uranite** [comment]
works for me

**Comment by alpcinar** [comment]
> Well, provide more information.

Well your FAQ page doesn't include an issue template. You can try to be more open and tell us what you need to know.

**Comment by Sainan** [comment]
There are issue templates here on Github but it would help to know the browser, browser version, and extension version.

**Comment by Sainan** [comment]
#1336 seems like a good example for how to describe the problem 🙃

**Comment by alpcinar** [comment]
> There are issue templates here on Github but it would help to know the browser, browser version, and extension version.

#1336 does not contain any of these info but you do you. Good luck with your extention. 😉

**Comment by Sainan** [comment]
It does not but it actually helps me reproduce the issue which

> Example Link: http://tl.gd/n_1sr9idp

did not

**Comment by Uranite** [comment]
the problem is the https, http work but https dont and will show 404 error
