### ISSUE TITLE
twitlonger.com (tl.gd)

### ISSUE THREAD

**Issue by Yaanu** [Sainan/Universal-Bypass#1336]
When using Twitter and bypassing their t.co links to get to a TwitLonger link, the bypasser puts you at the shortlink which TwitLonger uses, rather than the actual site which for whatever reason is not being triggered when using Universal Bypass. As a result, the result page delivers a 404 error.

For example, if you find a Tweet with a TwitLonger link (https://twitter.com/Ewok/status/1272690715101929477) and click through its t.co shortlink (https://t.co/UyjxEn2xkA?amp=1), you'll be put through to the tl.gd shortlink used (https://tl.gd/n_1sr9bk7) rather than the actual twitlonger.com page (https://twitlonger.com/show/n_1sr9bk7).

**Comment by Sainan** [comment]
Seems like an issue with TwitLonger but I guess it's up to me to fix 🙄
