### ISSUE TITLE
get-url.com

### ISSUE THREAD

**Issue by GiliceJani** [Sainan/Universal-Bypass#1339]
http://get-url.com/download.php?url=NAZs2f3JVOYsEQ8+d1PxKNkn3JzcNGV0C0k5zT8wgeKcxkmt3wB/Qecy0sqL7/+A1PX5MLElueV31hVcSX1wstlC/Gx18EAB5iAxrrxbccP8TOuQOcrRSai9o5KVf+K6bnjTOnuB7jsG7SbVKgAKlfDgcX75aQ7fhBRW+Lo236I/ursQExxhfO7qxl5GpGuF/tSYq5rO6XgL62+v0+lR6Wav6Zgei96Mwv33MX8vMOf+QFPT9pwB4LJgN63wf+kvlTmEtpU+5XZSQmCywYZH6PWfl/sOnBCuSmoTLHjQXkHmvgeTb1wVaOLStlh6jutxwPzdJWllWkE/Yqw/LPxFFLByjMjW1M1WpsglQGJiwdVQ2Gu0kawJO8v0AGlckOxamqvRXvRpLIs1b/9TutBVDhjYdCAa5fILCjnPeAhl9UGvYn9F7IKw8kMx1vbCT4E6cLTeoiCh/dPrdkNn+jhOoXEBdXwisH6VZLoXwiCMvxo7BeYVmuAEosp1J8CcDo6wJeP0Z0cMgtPf3jktECrg6QlLP2vIs6pkDIlSDSlhM+zamFcTvgcCvlqUaD3ufMcyS67zlMu67I6NRPq45hxEV2ptT6ad82EAs3nncUUC020fxglCKT3lNVZODWJcCMoxJwCTMu46TQRUOQ++0XJvXlYs7OnOD2haVaPntqlh9NwyzH6OKPTPe1X/SLYxTmIlRhCksd0QCAHt6Lmu5SJSSpgslu1bR8wRTFJx6O9L1NPmYMMDne0yScBZSdxl4X3K9ImlpUV+M19VT5SqhGNZt41tE4aRWJLuUGQGfsYHXpyJJNuMo0sagZWIQid7gTg9W9GoeoNsCQTYBnbczkHqdkIwTQaApom4PgLohy50Rp2XnV8X1HcnwwB/suYjzCG49xefbVobPnNcWPHgq+jr2I0ONCWYKMZYZOMW89qeggxQDqAbU7r5O6agPhyO9Q2s

**Comment by Uranite** [comment]
the website looks the same as bluemediafiles.com which are already bypassed

**Comment by aimansddiq** [comment]
It doesn't bypass for me

**Comment by FireMasterK** [comment]
I'm aware this is a terrible way of doing it, but it works, there's a server side timer check by the looks of it.
```
domainBypass("get-url.com", () => {
	awaitElement("#nut[src=\"img/NUTDL.jpg\"]", () => {
		ifElement("form[action=\"geturl.php\"]", f => {
		    f.submit()
	        })
	})
})
```

**Comment by Bugster** [comment]
Copying the bluemediafiles.com code and changing the url worked for me

**Comment by Sainan** [comment]
Example link seems dead.
