### ISSUE TITLE
Please fix

### ISSUE THREAD

**Issue by Shadmanislam** [Sainan/Universal-Bypass#1340]
![image](https://user-images.githubusercontent.com/57795574/85772522-be7deb00-b73e-11ea-9ea1-dfa024925d73.png)
![image](https://user-images.githubusercontent.com/57795574/85772707-ec632f80-b73e-11ea-9686-2020f574966c.png)

**Comment by Sainan** [comment]
Where's the reproducable steps? And which version of Universal Bypass?
