### ISSUE TITLE
[Req] binbox.io

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1341]
Eg link: http://binbox.io/UtT9E#4UkwKgM6

Note: It's bypassable via Adsbypasser.

**Comment by FireMasterK** [comment]
https://github.com/adsbypasser/adsbypasser/blob/0314b280e8cfe9ee53e31cc0b9bf149405dc1fe0/src/sites/paste/binbox.io.js
https://github.com/adsbypasser/adsbypasser/blob/ad60c667503aa370e717904f9067d27a2483b141/src/sites/link/binbox.io.js
This is how adsbypasser bypasses it.

**Comment by Cyberavater** [comment]
#163

**Comment by Cyberavater** [comment]
@Sainan Can you add this fix? Since it's already available.

**Comment by Sainan** [comment]
Sorry, my interest in Universal Bypass is greatly degraded. I'm always open to a PR and'll make sure to distribute it, but I'm not gonna invest a lot of effort into writing my own code for it anymore. I hope you can understand.

**Comment by Cyberavater** [comment]
Understandable but thank you so much anyway for all the hard work you did till now, we all _really_ appreciate it.

P.S. Using open-source code is not stealing tho, (IMO).
Anyways, again, thank you for everything! <3
