### ISSUE TITLE
https://cut.my.id/****,https://dogecoin.host/sl/********

### ISSUE THREAD

**Issue by Harfho** [Sainan/Universal-Bypass#1343]
Not only on those websites, there are still more of them i use to encounter every time.
But as usual universalB will always say , the link will be bypass next time for other UB users when they also encounter it.
But anytime i visit that link again it wont be bypass, i haved visited that same link more than 10 times , But it doesn't get bypass.
I also have question?. How can i use the custom Bypasser , If you can make video for this to help explain , i will be grateful. Thanks

**Comment by Sainan** [comment]
Could you provide an example link? Also, `dogecoin.host` sounds like a Faucet. If you're having issues with "links" from faucet services, then please accept that these aren't links, they're integrated adwalls.

**Comment by Harfho** [comment]
How can i use the custom Bypasser , If you can make video for this to help explain , i will be grateful
