### ISSUE TITLE
is there anyway to bypass the download counter links at  https://www.thesimsresource.com/

### ISSUE THREAD

**Issue by lonedove28** [Sainan/Universal-Bypass#1346]
here is a link to a download counter
https://www.thesimsresource.com/downloads/download/itemId/1496803

**Comment by FireMasterK** [comment]
```
domainBypass(/www.thesimsresource.com/,()=>{
    var setInterval=window.setInterval
    window.setInterval=f=>setInterval(f,1)
})
```
Except the regex should only match urls like `https://www.thesimsresource.com/downloads/download/itemId/1496803`

**Comment by Sainan** [comment]
Didn't we have this somewhere already? Can't bypass the download timer because then you can't download the file, as is the case with most download sites, but I can bypass the fake "loading" for the details page.
