### ISSUE TITLE
[request] zedge.net

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1347]
example:
https://www.zedge.net/ringtone/543ce4cf-b253-3cc8-931a-c686fb28f361

![image](https://user-images.githubusercontent.com/19517680/85969123-f8761800-b9f0-11ea-8c72-67bd32821e18.png)

**Comment by FireMasterK** [comment]
```
domainBypass(/www.zedge.net/,()=>{
    var setInterval=window.setInterval
    window.setInterval=f=>setInterval(f,1)
})
```
The regex is whacky but it works.

**Comment by 3xploiton3** [comment]
sorry i test but doesn't work

![image](https://user-images.githubusercontent.com/19517680/86080528-507a5080-babd-11ea-8cdc-7620182913e8.png)
https://www.zedge.net/ringtone/7d7a1e22-2299-35de-b41d-13b332743f1e

**Comment by Sainan** [comment]
You're probably on Firefox.

**Comment by 3xploiton3** [comment]
> You're probably on Firefox.

yes, firefox version 77

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/86122342-51c76f80-baf5-11ea-80a1-7f7c5aa9f710.png)
Something is wrong, it doesn't seem to be working on brave.

**Comment by Sainan** [comment]
Of course, nothing works in Brave. Brave doesn't support Universal Bypass. Universal Bypass doesn't support Brave.

**Comment by FireMasterK** [comment]
The custom bypass I wrote works in brave tho 🤔

**Comment by Sainan** [comment]
I'm not sure how you consume Universal Bypass on Brave, but make sure your bypass definitions are up-to-date.

**Comment by FireMasterK** [comment]
I run Universal Bypass on Brave in development mode with my fork. Everything is up to date with my fork.
![image](https://user-images.githubusercontent.com/20838718/86141244-72042800-bb0f-11ea-82a6-544f68f865bc.png)

**Comment by FireMasterK** [comment]
Ok, I figured it out, when I reinstalled the extension, it magically fixed itself.
