### ISSUE TITLE
[Req] w.akwam.org

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1348]
Eg link: http://w.akwam.org/5bddc72e1c730

5sec wait at the end.

**Comment by FireMasterK** [comment]
```
domainBypass(/akwam.org/,()=>{
    var setInterval=window.setInterval
    window.setInterval=f=>setInterval(f,1)
    awaitElement("#timerHolder a",a=>a.click())
})
```
This is a whacky bypass but it works, @Sainan can we have the constants in https://github.com/Sainan/Universal-Bypass/blob/bcf014063a2199b8f41148c361875b41c306f3fc/injection_script.js#L7 set for custom bypasses?
Without this the `var setInterval=window.setInterval` necessary for custom bypasses.

**Comment by Sainan** [comment]
@FireMasterK, you should have access to that. Where do you think your "awaitElement" or "safelyNavigate" are defined? :P

**Comment by FireMasterK** [comment]
Oh yeah, I messed up my domain match before, it works perfectly ;)
