### ISSUE TITLE
flexlinkspro.com

### ISSUE THREAD

**Issue by accessibl** [Sainan/Universal-Bypass#1349]
flexlinkspro.com, track.flexlinkspro.com, and so on...

**Comment by FireMasterK** [comment]
You need to give example links, not domains

**Comment by accessibl** [comment]
Sure:

https://track.flexlinkspro.com/a.ashx?foid=1133471.140212747&foc=1&fot=9999&fos=1&url=https%3A%2F%2Fwww.udemy.com%2Fstep-by-step-guide-to-machine-learning-course

https://www.udemy.com/course/step-by-step-guide-to-machine-learning-course

:-)

**Comment by Sainan** [comment]
What is there to be bypassed?

**Comment by FireMasterK** [comment]
Tracker bypass
