### ISSUE TITLE
Bypass uninstalling itself over and over

### ISSUE THREAD

**Issue by ZibiCat** [Sainan/Universal-Bypass#1355]
Hello,

I'm having an issue with UB. I have to reinstall it over and over because the extension seems to delete itself over and over. Is this supposed to happen? I have to drag it into extensions every time I start chrome.

I'm using the zip file to install it and I'm using Google Chrome.

**Comment by Sainan** [comment]
Just click the "x" on the popup when you get it, or you can also patch chrome to stop bothering you, as discussed in #1311.

**Comment by ZibiCat** [comment]
> Just click the "x" on the popup when you get it, or you can also patch chrome to stop bothering you, as discussed in #1311.

I never mentioned a popup. The extension just vanishes after a reboot and a chrome restart. Is this normal?

**Comment by Uranite** [comment]
> > Just click the "x" on the popup when you get it, or you can also patch chrome to stop bothering you, as discussed in #1311.
> 
> I never mentioned a popup. The extension just vanishes after a reboot and a chrome restart. Is this normal?

extract the file, maybe something is clearing your temp folder

**Comment by Cyberavater** [comment]
@Sainan Pin this issue as am sure many are having this same issue.

**Comment by Sainan** [comment]
I've updated https://universal-bypass.org/install to hopefully avoid this confusion although I didn't think the Downloads folder was temporary, might just be Chrome using the temp folder for the drag & drop operation, which would be hilariously inefficient.

**Comment by Cyberavater** [comment]
It's not the location of the zip, rather the extraction of the zip, which is a temp folder.

**Comment by Cyberavater** [comment]
You need to extract in a permanent folder (and then add the folder) rather than having the zip in a permanent folder.

**Comment by Sainan** [comment]
Could you elaborate on that?

**Comment by Cyberavater** [comment]
https://github.com/Sainan/Universal-Bypass/issues/1355#issuecomment-652941946

**Comment by Sainan** [comment]
I don't get it, you'd have to purposefully extract the zip into the temp folder at which point what are you even doing?

**Comment by Cyberavater** [comment]
Adding zip= Extracts to temp>Loads extension from temp folder>Temp folder gets deleted after a time> Extension is uninstalled.
Adding EXTRACTED zip folder (from permanent directory)= Loads extension from permanenet folder> Folder not deleted>Extension is not uninstalled.

**Comment by Uranite** [comment]
windows + R and type %temp% and enter

**Comment by Sainan** [comment]
I see what you mean now, it's weird that chrome does it that way. Hopefully now https://universal-bypass.org/install is correct.
