### ISSUE TITLE
Documentation for Custom Bypass

### ISSUE THREAD

**Issue by RobbyAJM** [Sainan/Universal-Bypass#1358]
1. As the title says, there's must be documentation for each function, well although contributors are able to see manually what the code means but at least there's a documentation for better learning session.
2. How to debug the injection scripts? Is the best way was only copy-paste the whole injection_script.js into the console?

**Comment by Sainan** [comment]
All the important functions are documented here:
![image](https://user-images.githubusercontent.com/63328889/86375823-7bfc6700-bc86-11ea-936e-ed739dfa8d58.png)

To debug it, you just run it, and if there's an error, you will see it in the console. You can also use console.trace, console.log, and all your other friends.
