### ISSUE TITLE
https://shorter.fun/

### ISSUE THREAD

**Issue by Harfho** [Sainan/Universal-Bypass#1359]
with some random words at the end like 
https://shorter.fun/NdFiv

**Comment by Uranite** [comment]
already has crowd bypass

**Comment by Harfho** [comment]
i know some javascript, Please can you tell how to go about with the custom bypass i need it.

**Comment by Sainan** [comment]
This site is literally already bypassed

**Comment by Harfho** [comment]
> This site is literally already bypassed

i understand but any time i try it from here , no matter the time i do it , it wont bypass even when UB said next time i encounter that link it would be bypass. Or maybe its bcos ive not yet fully understand how UB works

**Comment by Uranite** [comment]
> > This site is literally already bypassed
> 
> i understand but any time i try it from here , no matter the time i do it , it wont bypass even when UB said next time i encounter that link it would be bypass. Or maybe its bcos ive not yet fully understand how UB works

its bypassed go try it

**Comment by Sainan** [comment]
The link you provided seems to be generated by a faucet service. You need to understand that these "shortened links" are not shortened links but actually integrated paywalls into the faucet service that you are using because the "link" is generated uniquely for you.
