### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated

### ISSUE THREAD

**Issue by JosephTico** [Sainan/Universal-Bypass#1360]
Getting the following error on Chrome v83:

![image](https://user-images.githubusercontent.com/8814190/86411804-e27b8800-bc7a-11ea-82f3-0782d93f37fa.png)

> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
> 
> **Context**: _generated_background_page.html
> **Stack Trace**: background.js:526 (resolveRedirect)

Extension version 13.12.1

**Comment by Sainan** [comment]
Not an error.

**Comment by FireMasterK** [comment]
That's a warning.
