### ISSUE TITLE
cshort.org

### ISSUE THREAD

**Issue by Annihilator4423** [Sainan/Universal-Bypass#1361]
https://cshort.org/C4kpHCuBQ6

it seems that this site hasn't been bypassed yet and idk if there is a way to add it so that all cshort.org is bypassed.

**Comment by Uranite** [comment]
already has crowd bypass

**Comment by Sainan** [comment]
Bad habit of mine to trust you there, it seems the crowd bypass is broken.

**Comment by Annihilator4423** [comment]
Ok, hope it's fixed soon :D also nice Plugin it's amazing!

**Comment by Uranite** [comment]
> Bad habit of mine to trust you there, it seems the crowd bypass is broken.

oh i think so too because when i go through the link it doesnt crowd bypass but i didnt think much about it and already forgot it lol

**Comment by Annihilator4423** [comment]
here is another one. (Adobe premier pro)

https://cshort.org/iYsmyZbwyF

idk if you have to bypass every single link or not but there's one just incase
