### ISSUE TITLE
universal-bypass.org/legal-battle-info

### ISSUE THREAD

**Issue by ImportTaste** [Sainan/Universal-Bypass#1368]
This is linked to within the extension itself to inform users of the lawsuit, but it leads to a 'Dead Link'.

**Comment by Uranite** [comment]
the lawsuit is already over

**Comment by ImportTaste** [comment]
Oh, then I guess the reference to it in the extension needs to be altered or removed.

**Comment by FireMasterK** [comment]
You're likely to be running an older version of the extension. The reference to that link has been removed a long time back.
