### ISSUE TITLE
not work on ugou.in

### ISSUE THREAD

**Issue by cisko99za** [Sainan/Universal-Bypass#1369]
hi, universal bypass not work at goldn-apps.com

eample link https://www.goldn-apps.com/p/learn-basics-of-forex-trading-for.html

**Comment by FireMasterK** [comment]
We need the link before that to fix this issue.

**Comment by cisko99za** [comment]
link is at my first post.
link: https://www.goldn-apps.com/p/learn-basics-of-forex-trading-for.html

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/86956636-05c09e80-c177-11ea-87ca-aa25e214ffbe.png)
As I said, you have to provide the link before this. Links like these require a specific referrer which is why we require the link before the link you sent.

**Comment by cisko99za** [comment]
ok now i've to understand! sorry.
link is: https://ugou.in/S6Anw

**Comment by cisko99za** [comment]
another issue: on chrome web store Universal Bypass there is not.
then i go on https://universal-bypass.org/install, drag "Universal Bypass for Chromium-based browsers.zip" into the extensions page, but when close my browser (vivaldi) and reopen it, i no longer have the extension. and i have to put it back!

**Comment by Uranite** [comment]
> another issue: on chrome web store Universal Bypass there is not.
> then i go on https://universal-bypass.org/install, drag "Universal Bypass for Chromium-based browsers.zip" into the extensions page, but when close my browser (vivaldi) and reopen it, i no longer have the extension. and i have to put it back!

It's either because of your browser, or something is clearing your temp folder. Try to extract Universal Bypass to a folder and drag that folder to your extension page.

**Comment by cisko99za** [comment]
tanxs for your suggestion. with this tricks work fine. as long as you don't move or rename the universal bypass folder, otherwise when you start it again the extension is missing again ... 
i have been using this extension for some time, then i changed my browser and i saw that it was no longer present on the chrome web store so to install this you have to do it from the site, using a zip file. however before it was more comfortable and stable, like all other extensions. why did it disappear from the chrome web store?

**Comment by Uranite** [comment]
> tanxs for your suggestion. with this tricks work fine. as long as you don't move or rename the universal bypass folder, otherwise when you start it again the extension is missing again ... 
> i have been using this extension for some time, then i changed my browser and i saw that it was no longer present on the chrome web store so to install this you have to do it from the site, using a zip file. however before it was more comfortable and stable, like all other extensions. why did it disappear from the chrome web store?

It got removed by google because of "circumventing paywalls"

**Comment by cisko99za** [comment]
ok, understand. now wait your new fix for ugou.in !

**Comment by Sainan** [comment]
Could you please provide a non-broken example link and also the intended destination of that link?

**Comment by FireMasterK** [comment]
The link took me to http://www.mediafire.com/file/6j878ad2i91or7p/%25E0%25B9%2580%25E0%25B8%2588%25E0%25B8%2599.rar/file

I'm pretty sure that's the expected destination.

**Comment by Sainan** [comment]
Okay, you got to mediafire after `https://boomx5.com/wgDZsL/2` so a bypass would just have to read the "url" parameter

**Comment by cisko99za** [comment]
----   Could you please provide a non-broken example link and also the intended destination of that link?
again? link is at my post #3...... https://ugou.in/S6Anw
it is now easy to continue.... this link https://ugou.in/S6Anw reports to https://www.goldn-apps.com/p/learn-basics-of-forex-trading-for.html    then to https://www.forextrading9.online/p/if-you-have-just-entered-forex-world.html  then to https://boomx5.com/wgDZsL/2  and after captcha go to http://www.mediafire.com/file/6j878ad2i91or7p/%25E0%25B9%2580%25E0%25B8%2588%25E0%25B8%2599.rar/file    final destination. I hope this time it's all clear!

**Comment by FireMasterK** [comment]
Can this be closed? The website shows a 502.
They've shut down according to [this](https://www.beermoneyforum.com/threads/boomx5-high-cpm-25-1000-referral-20-daily-payments.58353/) link.
