### ISSUE TITLE
swatchseries.to

### ISSUE THREAD

**Issue by Burkino** [Sainan/Universal-Bypass#1370]
[LINK](https://www1.swatchseries.to/freecale.html?r=wedyJfjdCI6InJyTlhzawTJCY3ljbWmp6U0dcL0Qw2azJPaG5cL0ZKdnBOYTYybm40T21nNEdyMEYyNzBCUFpiR056bGJOZm5VVmJRaCIsIml2IjoiNDVlMzdlMTE0ZGZkZjA0NDRiNDdjYzQzNTBhZGIzMDIiLCJzIjoiNTRkYTgzMWY2NjY4ODZlZCJ9)
After selecting a site to watch a show on universal bypass closes the tab
Works fine when the website bypass is disabled
A direct link to it works fine but is broken when clicking on it from the main site such as here [LINK](https://www1.swatchseries.to/episode/Agents_of_S_H_I_E_L_D_s7_e7.html)

**Comment by respecting** [comment]
Doesn't happen for me on Google Chrome Canary and Firefox. Both on version 13.15.1.

**Comment by Sainan** [comment]
Also can't reproduce.
