### ISSUE TITLE
pnd.money

### ISSUE THREAD

**Issue by Slowftw** [Sainan/Universal-Bypass#1378]
https://pnd.money/test

![image](https://user-images.githubusercontent.com/46169656/87303720-fb413480-c4e9-11ea-9b07-180a69434ebc.png)
![image](https://user-images.githubusercontent.com/46169656/87303505-aa314080-c4e9-11ea-91b1-84563055410e.png)
![image](https://user-images.githubusercontent.com/46169656/87303496-a7cee680-c4e9-11ea-9e05-1382419423b0.png)

**Comment by respecting** [comment]
```js
domainBypass("pnd.money", () => {
    ifElement('#redirect_button',a=>{a.click()}); //Your redirecting will be ready in x seconds ...
    ifElement('#link-view',a=>{a.submit()}); //Please check the captcha box to proceed to the destination page.
})
```
The last page with a video is unskippable, it's based on time.

**Comment by Sainan** [comment]
Still, crowd bypass should work, and it seems broken for that site.
