### ISSUE TITLE
Add Cloud Sync for Options and Custom Bypasses

### ISSUE THREAD

**Issue by aztecrabbit** [Sainan/Universal-Bypass#1380]
Like in uBlock Origin, uMatrix, etc.

Btw Universal Bypass is must have extensions after uBlock Origin and Tampermonkey.
Thanks to timmyRS, Sainan, and other Contributors.

♥️♥️♥️

**Comment by Sainan** [comment]
It does technically have cloud sync support but since Google has banned it, I guess that's no use to you. Go complain to Google for being assholes.
