### ISSUE TITLE
The extension keeps deleting everytime i quit and reopen chrome

### ISSUE THREAD

**Issue by itschews** [Sainan/Universal-Bypass#1387]
idk why probably not your problem but I'm on a mac and please help if it happened to any1 else

**Comment by Sainan** [comment]
Be sure to follow the instructions at https://universal-bypass.org/install properly, especially the extraction part:
![image](https://user-images.githubusercontent.com/63328889/87876809-b2521a00-c9da-11ea-836a-f7966b483d30.png)

**Comment by AncientCatz** [comment]
I also always experience it, it's troublesome

**Comment by AncientCatz** [comment]
That too often happens to me, and is very troublesome

**Comment by Cyberavater** [comment]
You'll need to install the folder, NOT the zip!

**Comment by Sainan** [comment]
I'm still unsure why this happens for some people, but I've updated the instructions to tell people to use the "Load unpacked" button, but I don't know if that's any better than dragging and dropping.

**Comment by RbxAiden12114** [comment]
> I'm still unsure why this happens for some people, but I've updated the instructions to tell people to use the "Load unpacked" button, but I don't know if that's any better than dragging and dropping.

If you delete the folder that you loaded the extension with, it removes it from chrome too. Just keep the folder somewhere like in the Chrome Installation Directory. Hope this helps!

**Comment by Sainan** [comment]
From the previous comment and #1801, I take that the issue is in fact people deleting the folder, so I hope the updated installation guide is more than enough for everyone to know how not to do it:
![image](https://user-images.githubusercontent.com/63328889/107921989-a4b04300-6f6f-11eb-96ad-5678718bb99b.png)
