### ISSUE TITLE
grabify.link/ broken

### ISSUE THREAD

**Issue by Programmer-Pro** [Sainan/Universal-Bypass#1388]
So, going to https://grabify.link/ doesn't block the home page, this is normal. But then I noticed https://grabify.link/* is blocked, I couldn't create/manage links, view terms of service, Privacy policy, etc. So, I may be wrong, but I think only user-created links IP log.

**Comment by Sainan** [comment]
Boohoo, poor Programmer-Pro can't use a shitty IP logging service because he didn't turn off an option in an extension.
