### ISSUE TITLE
genlink.cc

### ISSUE THREAD

**Issue by ANightDazingZoroark** [Sainan/Universal-Bypass#1390]
https://genlink.cc/encrypted/VpTyJ04GFAd

![image](https://user-images.githubusercontent.com/56536620/87961240-04cd2c80-cae8-11ea-8d4c-e4cb4366f048.png)

**Comment by eribito** [comment]
@ANightDazingZoroark can you provide more links for me to test a bypass that I am make?

**Comment by ANightDazingZoroark** [comment]
https://genlink.cc/encrypted/Or2bM8

heres one from the same site i found it from
