### ISSUE TITLE
fcc.lc

### ISSUE THREAD

**Issue by vothisau** [Sainan/Universal-Bypass#1394]
https://fcc.lc/2020/06/reasons-why-website-analytics-is-important-for-your-business/?a=T05DRzhV

I can't skip bypass, please fix it.

**Comment by mnervik** [comment]
Universal Bypass gives following error in chrome

```VM529:15 [Universal Bypass] Couldn't define blurred
ODP @ VM529:15
(anonymous) @ VM529:255
(anonymous) @ VM529:1905
(anonymous) @ content_script.js:114```
