### ISSUE TITLE
Feature Req: make the crowd bypass links DB public

### ISSUE THREAD

**Issue by Ashish0804** [Sainan/Universal-Bypass#1399]
Consider making the crowd bypass links db public for bulk link extraction.

**Comment by FireMasterK** [comment]
#1357 this likely not going to happen as @Sainan wants crowd bypass to be centralized.

**Comment by Sainan** [comment]
Give me a good use case for "bulk link extraction" that's not leeching.

**Comment by Ashish0804** [comment]
> Give me a good use case for "bulk link extraction" that's not leeching.

Backing up content from piracy sites that have high chances of getting nuked.
I can see how someone can misuse the DB so even an api endpoint will be enough

**Comment by Sainan** [comment]
Poor piracy websites. You might wanna look into torrent.
