### ISSUE TITLE
tii.ai aka shrinkearn

### ISSUE THREAD

**Issue by kevin01523** [Sainan/Universal-Bypass#1405]
I just noticed it doesnt redirect or does not have any pop up anymore

https://tii.ai/RMzCg86

I think this link got already bypassed by crowdbypassing but the script that nake that work doesnt seem to work now it worked a few days ago

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by kevin01523** [comment]
@Sainan what i meant was crowd bypass ain't workin or rather universal bypass pop up or warning message doesn't seem to appear do if please could you check it out.i worked 24 hours ago but now even if i keep staring at the screen for 2 minutes it doesnt redirect

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/89041130-7c118480-d362-11ea-86de-c4e6b49de41b.png)
works fine

**Comment by kevin01523** [comment]
Ok the problem seems to be on firefox mobile android version the last fennec version

**Comment by FireMasterK** [comment]
Kiwi Browser hasn't been updated in a almost a year as the developer (arnaud42) is waiting for Brave to release their extension port for Android to resume development on kiwi.

Provide logs using Firefox's remote/usb debugging if you belive this is an issue caused by Universal Bypass.

**Comment by kevin01523** [comment]
A pc is not available so i cant do that also tried it on a freshly installed firefox fennec and universal bypass and tii.ai links still doesnt redirect or putup any warning but works on links that doesn't require crowd bypass.i guess the cause is something from commits after a10d4d6
