### ISSUE TITLE
Can't paste custom bypass on android Kiwi browser

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1418]
I can type in custom bypass panel but no copy or paste feature is available there.

**Comment by Sainan** [comment]
Go ahead and complain over at https://github.com/ajaxorg/ace

**Comment by Cyberavater** [comment]
Can _you_ open an issue there plz? Seems like I'll fail to explain it to them. (as I don't know anything about them).

**Comment by Sainan** [comment]
To be fair, I did modify the ace source code a tiny bit to make it work in an extension at all, but if you can replicate the issue over at https://ace.c9.io/ then you can just say "can't use copy-paste on Kiwi browser", you'll just have to pray they consider that an issue worth fixing, and then you can tell me to update ace. 🙃

**Comment by Cyberavater** [comment]
Yup, the paste feature works there perfectly, it only doesn't work on UB page. So, it really is UB issue.

**Comment by Sainan** [comment]
Alright, should be as easy as updating to the latest ace version, then.

**Comment by Cyberavater** [comment]
>Alright, should be as easy as updating to the latest ace version, then.

Hi, can you update ace to the latest version? It doesn't seem to be fixed yet.

**Comment by Sainan** [comment]
That would mean putting in effort. I'm sure I'll get around to it eventually.

**Comment by Sainan** [comment]
13.13.1 should have the latest version of ace, so it should work.
