### ISSUE TITLE
google.com/url

### ISSUE THREAD

**Issue by grantlison** [Sainan/Universal-Bypass#1424]
[https://www.google.com/url?q=https://imgur.com/a/L8rLD&sa=D&ust=1596625630690000&usg=AFQjCNFWq7yzCnq8v5A0aWbI_WC-yhlYQg](url) to [https://imgur.com/a/L8rLD](url)

**Comment by Sainan** [comment]
- https://chrome.google.com/webstore/detail/google-search-link-fix/cekfddagaicikmgoheekchngpadahmlf?hl=en
- https://addons.mozilla.org/en-US/firefox/addon/google-search-link-fix/
