### ISSUE TITLE
KatMoviesHD Link Bypass Custom BYPASS

### ISSUE THREAD

**Issue by hamzaharoon1314** [Sainan/Universal-Bypass#1425]
here is the famous website to download movies but they have ads link in them. and universal bypass can't completely bypass them. even if I have gone from those links.

Here is the example of Ads link:
https://liveinsure.in/?id=MGxFa3dNSmV4Rk5HL1V2OExKZXZ5K2o3OHhIM1djWDR4NXAzYTZRTHlOMGRNTExMd2FOa3I5M25YSkpPZUV4VXpzbjZlM1c2b2NwMGxEeUtkNmxJZ3h0MnkybFVPTXRWQWxLWGlVZFVNUDg9

The website from which this link was found:
https://katmoviehd.nu/

The destination of this ads link will me mostly :
https://kmhd.link/archives/XXXXXX
where XXXX is the original file link

**Comment by DineshSolanki** [comment]
these sites use infinite debugger statements to make inspecting them buggy and unresponsive, like some code mentioned here- https://x-c3ll.github.io/posts/javascript-antidebugging/

**Comment by FireMasterK** [comment]
Crowd bypass seems to be working.

**Comment by DineshSolanki** [comment]
> Crowd bypass seems to be working.

Off course there's no way cloud bypass wouldn't work.
