### ISSUE TITLE
http://www.softairbay.com/shortSAB/1vsqK12m

### ISSUE THREAD

**Issue by Harfho** [Sainan/Universal-Bypass#1426]
Can u plz bypass that website

**Comment by Cyberavater** [comment]
There is a captcha there, so having it under CB is already enough!

**Comment by Sainan** [comment]
Also looks like a faucet site, so adding `autobitco.in` to the cleanup list...

Didn't I explain somewhere in the issue template or something that faucets are integrated adwalls?
