### ISSUE TITLE
One domain link different source, one work, other keep say "Unfortunately"

### ISSUE THREAD

**Issue by tembox** [Sainan/Universal-Bypass#1432]
Thank you for your excelent bypass extension. 
but here the issues.., 

When two or more source contain a same domain link (domain link example : https://aii.sh/Wfy), domain link after one source will not work (any other https://aii.sh/????).  even after the source tab closed, or browser restart or even many time reinstalled extension/update, 

It seem domain link was bounding with certain source only/after first detection? Any other source with that domain link cannot work, and it keep say "Unfortunately, you're the first to encounter this link, but after you've waited, other Universal Bypass users will no longer have to." even after visitly frequently. 

Please fix this great extension and thank you!

**Comment by Sainan** [comment]
#1068
