### ISSUE TITLE
multiup(org|eu) not work

### ISSUE THREAD

**Issue by Dhanamerdeka** [Sainan/Universal-Bypass#1434]
https://multiup.eu/download/c3e0f674b351d0db67e6a00f86a72b20/_Ecchiku__Going_Down_on_the_Sickness.zip
https://multiup.org/download/c3e0f674b351d0db67e6a00f86a72b20/_Ecchiku__Going_Down_on_the_Sickness.zip

**Comment by FireMasterK** [comment]
Consider using an adblocker such as nano or ublock in addition to universal bypass, they already have filters for this.

**Comment by ghajini** [comment]
No they don't have any fix for this see 
https://github.com/uBlockOrigin/uAssets/issues/7897

**Comment by respecting** [comment]
I have uBO, privacy badger, and nano defender and I don't get any ads

**Comment by Dhanamerdeka** [comment]
no ads... but if you click download button you open the ads sites first

**Comment by Sainan** [comment]
Watch out with Nano Defender; that shit was bought by some org. that now put tracking in it. But in regards to this, there is some sort of bypass for multiup already in Universal Bypass, but it seems to me this is more a thing that an adblocker would take care of.

**Comment by ghajini** [comment]
Bypass by UB doesn't work fyi

**Comment by sayapemula** [comment]
Works fine for me, but for uBlockOrigin users with default settings this bypass will not work because of this filter `multiup.*##+js(nostif, .submit)`

**Comment by Sainan** [comment]
Can confirm; bypass works with adblock disabled. Would just remove the bypass because it seems out-of-scope for UB, but whatever, it's here, it works (sorta). In any case, this is an issue with uBlock Origin.

**Comment by ghajini** [comment]
https://github.com/Sainan/Universal-Bypass/issues/1434#issuecomment-725913882
@okiehsch would you help?

**Comment by uBlock-user** [comment]
@ghajini If I remove `multiup.*##+js(nostif, .submit)` from the filter list what happens to users who don't use Universal Bypass ?

**Comment by ghajini** [comment]
this will https://github.com/uBlockOrigin/uAssets/issues/6627#issuecomment-559373561

**Comment by uBlock-user** [comment]
try --

```
multiup.*#@#+js(nostif, .submit)
multiup.*##+js(nostif, .submit, 2000)
```

**Comment by uBlock-user** [comment]
you can try --


```
multiup.*#@#+js(nostif, .submit)
multiup.*##+js(nostif, \$\(\"form\"\)\.submit, 2000)
```

**Comment by ghajini** [comment]
@uBlock-user 
Redirection to ads happened here if I use above filter

`https://multiup.org/download/e1434d6c1c62d084ee2c53cc4462759a/CHNKSKMHD%20%282019%29%20www.SkymoviesHD.vin%20720p%20HEVC%20UnCut%20HDRip%20Dual%20Audio%20x265%20ESUb.mkv`
