### ISSUE TITLE
How to remove your extension

### ISSUE THREAD

**Issue by Vik4o0** [Sainan/Universal-Bypass#1437]
I'm having lots of problems with your extension like cannot pass in the site cuz i dont see the popup window where i must accept cookies and etc. Can you tell me how to remove it?

**Comment by FireMasterK** [comment]
chrome://extensions/ or about:addons

and wrong place to ask this question, maybe search "How to remove an extension in my browser"

**Comment by Sainan** [comment]
If you're having issues with a particular website, you can also just provide an example link so the issue can be fixed. 🙃 

You can also toggle Universal Bypass in the options: https://universal-bypass.org/options#option-enabled

**Comment by Vik4o0** [comment]
Thanks, but the problem is that i don't have it listed in my extensions

**Comment by Sainan** [comment]
Then you probably don't have the extension? Don't let whichever website you're having issues with know, and instead just don't use them. ¯\_(ツ)_/¯
