### ISSUE TITLE
linegee.net from pahe.ph

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1441]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

https://pahe.ph/a-street-cat-named-bob-2016-bluray-480p-720p/
https://intercelestial.com/?id=eW5WTXFIaDVYT0ViR1B6WTc4L2lvSndQUWZSVmpIVlZlQ1p2ejlyTlR6eC85T1pqVHJHWldGNWwrN084bDJNNGs5V2hhYzNHWTlpOTN0Y3ZFYU9SRFE9PQ==#bypassClipboard=astreetcatnamedbob2016bluray480p720p720px264800mbrct
https://linegee.net/2jbp6 ==> doesn't work to destination site

**Comment by Sainan** [comment]
Crowd bypass seems to be working perfectly.

**Comment by FireMasterK** [comment]
I think he meant that when you go to https://linegee.net/M4Fjn , there's a continue button which can be skipped.

**Comment by 3xploiton3** [comment]
> 
> 
> I think he meant that when you go to https://linegee.net/M4Fjn , there's a continue button which can be skipped.

thx, that was i mean
