### ISSUE TITLE
Linkvertise has brought back all of the annoying steps

### ISSUE THREAD

**Issue by ZERO8914** [Sainan/Universal-Bypass#1445]
Linkvertise has brought all of their annoying steps, including adding lookbox which has killed over 16 of my hard drives, leading me to believe it's malicious
![image](https://user-images.githubusercontent.com/69772871/90345732-36ef8280-dff1-11ea-98cb-fb50d6f6f89a.png)

**Comment by llacb47** [comment]
> which has killed over 16 of my hard drives

surely you're joking lol
