### ISSUE TITLE
blocked by sh.st 

### ISSUE THREAD

**Issue by gahara31** [Sainan/Universal-Bypass#1446]
the add on need to be turned off so I can access sh.st link.

**Comment by Sainan** [comment]
Could you provide an example link?

**Comment by FaolanX** [comment]
> Could you provide an example link?

Any link, take for example [this link](http://sh.st/wVGYZ) you gave in the [Example Links section](https://universal-bypass.org/example-links). It brings up [this Cloudflare error](https://prnt.sc/u15ttv). Tampermonkey scripts are still working to bypass it somehow.
