### ISSUE TITLE
indihome bypass broken?

### ISSUE THREAD

**Issue by Uranite** [Sainan/Universal-Bypass#1447]
It doesnt redirect to the website i want to visit, its redirecting me to indihome website instead

**Comment by Sainan** [comment]
As stated in #1326, I don't have indihome and adding a bypass for it is a terrible idea.

**Comment by codergautam** [comment]
Why

**Comment by FireMasterK** [comment]
https://www.eff.org/https-everywhere

I believe this should prevent you from being redirected as long as there is a rule for the site.

**Comment by Uranite** [comment]
seems like its working again for some reason, its now redirecting me to the website i want to visit
