### ISSUE TITLE
[Enhancement] Firefox's container support.

### ISSUE THREAD

**Issue by Bulogan** [Sainan/Universal-Bypass#1449]
When bypassing a website from a specific container, the destination is opened in the default container.

**Comment by Sainan** [comment]
u wot m8?

**Comment by Bulogan** [comment]
I'm talking about thing [container](https://support.mozilla.org/en-US/kb/containers). UB doesn't respect the tab where the bypass-able link comes from. 

screenshot!
![image](https://user-images.githubusercontent.com/69257763/90478709-227dc800-e160-11ea-9215-d27c2aea8bae.png)
the you may not have to wait tab is in a specific container, then the opened tab/ bypassed tab is in normal, default tab.

**Comment by Sainan** [comment]
I see, so it's like incognito mode. Well, if Mozilla were competent enough to accept `"incognito": "split"` in the manifest, that shouldn't be a problem.

**Comment by Sainan** [comment]
This whole containers thing seems like another half-baked idea by Mozilla, but as there's no real extension API for it that I can see, it seems like this _might_ be fixed if https://bugzilla.mozilla.org/show_bug.cgi?id=1380812 is fixed.
