### ISSUE TITLE
ouo.io take longtime to redirect

### ISSUE THREAD

**Issue by exodius48** [Sainan/Universal-Bypass#1453]
Before you report a broken bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE
I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.

If that is not the case, please **provide an example link.** We need to be able to see what has gone wrong in order to fix it.

After Universal Bypass Update Version 13.13.0 · Bypass definitions 9eae606 it take longtime to redirect ouo.io to exact link. Slowdown the browser too.
Example link: `https://ouo.io/1vU9tG` 
Souce link: `https://hikarinoakariost.info/tomorrow-x-together-eien-ni-hikare-single-black-clover-op12/`
`https://hikarinoakariost.info/`

Video proof: `https://streamable.com/854nwc`

Browser: FF 79.0 X64

**Comment by Sainan** [comment]
Looks like ouo.io is just slow.
