### ISSUE TITLE
https://expertvn.com

### ISSUE THREAD

**Issue by nguyenhai97** [Sainan/Universal-Bypass#1458]
Example link: https://expertvn.com/ngan-hang-trung-uong-phap-se-thu-nghiem-tien-ky-thuat-so-trong-nam-2020.html#bwutP
Link before Example: http://megaurl.in/bwutP
They now using re-captcha to protect destination url

**Comment by nguyenhai97** [comment]
I will close this now, as far as I investigate the shortlink services check captcha on server and only when captcha verified the api start return destination url so there no way to gather destination url locally

**Comment by FireMasterK** [comment]
Crowd bypass seems to working for that url anyways.

**Comment by nguyenhai97** [comment]
I'm that crowd :)
