### ISSUE TITLE
bypass https://acortaz.com/

### ISSUE THREAD

**Issue by dease12** [Sainan/Universal-Bypass#1460]
bypass https://acortaz.com/ 
new annoyance on download websites

**Comment by FireMasterK** [comment]
I got an example link from [here](https://www.gamesfull.org/juegos/the-sims-4-digital-deluxe-edition-elamigos/), the website seems to be broken now.

**Comment by Sainan** [comment]
Doesn't seem broken, "Descargar" just leads to some link on acortaz.com where you need to press "Enlace" to continue to the destination, definitely not the most exciting thing to bypass.
