### ISSUE TITLE
h-gen.xyz

### ISSUE THREAD

**Issue by MDMCK10** [Sainan/Universal-Bypass#1463]
![image](https://user-images.githubusercontent.com/21245760/90983514-15514680-e56f-11ea-8a66-cfea5730a982.png)

**Comment by FireMasterK** [comment]
Related to linkvertise.

**Comment by FaolanX** [comment]
Disable Universal Bypass and use FireMasterK's userscript

**Comment by MDMCK10** [comment]
> 
> 
> Disable Universal Bypass and use FireMasterK's userscript to bypass Linkvertise

ah alright, is there a way to disable UB just for the site instead of having to disable it globally every time i want to use the site?

**Comment by FireMasterK** [comment]
There's a simple way: use a private tab
