### ISSUE TITLE
pastelinku.net

### ISSUE THREAD

**Issue by shintaro911** [Sainan/Universal-Bypass#1466]
https://pastelinku.net/?id=dDBTalYzbGJVRm9QQU41V1k1dE1oeDdVQ3RNV080RmtBdmhpQnhhY2lBNVZKTFUrUjFYL3RsdUZlRWxGaWRyNElzQUo1ZzhKRHpRcmZtOW96dWpCVmFTeUdvVUNTTzROemZYMVNKM094QTJkYzhKRXFLVDdGVjJzWlQyOTExSUQxOUJ2Q1dUeFhZMzc0NDVzakREdmp3PT0=

**Comment by Lya-chan** [comment]
The site seems to dead, cant pass the link with/without Universal Bypass
