### ISSUE TITLE
forocoches.com

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1469]
https://www.forocoches.com/link.php?url=https%3A%2F%2Fwww.pccomponentes.com%2Fmsi-modern-14-a10ras-1049xes-intel-core-i7-10510u-32gb-1tb-ssd-mx330-14

**Comment by DineshSolanki** [comment]
what's here to bypass? this seems just simple redirection.

**Comment by FireMasterK** [comment]
A tracker bypass.

**Comment by DineshSolanki** [comment]
> 
> 
> A tracker bypass.

oh, okay, I have UBlock installed so maybe that's the reason I didn't saw anything.
