### ISSUE TITLE
Redirecting me to a random website

### ISSUE THREAD

**Issue by SrMilton** [Sainan/Universal-Bypass#1477]
I was googling when o got redirected to "cutecursors.com". I've just typed "Streamer_MaxItem samp" in my URL Bar to search than i got redirected to this. Idk how to send a log but i think it's interesting report it.

![image](https://user-images.githubusercontent.com/35127424/91640634-693baf80-e9f5-11ea-921d-b9314bb1f515.png)

**Comment by Sainan** [comment]
You might just have some adware extension that is fucking with you, UB certainly isn't that adware, but the adware might be triggering it.

**Comment by SrMilton** [comment]
Rude af but probably, that was the first time i saw this. Btw I'm just using nano blocker, nano defenser and Steam Invetory Helper

**Comment by Sainan** [comment]
> Steam Inventory Helper
Triggers like 3 red flags in my head. Is your Steam account hacked yet?

**Comment by SrMilton** [comment]
Wtf man, SIH was like the most famous plugin to CSGO Trades on Steam back in 2015
