### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1481]
Regarding Mozilla's latest brain fart:
https://blog.mozilla.org/addons/2020/02/11/faq-for-extension-support-in-new-firefox-for-android/
![image](https://user-images.githubusercontent.com/63328889/91777386-f5192b80-ebef-11ea-9a77-223c60d4309d.png)

**Comment by FireMasterK** [comment]
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

This might be useful for nightly users.

**Comment by Sainan** [comment]
Some users have _already_ reported issues with this (#1545), but I suppose it's a start... if only they already had a fully-functioning extension system. I'm sure if they would have such a system, they wouldn't just abolish it in an "update" for no reason.
