### ISSUE TITLE
linegee.net (from pahe.ph)

### ISSUE THREAD

**Issue by lambatgarry** [Sainan/Universal-Bypass#1500]
https://pahe.ph/?38495eca49=WSt5YlEwazFINEl5aCt4SERWQXhUNS9HV29zVEVoUU91OU95Ly9vNFJPSlpCa0xicVk3VllLMndueVl3b0ZvUzlzNFFFeDlsVS9HMzhQVjBmbmJ5OFE9PQ==
https://linegee.net/flrGg
https://www.google.com/search?q=How%20to%20Uninstall%20Universal%20Bypass
bypass detected, from linegee redirect to google

**Comment by FireMasterK** [comment]
Relevant link: https://linegee.net/flrGg
Relevant Code:
![image](https://user-images.githubusercontent.com/20838718/92330332-ace48800-f08b-11ea-9923-c23007761c9f.png)

**Comment by FireMasterK** [comment]
Crowd bypass doesn't seem to work anymore too.

**Comment by sayapemula01** [comment]
Seems bypass not going to work anymore

**Comment by sayapemula01** [comment]
Its annoying too

**Comment by FireMasterK** [comment]
https://stackoverflow.com/a/53488689 I think this might help
Another Implementation: https://github.com/Sentero-esp12/IsTrusted-event-Debugger-API

Firefox users can probably complain at https://bugzilla.mozilla.org/show_bug.cgi?id=1348213

**Comment by sayapemula01** [comment]
I think its different, since it read only property

**Comment by Sainan** [comment]
These people are probably reading this, so I'll say thank you for giving me something that actually excites me.

**Comment by sayapemula01** [comment]
The issue closed?

**Comment by Sainan** [comment]
Indeed, update your Universal Bypass.

**Comment by sayapemula01** [comment]
It doesn't work
