### ISSUE TITLE
Pahe.ph

### ISSUE THREAD

**Issue by sayapemula01** [Sainan/Universal-Bypass#1502]
Not bypassed
https://pahe.ph/?38495eca49=WSt5YlEwazFINEl5aCt4SERWQXhUNS9HV29zVEVoUU91OU95Ly9vNFJPSlpCa0xicVk3VllLMndueVl3b0ZvUzlzNFFFeDlsVS9HMzhQVjBmbmJ5OFE9PQ==
https://linegee.net/flrGg

**Comment by Sainan** [comment]
This is just pathetic now.

**Comment by FireMasterK** [comment]
They've made another patch that takes you to the fake link in the comment
![image](https://user-images.githubusercontent.com/20838718/92333913-b62f1e00-f0a6-11ea-946f-27078db35e45.png)
