### ISSUE TITLE
Compatibility with Waterfox Classic?

### ISSUE THREAD

**Issue by PlaceboPRS** [Sainan/Universal-Bypass#1506]
Hi,

I'm using Waterfox Classic 2020.08.1 (64bit), Universal Bypass works but the settings don't stick when I change them, is it an issue with the browser or is there a fix please?

**Comment by Sainan** [comment]
You'd need to give it an extension ID in the `manifest.json`, like this:
```JSON
"browser_specific_settings": {
    "gecko": {
      "id": "addon@example.com",
      "strict_min_version": "42.0"
    }
  }
```

**Comment by PlaceboPRS** [comment]
Apologies for delay in getting back to you, thanks for the reply, I tried to add that and I'm guessing it's beyond my capabilities as Waterfox now says the addon is corrupt :( (used winrar to open the xpi and extract manifest.json to edit).

**Comment by Sainan** [comment]
You might need to add a comma to the previous statement, JSON is a very sensitive format. You can also check against an online linter (such as https://jsonlint.com/) to see if your JSON is valid.

**Comment by PlaceboPRS** [comment]
Thanks I got the modified xpi accepted now, but for some reason the settings still aren't sticking when I change them :(

I make the changes like so: 

![bypass](https://user-images.githubusercontent.com/23120453/103454498-1e081500-4ce5-11eb-9057-56fc74692ac4.jpg)

But as soon as I restart my browser and visit another link everything is reset to default:

![bypass2](https://user-images.githubusercontent.com/23120453/103454506-32e4a880-4ce5-11eb-8ec9-0665b3fb88eb.jpg)

**Comment by Sainan** [comment]
There must be an error message somewhere in the relevant consoles for extension debugging.
