### ISSUE TITLE
linkvertise

### ISSUE THREAD

**Issue by codergautam** [Sainan/Universal-Bypass#1523]
```js
domainBypass(/linkvertise\.(com|net)|link-to\.net/,()=>{

 fetch("https://linkunshortener.herokuapp.com/api?url="+window.location).then(r=>r.json()).then(json=>{
     if(json.success) {
         safelyNavigate(json.bypassedlink)
     } else {
         alert("Bypass failed: "+json.errormsg)
     }
 })

})
```

**Comment by bossotron13** [comment]
Works perfectly thank you!

**Comment by GreenXpqser** [comment]
domainBypass(/linkvertise\.(com|net)|link-to\.net/,()=>{

to

domainBypass(/linkvertise\.(com|net|download)|link-to\.net/,()=>{

**Comment by rcgjogamine** [comment]
stop working im hate this stupid linkvertise so much

**Comment by Sainan** [comment]
I've blocked @codergautam for repeatedly creating new issues with his shitty code. Take this conversation to #1323.
