### ISSUE TITLE
Youtube Redirect links

### ISSUE THREAD

**Issue by Mhowser** [Sainan/Universal-Bypass#1526]
Youtube redirects users to this when clicking on a link in a video's description:
![image](https://user-images.githubusercontent.com/24195572/93560701-9e258d00-f937-11ea-8902-74869702354b.png)
Here is an example: https://www.youtube.com/watch?v=ACIt2aTuCac

Go in to the description and try to go to his Twitter: 
![image](https://user-images.githubusercontent.com/24195572/93560853-ed6bbd80-f937-11ea-9086-c8d64dd0c2a7.png)
Clicking on the twitter URL goes to https://www.youtube.com/redirect?event=video_description&v=ACIt2aTuCac&q=https%3A%2F%2Ftwitter.com%2Fddofinternet instead. I think this wastes our time. And even if this is a soft security measure, I'm fairly certain users who choose to install Universal-Bypass are smarter than most and will not need this kind of weak protection.

**Comment by Sainan** [comment]
Unfortunately this will need a proper extension update.
