### ISSUE TITLE
Bit.do

### ISSUE THREAD

**Issue by Mhowser** [Sainan/Universal-Bypass#1527]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

Example link: http://bit.do/fJzuE

Edit: I made that shorten URL link back to this issue as an example, so do not be confused

**Comment by Sainan** [comment]
This happens immediately when I click on the bit.do link, so I don't see what your issue is.
![image](https://user-images.githubusercontent.com/63328889/93626492-c8cd1f80-f9e3-11ea-8751-d062f0f0a2e0.png)
