### ISSUE TITLE
[Unknown-Bug] shorte.be

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1533]
Eg link: https://shorte.be/LP2CH?$=1808

This link is dead on PC, but it UB can bypass it on android. Maybe Spoofing to be android will help bypass it on PC too.

**Comment by Sainan** [comment]
Seems to be working for me on PC with Chrome.

**Comment by FireMasterK** [comment]
Seems to be working fine on Brave too.

**Comment by Cyberavater** [comment]
This is what I'm getting even without any extensions (on chrome);

![Screenshot (7)](https://user-images.githubusercontent.com/32187927/94104589-31d7eb80-fe59-11ea-9165-a1a483df0768.png)

But it is working on incognito mode, So it isn't really Browser agent issue. Any idea what's wrong? (I already tried disabling all extensions).

**Comment by FireMasterK** [comment]
Clear your cookies and maybe it might work, this is a server issue.

**Comment by Cyberavater** [comment]
No cookies are there, to begin with, but this issue is unrelated to UB so closing it.

**Comment by Cyberavater** [comment]
But it would be nice to figure out what is wrong. Any suggestion is appreciated.

**Comment by FireMasterK** [comment]
Not sure what could be wrong, you could checkout the network tab in the devtools to see if there are any abnormalities which cause the server to close the connection immediately (cookies, user agent, other headers, etc).

**Comment by Cyberavater** [comment]
Clearing Browser cache fixed it.
