### ISSUE TITLE
Intermediary pages skip

### ISSUE THREAD

**Issue by UltraBlackLinux** [Sainan/Universal-Bypass#1538]
Hey there,
It would be cool if you added the possibility to skip intermediary pages, like youtube uses in links: It makes the pages load faster and prevents youtube from knowing where your account went.
This plugin here does this, but its kinda buggy, since the blacklist doesnt work: https://github.com/sblask/webextension-skip-redirect
Pages, e.g. Google drive break when skipping intermediary pages, since the download links link into itself, that leads to the site being unloaded. (My Blacklist: docs.google.com/* | *.googleusercontent.com)
Thanks!

**Comment by Sainan** [comment]
Although I'm not a huge fon of it, intermediary pages are generally accepted into the bypass definitions. The youtube out redirects will be skipped in the next release; it's already in master.
