### ISSUE TITLE
https://dropgalaxy.com/

### ISSUE THREAD

**Issue by rushi4tg** [Sainan/Universal-Bypass#1540]
https://dropgalaxy.com/

Example:-
𝚆̶𝚛̶𝚘̶𝚗̶𝚐̶ ̶𝙻̶𝚒̶𝚗̶𝚔̶

**Comment by Sainan** [comment]
Where did you get that link from?

**Comment by rushi4tg** [comment]
> Where did you get that link from?

https://www.google.com/search?q=https%3A%2F%2Fdropgalaxy.com%2F+site%3Aa2zapk.com

It appeared in the search results,i didn't check it was a nsfw app😅

Here is another link, https://dropgalaxy.in/iu2cvy5135uw

**Comment by Uranite** [comment]
> Where did you get that link from?

not the same exact link but link leads to dropgalaxy.com
https://dropgalaxy.in/syvl4hghldoj

**Comment by respecting** [comment]
Captcha verification.

**Comment by Sainan** [comment]
Also, it's some sort of download site. Plus, it's broken.
