### ISSUE TITLE
block.fiverr.com

### ISSUE THREAD

**Issue by FireMasterK** [Sainan/Universal-Bypass#1543]
Example URL: https://block.fiverr.com/index.html?url=aHR0cDovL3d3dy5maXZlcnIuY29tL3NlbGxlcl9vbmJvYXJkaW5nL3BlcnNvbmFsX2luZm8/&uuid=77f8f330-01be-11eb-b54b-6d987b7c89ed&vid=202fa721-01be-11eb-8966-4be763a15371

The URL seems to be just base64 encoded.

**Comment by Sainan** [comment]
Sure thing, next I'll add a cloudflare bot check bypass.

**Comment by FireMasterK** [comment]
¯\_(ツ)_/¯ 
![image](https://user-images.githubusercontent.com/20838718/94641486-0ba1c800-02ff-11eb-8e6f-e38efaac1cae.png)
It's not a Cloudflare bot check lol.

**Comment by Sainan** [comment]
I'm not saying it's a Cloudflare bot check, but it is a bot check. The joke is that after this, the next thing will be the Cloudflare bot check.
