### ISSUE TITLE
Auto remove

### ISSUE THREAD

**Issue by HolyDemonz** [Sainan/Universal-Bypass#1546]
Universal bypass keeps getting deleted from extensions.

**Comment by Sainan** [comment]
#1387

**Comment by HolyDemonz** [comment]
Installed from extracted folder and this happened again no fix.

**Comment by Sainan** [comment]
The extracted folder is permanent and not in your temp, right? I literally use Universal Bypass in dev mode _all the time_ and I never have it magically disappear. Did you maybe get a popup asking you to disable developer mode extensions and you just blindly obliged? All the answers should be in #1387.
