### ISSUE TITLE
why cant you bypass Linkvertise?

### ISSUE THREAD

**Issue by ll821301** [Sainan/Universal-Bypass#1555]
why cant u bypass Linkvertise? its one of the most popular link shortens, why cant u bypass it?

I'm using a tampermonkey script to bypass linkvertise. Why does it say when i go to linkvertise "we cannot bypass this site, but have negotiated a removal of their most annoying steps"?

**Comment by ll821301** [comment]
@Sainan

**Comment by Sainan** [comment]
#1323
