### ISSUE TITLE
Mirrorace isn't working

### ISSUE THREAD

**Issue by kargupta28** [Sainan/Universal-Bypass#1560]
I was just testing it out and I was using the links on the "Examples" page.

When I load the link the website goes on a infinite loop. I removed the extension and then I was able to proceed. Is Cloudflare causing a problem?

Link: https://mirrorace.com/m/1zf2c

**Comment by Cyberavater** [comment]
Working fine here, you should try again after clearing the browser cache.

**Comment by Sainan** [comment]
Seems to work for me, too.
