### ISSUE TITLE
a new bypass pls for this site

### ISSUE THREAD

**Issue by memerdz19** [Sainan/Universal-Bypass#1561]
the site is "https://www.blizzboygames.net/" and the bypass is for "fc-lc.com", when i use the first hours is working but when i restart the pc the bypass didnt work, only in this page, so if you can help with that I would appreciate it, ty

**Comment by Sainan** [comment]
Do you happen to be on Firefox?

**Comment by Sainan** [comment]
I'm just gonna assume you're on Firefox and say: Wait for the 13.15.0 update. Feel free to respond if I'm wrong or it still doesn't work.

**Comment by memerdz19** [comment]
i try in chrome, edge, opera gx and firefox and its the same, the site dont
redirect

**Comment by Sainan** [comment]
I'm not sure if you've got the _latest_ version because I've basically released it just now, but could you please provide a more specific example link?

**Comment by memerdz19** [comment]
I think the link was wrong on my part but it is that site that I mentioned
earlier

**Comment by Sainan** [comment]
That's a big site, but the fc-lc.com bypass seems to work as intended.

**Comment by memerdz19** [comment]
I try in chrome, firefox, edge and i have the same problem, i think that i
change the config or something, it was working before updating a processor
driver, do you think that has affected?

**Comment by Sainan** [comment]
Don't think so, you just need to make sure that you have UB 13.15.0 with the latest definitions or 13.15.0.1 on Firefox.
