### ISSUE TITLE
Can we avoid bypassing certain links?

### ISSUE THREAD

**Issue by Lazza** [Sainan/Universal-Bypass#1564]
Recently, I realized I could not read some articles linked on Twitter due to the extension being active.

See for instance:

https://twitter.com/FinancialTimes/status/1314302067163439111

It seems Universal Bypass is hiding the referer or something like that, hence the FT does not recognize I am coming from Twitter and it decides to activate a paywall.

Is it possible to disable Universal Bypass on certain domains?

Thank you.

**Comment by Sainan** [comment]
You can disable the tracker bypass. Although, `ft.com` is blocked by my DNS for "notserious" so that's that.

**Comment by Lazza** [comment]
Thank you for your reply. My question was a bit different, though... I was wondering if a user can have a whitelist of domains not affected by the extension. I guess the answer is no then. 🙂 

I am not sure about your last sentence, FT is quite a large newspaper dating back to 1888 and now owned by Nikkei, "not serious" doesn't seem to be a fitting description. 😅 Anyhow, my concern was the `t.co` domain and the FT tweet was an example.

I will follow your suggestion and disable the tracker bypass.

**Comment by hacker1024** [comment]
I'd also like this option. The Twitter bypass also blocks access to many Medium articles.

**Comment by Sainan** [comment]
Provide an example?

**Comment by FireMasterK** [comment]
The other alternative is to spoof the referrer the website wants.

**Comment by Lazza** [comment]
@FireMasterK in the original example I posted, the referer works fine when the extension is off or the "tracker bypass" is disabled.

**Comment by hacker1024** [comment]
> Provide an example?

1. Find a paid medium article (such as [this one](https://medium.com/@azamsharp/understanding-global-state-in-flutter-using-redux-2017b7646574))
2. DM it to yourself on Twitter
3. Open it with Universal Bypass tracker bypassing enabled
4. Note that it's still behind a paywall
5. Disable the tracker bypassing
6. Open the link again
7. Note that the article can now be accessed

**Comment by Sainan** [comment]
Works perfectly fine on master.
