### ISSUE TITLE
Need exe.io bypass

### ISSUE THREAD

**Issue by RoninReilly** [Sainan/Universal-Bypass#1565]

**Comment by Sainan** [comment]
Example link?

**Comment by Cyberavater** [comment]
Eg link: http://exe.io/2JZMEq

Bypasses successfully using CB.

**Comment by Cyberavater** [comment]
But maybe he is requesting to make it default bypass, as there doesn't seem to be any captcha.

**Comment by FireMasterK** [comment]
There is a captcha...
![image](https://user-images.githubusercontent.com/20838718/95818509-a5c33080-0d41-11eb-906e-e2d5f5e4b326.png)
