### ISSUE TITLE
https://cutdl.xyz 

### ISSUE THREAD

**Issue by Dorathekiller97** [Sainan/Universal-Bypass#1568]
This website does not work with Universal Bypass. Please fix this issue. I believe this is a new site. :)

This hangs at "3 seconds" and "Please wait" and nothing happens when adblocker is enabled.

**Comment by FireMasterK** [comment]
Issue not related to Universal Bypass, if your adblocker is being detected, get Nano Adblocker + Nano Defender as it evades adblocker detection.

**Comment by Sainan** [comment]
And without an example link, I can't look at the issue.

**Comment by sjkim04** [comment]
https://cutdl.xyz/QOaiWFB2
Here is one.
