### ISSUE TITLE
https://gateway.svk.jp/

### ISSUE THREAD

**Issue by j-moriarti** [Sainan/Universal-Bypass#1574]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

https://gateway.svk.jp/?c=tMn6bu%2FuJp932bbIKm6dXkld0kOUaF4gGewcho6EQZKz5addfP4zOap32SiFjWXJn3ngZbPudVLaycilB4PGCIzcOeKrIbGPsHrS1aWxTP8%3D

**Comment by Sainan** [comment]
What's there to be bypassed?

**Comment by j-moriarti** [comment]
I think it is a redirector service which replaces destination links with their encoded (trackable?) url. the destination link of the above example goes to:

(remove the spaces)
https :// github.com / IngoZenz / personaldnsfilter / pull / 112

I'm curious if it can be bypassed to directly jump to dest url :thinking:

**Comment by Sainan** [comment]
So, you're suggesting a tracker bypass?

**Comment by j-moriarti** [comment]
somehow yes. but I'm not sure if it is exactly a tracker! I can give some other example links if needed. Or you may consider closing the issue if it can't be bypassed.

**Comment by Sainan** [comment]
I don't think this remotely matches what Universal Bypass is for, if it really is just a redirect.
