### ISSUE TITLE
ask how to disable script to some website

### ISSUE THREAD

**Issue by Dhanamerdeka** [Sainan/Universal-Bypass#1576]
Hello admin...
can you give me a ways to disable some website to be skipped on my adsbypasser?

like... i have nesiaku.my.id that i don't want to skipped directly... how can i disable the plugin to disable to that website?
or adsbypasser have some form to input exception sites?

**Comment by Sainan** [comment]
The only reason I see why you wouldn't want it to be skipped, is because they detect that it was skipped, in which case that's an issue to be addressed.

**Comment by Dhanamerdeka** [comment]
what?
i just asking how to disable script run in some website that i want to not be skipped automatically....
'-' what kind of answer this is....
