### ISSUE TITLE
Redirecting does not allow opening the Tecmundo website?

### ISSUE THREAD

**Issue by serial02** [Sainan/Universal-Bypass#1580]
Hello Universal Bypass Team

When clicking on the Twitter page link, the reduced URL does not open the Tecmundo page website ( https://www.tecmundo.com.br/produto/205447-10-celulares-populares-comparador-tecmundo.htm ), as seen in this GIF image below.

The news link on the page is this:
( https://www.tecmundo.com.br/produto/177382-5-dicas-montar-escritorio-profissional-casa.htm )

![Screen Capture_Opera_20201021160258](https://user-images.githubusercontent.com/32621790/96771288-d47f7d80-13b7-11eb-9475-ee76182a1343.gif)

**Comment by Sainan** [comment]
This will be fixed with the next extension update. Alternatively, you could use the current master. Not sure what's up with all these shitty companies not even accepting HTTPS.

**Comment by serial02** [comment]
> This will be fixed with the next extension update. Alternatively, you could use the current master. Not sure what's up with all these shitty companies not even accepting HTTPS.

Thanks !
