### ISSUE TITLE
universal bypass is blocked

### ISSUE THREAD

**Issue by slain576** [Sainan/Universal-Bypass#1581]
if you try to bypass this with universal bypass it blocks you with cloudflare

http://gestyy.com/erpuUs

**Comment by slain576** [comment]
I install this extension it bypass it
https://chrome.google.com/webstore/detail/skip-shortest-ads/bhgkdnnlhmefhnkfilcaaibapeepkfok

**Comment by Sainan** [comment]
This will be fixed in the next extension update. Alternatively, you could use the current master.

**Comment by isaactzab** [comment]
This issue still in June 2022, in master branch using incognito mode. Is there a workaround for this?
