### ISSUE TITLE
fc-lc.com

### ISSUE THREAD

**Issue by Sainan** [Sainan/Universal-Bypass#1583]
https://fc-lc.com/ozU3YeHX

Still using the `?a=` at the adlinkfly site but with a different "encoding."

**Comment by sayapemula** [comment]
```ruby
const param=new URLSearchParams(location.search)
if(param.has("a"))
{
	crowdPath(atob(param.get("a").substr(5)))
}
```

**Comment by Sainan** [comment]
Now I feel silly for giving up after I noticed the length correlation
