### ISSUE TITLE
Universal Bypass gets removed from chrome every time I turn off my computer

### ISSUE THREAD

**Issue by Jayinem** [Sainan/Universal-Bypass#1585]
I have been using this for over a year and this is the only computer this happens on the other one stays but my main one every time I turn off the computer I turn it back on the extension is removed from Chrome and I have to reinstall it.

**Comment by rushi4tg** [comment]
https://github.com/Sainan/Universal-Bypass/issues/1387

**Comment by Sainan** [comment]
I'm still unsure why this happens for some people, but I've updated the instructions to tell people to use the "Load unpacked" button, but I don't know if that's any better than dragging and dropping.
