### ISSUE TITLE
website is not bypassed

### ISSUE THREAD

**Issue by slain576** [Sainan/Universal-Bypass#1586]
this website isn't bypassed

https://goodssh.com/server/choice-your-server-vultr-2

**Comment by Sainan** [comment]
What?

**Comment by slain576** [comment]
it's a link shortener

**Comment by slain576** [comment]
it's supposed take you to this

https://www.mediafire.com/file/u5czr3lr5jn7rms/IAM%2527s_Vehicle_v2.3_%255Bbeh%255D.mcpack/file

**Comment by Sainan** [comment]
You do realize the link you've sent?

**Comment by slain576** [comment]
yeah you can wait 15 seconds scroll to the bottom
then you can the small blue button
and one someone is not going to get through that link,because they don't know how.

**Comment by slain576** [comment]
![Capture34](https://user-images.githubusercontent.com/69993694/97127631-627ca080-16f7-11eb-9070-449b3d1c5ca6.PNG)

**Comment by Sainan** [comment]
And you can get this by clicking on the example link that you have provided?

**Comment by slain576** [comment]
yes

**Comment by Sainan** [comment]
Well, I don't see it. Please provide a proper example link and steps to get the desired result.
