### ISSUE TITLE
TMEARN.COM

### ISSUE THREAD

**Issue by ilaicraftYT** [Sainan/Universal-Bypass#1590]
Universal-Bypass does not detect the **TMEARN.COM** site

I tried to reload the page, and got no results.

For example: _https://tmearn.com/CoreHCF_
which was the one who tried to access, bypass I did not detect and did nothing about it.

I am looking forward to your response. Thank you!

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
