### ISSUE TITLE
nyantaidulu.com

### ISSUE THREAD

**Issue by Recehan-Slayer** [Sainan/Universal-Bypass#1594]
https://nyantaidulu.com/linknya/?url=aHR0cHM6Ly9kcml2ZS5nb29nbGUuY29tL2ZpbGUvZC8xMHJoaVFSWVAweDNXa21VU3cyNS14U01fUUV2UFNmNXEvdmlldz91c3A9c2hhcmluZw==

`https://batchkun.com/download-nanatsu-no-taizai-season-3-batch/`

**Comment by respecting** [comment]
1594, param_url_base64, 1595 & 1596, param_data_base64
you can probably make a pull request

**Comment by Sainan** [comment]
I think he just wants to annoy me :^)
