### ISSUE TITLE
forex-lab.xyz

### ISSUE THREAD

**Issue by stuffi3000** [Sainan/Universal-Bypass#1601]
https://forex-lab.xyz/2020/06/20/trend-following-strategy-using-pullbacks/

**Comment by FireMasterK** [comment]
This is just a blog... You need to provide the previous URL.

**Comment by stuffi3000** [comment]
> 
> 
> This is just a blog... You need to provide the previous URL.

There's a timer popping up on the top when I click on it though

**Comment by stuffi3000** [comment]
> 
> 
> This is just a blog... You need to provide the previous URL.

I'll provide the previous URL when I can select it again tomorrow.

**Comment by FireMasterK** [comment]
You'll see that only when you visit it from a specific URL as the timer pops up only based on a specific referrer.

**Comment by Sainan** [comment]
> when I can select it again tomorrow
If this is a faucet, you can close this issue.

**Comment by stuffi3000** [comment]
@Sainan
Oh, are ads coming from faucets not allowed? Sorry, I didn't know that. I'll close this one and the first issue I created.
Sorry again ^^'

**Comment by Sainan** [comment]
These "link shorteners" used on faucets are just integrated ad walls.

**Comment by stuffi3000** [comment]
@Sainan 
I noticed that even though it leads to an ad wall, the link leading to it is this : https://kekolink.com/nNwB
This does look like a shortener though, doesn't it?

**Comment by Sainan** [comment]
It looks like a link shortener. Heck, it might actually be a link shortener. But that's just them being too lazy to integrate a proper paywall, so they simply bought a link shortener template to show you ads. Either way, it's an integrated ad wall.

**Comment by FireMasterK** [comment]
You can just rewrite the URL to https://kekolink.com/nNwB?r=/nNwB, but the initial link is a 302.

**Comment by FireMasterK** [comment]
I can definitely tell it's a real link shortener: https://www.beermoneyforum.com/threads/kekolink-com-reviews-scam-or-legit.87089/

**Comment by Sainan** [comment]
Might be, we can add it to the #1573 bunch, I just don't see see the point in bypassing these links used by faucets.
