### ISSUE TITLE
rubtech.xyz

### ISSUE THREAD

**Issue by stuffi3000** [Sainan/Universal-Bypass#1602]
https://rubtech.xyz/index.php/2020/05/26/how-to-start-trading-in-forex-for-free-first-steps/

**Comment by FireMasterK** [comment]
You need to provide the previous URL as it requires a specific referrer.

**Comment by stuffi3000** [comment]
> 
> 
> You need to provide the previous URL as it requires a specific referrer.

Will do so here tomorrow as well
