### ISSUE TITLE
https://janusnotes.com/

### ISSUE THREAD

**Issue by Harfho** [Sainan/Universal-Bypass#1606]
https://janusnotes.com/?token=3qSqR45p - this link shows but it so quick in redirecting to  https://janusnotes.com/

then after solving the capctha on the page

it again redirect to https://janusnotes.com/electronic-health-record-program/  to wait for 10 seconds b4 the final destination

**Comment by Sainan** [comment]
@bogachenko, cheers, that website was a nightmare before I subscribed your filters xD

**Comment by Sainan** [comment]
Although, it seems this website is straight-up broken because it's missing jQuery
![image](https://user-images.githubusercontent.com/63328889/97781027-db14ae80-1b88-11eb-90f9-feeb60988c8c.png)
and it doesn't seem like anything jQuery-related was blocked

**Comment by FireMasterK** [comment]
The website is broken, but I did find a way to "unbreak" it.
`curl -H "Referer: https://janusnotes.com/" https://l.janusnotes.com/3qSqR45p`
Without the referer, it'll take you in a redirection loop.

So, the way to bypass this is by spoofing the referer and directly navigating to adlinkfly page.

**Comment by FireMasterK** [comment]
Tagging #1573 just in case.

**Comment by Sainan** [comment]
Don't see why I would unbreak link shorteners. Plus, another faucet site:
![image](https://user-images.githubusercontent.com/63328889/97791068-c78c3680-1bce-11eb-92d4-fb395d7d1bff.png)

**Comment by Harfho** [comment]
that faucet site is just using their service,
![Screenshot_1](https://user-images.githubusercontent.com/39716223/97792703-f64ae280-1bb7-11eb-9dc3-4eb91ee1e0d9.png)

**Comment by Sainan** [comment]
They're using it as an integrated ad wall. So, with all due respect, I don't give a fuck. I'm not here "bypassing" ad walls. You either deal with the ad wall, or don't use a faucet. Dead, fucking, simple.

**Comment by Harfho** [comment]
OK Boss
