### ISSUE TITLE
¿Cómo puedo comprobar que Universal Bypass funciona?

### ISSUE THREAD

**Issue by LEMC-ciber** [Sainan/Universal-Bypass#1610]
There's a list of example links where you can see Universal Bypass in action over here.
no esta el exe.io en la lista.
Example Links
A small list of sites which are bypassed by Universal Bypass follows. Of course, because Universal Bypass is bypassing several templates which are used in many places, it's impossible for me to give you a proper list of all domains that are bypassed.

Is there a site Universal Bypass is not yet or no longer bypassing? Please open an issue on Github or send me an email!

Adf.ly
Sh.st (Shorte.st)
Show.co
SourceForge.net
sub2unlock.com
mylink.zone (Clictune.com)
srt.am (Short.am)
cshort.org
link.tl
won.pe
Bit.ly (Tracker Bypass)
Goo.gl (Tracker Bypass)
T.co (Tracker Bypass)
Grabify.link (Tracker Bypass)
l.ly (GemPixel/KBRMedia Premium URL Shortener Template)
tetew.info (GemPixel/KBRmedia Premium URL Shortener Template)
animanganews.com (Safelink Bloggerku Template)
losstor.com
onepieceex.net
Bluemediafiles.com
complete2unlock.com
sub2unlock.net
do2unlock.com
mirrorace.com
linkrex.net (AdLinkFly Template) (Crowd Bypass)
ouo.io (Crowd Bypass)
rom.io (Crowd Bypass)
bc.vc (Crowd Bypass)
cuio.io (Crowd Bypass)
adyou.me (Crowd Bypass)
oke.io (Crowd Bypass)
cpmlink.net
hidelink.club
ux9.de
telolet.in
Akoam.net

NOTA! no esta exe.io 
ESPERO QUE LO PUEDAS ARRELGAR AMIGO, GRACIAS,
 SALUDOS DESDE COLOMBIA.

**Comment by respecting** [comment]
Captcha, and already bypassed via Crowd Bypass.

**Comment by Sainan** [comment]
Also, spam.
