### ISSUE TITLE
t.co errors in Chrome 86

### ISSUE THREAD

**Issue by dividedby** [Sainan/Universal-Bypass#1612]
When clicking on t.co links I receive the below error.

Example link: `https://t.co/NKMEXEzYLN?amp=1`

![image](https://user-images.githubusercontent.com/64715420/97950555-dbfe3980-1d5c-11eb-8461-67c5fa3a95c6.png)

**Comment by respecting** [comment]
Not an error, just a warning. Although Sainan should probably stop using XMLHttpRequest and use fetch.

**Comment by dividedby** [comment]
> Not an error, just a warning. Although Sainan should probably stop using XMLHttpRequest and use fetch.

Is there something I can do on my side to make the redirects go through without disabling the extension?

**Comment by respecting** [comment]
What do you mean? That "Synchronous XMLHttpRequest" thing is a warning, you can tell by the yellow triagne and exclamation point.

**Comment by Sainan** [comment]
This is not an issue as long as the extension works.

**Comment by dividedby** [comment]
> This is not an issue as long as the extension works.

The extension doesn't work, the pages don't redirect/load.

**Comment by Sainan** [comment]
Seems to be an issue with apimon. You can disable tracker bypass in the options.

**Comment by dividedby** [comment]
Looks like I had to add a universal noop for apimon.de in uBlock Origin,
maybe add that to the FAQ/documentation?

**Comment by Sainan** [comment]
You can literally disable the tracker bypass in the options of Universal Bypass. But sure, keep blocking everything and complain when everything breaks.

**Comment by dividedby** [comment]
Apologies for trying to get clarification on an issue with the extension,
next time I’ll make sure not to bother.

**Comment by Sainan** [comment]
Is there anything I didn't clarify? Maybe you should actually open your eyes and read.
