### ISSUE TITLE
dutchycorp.ovh

### ISSUE THREAD

**Issue by wuniversales** [Sainan/Universal-Bypass#1613]
I have noticed that the domains "`https://dutchycorp.ovh/sh/****`" redirect to "`https://*.dutchycorp.space/****`" to later go back to the domain "`https://dutchycorp.ovh/sh/****`".
Why not remove the timeout in "`https://*.dutchycorp.space/****`"? 
Example link: https://dutchycorp.ovh/sh/hpOoXvz
Cheers

**Comment by Sainan** [comment]
Faucet.

**Comment by respecting** [comment]
If you want to remove the timeout, just put this in custom bypasses:
`domainBypass("movies.dutchycorp.space", () => {
	ifElement("#cl1 > center:nth-child(1) > a:nth-child(1)", (a)=>{
		safelyNavigate(a.href)
    })
})`
