### ISSUE TITLE
buff.ly

### ISSUE THREAD

**Issue by MaxJW** [Sainan/Universal-Bypass#1616]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

Example Link: https://buff.ly/2HYWMNt
Leads to: https://www.pcgamer.com/best-minecraft-texture-packs/?utm_content=bufferf351e&utm_medium=social&utm_source=twitter&utm_campaign=buffer-pcgamertw

**Comment by Sainan** [comment]
I assume you want a tracker bypass, in which case, this is already bypassed.
