### ISSUE TITLE
SHORTE.ST

### ISSUE THREAD

**Issue by FreePromotions** [Sainan/Universal-Bypass#1619]
https://i.imgur.com/iuFmmrl.png

**Comment by Sainan** [comment]
This should be bypassed; make sure to update your Universal Bypass -- not just the bypass definitions. Also, provide an example link, and not this vague bullshit, if you care for anything being done.

**Comment by FreePromotions** [comment]
Updating it seemed to work but just so you know, the link on your website does not direct to the same issue section from here. As in, on the website, it just loads a simple forum box, no requested info, etc. [Example Imgur Link](https://i.imgur.com/v3W7Ank.png )

You should update that link to show that instead. Also, SHORTE.ST is the literal site where the links get shortened. That's why I put it in the title. 

Here are some example links, which I thought weren't necessary since I gave the source website.
http://corneey.com/wOvZWE
http://destyy.com/wOIQnC
