### ISSUE TITLE
https://www.muxnux.com/

### ISSUE THREAD

**Issue by ModooMarble** [Sainan/Universal-Bypass#1623]
https://www.anonimfiles.my.id/2020/04/psiphon-pro-mod-apk-download-v254.html#?o=d621f7f85418c746d9e48a648a1786ccbc976e973b14db4d55d04fc8d1f60052433953d9173f5cec1b5b5df595c051db3e8e9d4a8d434348
https://casperqu.blogspot.com/2019/07/cara-mengetahui-alamat-ip-sebuah-website.html#?o=fdc7e9d47f2d7a48e8cf1800bc4da79ee3d542316c521bf7de1dbf492b0a2127cf4369db4929112c
from https://www.muxnux.com/2020/10/wedding-peach-episode-37-subtitle.html

**Comment by ModooMarble** [comment]
@Sainan https://lewatinmas.blogspot.com/2020/01/beware-washing-machines-can-make-flu.html#?o=699f6d95aca939bcc5bdfd37205fcaf0039cf3dcd705ddbbd7c96aa55d27e38e282cd28b6d1b91ec
one more from https://www.muxnux.com/2020/10/wedding-peach-episode-36-subtitle.html

**Comment by Sainan** [comment]
Seems broken to me.
