### ISSUE TITLE
"You're being navigated to..."

### ISSUE THREAD

**Issue by rpodric** [Sainan/Universal-Bypass#1624]
I see it in the release notes:

-Universal Bypass now says "You are being navigated to https://..." with "Take me to destinations after 0 seconds." set, so you know something is happening if the destination is slow.

But I'd like to never see it, since at best it's not telling me anything, and at worst it's slowing down the transition. I unchecked "Take me to destinations after..." but that didn't help, at least on the Chromium version.

Note that I'm seeing it on sites that have nothing to do with bypassing anything. They're just straight links leading to another site, like from Slate.com. I'm not sure why it's bothering with those in the first place.

**Comment by Sainan** [comment]
It shouldn't slow anything down if you have a CPU from the last decade or so. As for "sites that have nothing to do with bypassing anything", it could just be the tracker bypass, which you can disable in the options.

**Comment by rpodric** [comment]
OK, thanks, I was so concentrated on the option right above that one, which I thought was the one causing it based on the release note, that I didn't notice the option right beneath it.

While I agree that it shouldn't slow things down, I have seen hangups when trying to resolve "t.co" type shorteners. It'll just not resolve in those cases sometimes. Perhaps related to Apimon.de, which it apparently uses each time.

**Comment by FireMasterK** [comment]
That's an unrelated issue, it could be that apimon.de takes a long time to respond, or you have a slow connection to Germany.
