### ISSUE TITLE
www.shrinkads.com

### ISSUE THREAD

**Issue by JeelsBoobz** [Sainan/Universal-Bypass#1628]
Page not redirected to target
Example https://www.shrinkads.com/full/?api=e943d9ebe64203a6ca9f0982f83d6f543dff4bdb&url=aHR0cDovLzRrbGlrLnh5ei9maWxlLzY1MTM2MjQ3OA==&type=2

**Comment by respecting** [comment]
Already bypassed. Works for me on 13.15.1

**Comment by JeelsBoobz** [comment]
But, not redirected to target
Browser: Firefox Nightly Android 10

**Comment by respecting** [comment]
What do you mean not redirected to target? It redirects me to http://4klik.xyz/file/651362478

**Comment by Sainan** [comment]
Might be some weird Mozilla thing. You might wanna roll your Firefox back to before they decided to break all extensions for no reason.
