### ISSUE TITLE
OUO.IO Bypass solution found for PH users

### ISSUE THREAD

**Issue by Aroueterra** [Sainan/Universal-Bypass#1653]
Hello, I just wanted to bring up that ouo.io is IP banned for the entirety of the philippines. However, you can easily bypass the website through deleting the html prefix and replacing .io with .press and keeping the code. I don't know how universal bypass handles things, but it can attempt to bypass .press from that point on after making the redirection. 

I hope this feature gets looked into, to help out some folks over @PH! Thanks.

**Comment by FireMasterK** [comment]
Example URL?

**Comment by Aroueterra** [comment]
ISP banned domain:
https://ouo.io/Xapc6G
unbanned domain
ouo.press/Xapc6G

ouo's just another link shortener with a timer.

**Comment by Sainan** [comment]
"ISP banned" is not really something I wanna get into. Possibly could be fixed by a preflight redirect, tho.

**Comment by FireMasterK** [comment]
I'd say it's only a matter of time until the other domain gets blocked too, a more permanent solution would be to bypass the block instead.

 I'm sure depending on what kind of block is used, you can use one of these:
- VPN
- ESNI on Firefox
- DPI bypasses
- Cloudflare Warp (technically a vpn)
- A Secure DNS server

I'd say this issue is out of Universal Bypass's scope.

**Comment by Sainan** [comment]
You're probably right. If it were some movie streaming site, then your ISP blocked it as a result of a lawsuit, in which case, that would've been an endlessly slow process, but since it's just annoying ad scum, perhaps your ISP is trying to do the right thing? ;P

**Comment by Aroueterra** [comment]
Alright, thanks for looking into it anyway. The workaround has actually been around for 4 years now, and we've mostly resorted to TOR browser to get around it. Was just wondering if UB was able to bypass before the block.
