### ISSUE TITLE
http:///bit.ly/2srVQFL stuck in loop

### ISSUE THREAD

**Issue by askfriends** [Sainan/Universal-Bypass#1654]
bypass is not working with this link and it just loop and nothing happens, have a look and fix it.
thanks
link is 
http:///bit.ly/2srVQFL

**Comment by FireMasterK** [comment]
Can you copy-paste what you see in https://apimon.de/redirect/https%3A%2F%2Fbit.ly%2F2srVQFL?

**Comment by askfriends** [comment]
> Can you copy-paste what you see in https://apimon.de/redirect/https%3A%2F%2Fbit.ly%2F2srVQFL?

{"valid":true,"destination":"https://www.lg.com/us/home-video/lg-HU80KA-projector?cmpid=social|HE|Projector|PROJ_IRM|HU80KA|Youtube|DIYCreator&utm_source=Youtube&utm_medium=IRM&utm_campaign=HU80KA|DIYCreator"}

**Comment by Sainan** [comment]
Don't see an issue, then. You can disable "Bypass trackers (such as bit.ly and t.co) using Apimon.de." in the options, tho.
