### ISSUE TITLE
t.co some t.co links are looping

### ISSUE THREAD

**Issue by pcislocked** [Sainan/Universal-Bypass#1655]
https://t.co/9Q7lIRxQqq?amp=1

when i open it with universal bypass, it redirects to the very same link, thus looping. 

Some more example link that I've tested and does the same thing. Not all of them weirdly. 

https:///t.co/Tj1iGhl1Oe?amp=1
https://t.co/XxtlNIVcPk?amp=1

No, deleting ?amp=1 didn't help.

**Comment by shifting-tides** [comment]
same issue.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/100232758-cab8df00-2f4e-11eb-9c36-c4a6c9db5e6f.png)

Can't replicate this issue on my end.

What does opening https://apimon.de/redirect/https%3A%2F%2Ft.co%2F9Q7lIRxQqq%3Famp%3D1 show you? (copy-paste the response here).

**Comment by Sainan** [comment]
You can disable "Bypass trackers (such as bit.ly and t.co) using Apimon.de." in the options.
