### ISSUE TITLE
[Feature Request] for JS alert blocking - sample code included

### ISSUE THREAD

**Issue by nasova** [Sainan/Universal-Bypass#1673]
hi
hope this is the right place for this

can you please add this js to be part of Universal-Bypass for skipping Alerts
i already use this as UserScript and it works.
thank you

`// ==UserScript==
// @name        XX Block javascript alerts
// @match       http://*/*
// @match       https://*/*
// @run-at      document-start
// ==/UserScript==

addJS_Node (null, null, overrideSelectNativeJS_Functions);

function overrideSelectNativeJS_Functions () {
    window.alert = function alert (message) {
        console.log (message);
    }
}

function addJS_Node (text, s_URL, funcToRun) {
    var D = document;
    var scriptNode = D.createElement ('script');
    scriptNode.type = "text/javascript";
    if (text)scriptNode.textContent = text;
    if (s_URL)scriptNode.src = s_URL;
    if (funcToRun)scriptNode.textContent = '(' + funcToRun.toString() + ')()';

    var targ = D.getElementsByTagName ('head')[0] || D.body || D.documentElement;
    targ.appendChild (scriptNode);
}`

**Comment by Sainan** [comment]
Don't really see how that would fit into Universal Bypass.
