### ISSUE TITLE
ERR_FILE_NOT_FOUND Redirect on all attempts to bypass any link.

### ISSUE THREAD

**Issue by JacksonTravisRipper** [Sainan/Universal-Bypass#1688]
> Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. > > For more help, check https://xhr.spec.whatwg.org/.

is the error raised, attempts to bypass any link lead to a ERR_FILE_NOT_FOUND page, the same happens when I click on the extension. 
> Context: _generated_background_page.html
> Stack Trace: background.js:533 (resolveRedirect)

**Comment by Sainan** [comment]
Which browser and version?

**Comment by JacksonTravisRipper** [comment]
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4230.1 Safari/537.36

**Comment by Sainan** [comment]
I didn't want your user agent. I wanted to know which browser and which version of it you're using.

**Comment by JacksonTravisRipper** [comment]
Ok, it says it right there though. Google Chrome 86.0.4230.

**Comment by Sainan** [comment]
I have Chrome 87, and I don't see ERR_FILE_NOT_FOUND on any attemps to bypass a link. What's your settings and can you provide an example link?

**Comment by JacksonTravisRipper** [comment]
http://intamema.com/25e is just some adfly link I generated, it breaks there, it also breaks when I try to view my settings, eg. clicking on the plugin I tried re-installing etc.

**Comment by Sainan** [comment]
You can't even view the settings? How did you install it?

**Comment by JacksonTravisRipper** [comment]
I downloaded the zip, unzipped it into a folder selected "Load unpacked" then selected it. It displays the extension there properly.

![image](https://user-images.githubusercontent.com/74473587/103437337-7dd2c300-4bf4-11eb-9506-e79e5172967e.png)

**Comment by Sainan** [comment]
Can't reproduce.
