### ISSUE TITLE
This website it doesn't bypass

### ISSUE THREAD

**Issue by iDevilz12** [Sainan/Universal-Bypass#1700]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

**Comment by BanderAlfaify** [comment]
https://getlink.animesanka.club/2020/10/sanka-shortcut.html#?o=c290b5866da7bbc7c6970ff1bab14d57b12b6d783a955d81670b48da966b69a148c1f3b9130af3bb194999e61ddcda0480e31e484103a8a1a2e52011c6af4017090d54a8f735649877586492147479dc8dbcb61c4a6500608f57b5c182a7997f430eb27218635e5071a93db38a279daaba6b77101f25610e8072f01f732c2a259d43b7749b1cccfb49cff03bdba9d3306eaae02639af6ea27612a58faeac58d35acc6bf5cdddf7ca
