### ISSUE TITLE
A site completely blocked due to detected bypass (changed useragent)

### ISSUE THREAD

**Issue by galra** [Sainan/Universal-Bypass#1701]
www.haaretz.co.il is reutrning 403 if one accesses with a googlebot UA, as defined in rules.json:
```
"useragent_googlebot": [
		"*://*.haaretz.co.il/*"
	],
```
I played with it, and the user agent is indeed the sole cause for the 403 response. Specifically, that's the problematic UA:
`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
I suggest to simply remove this rule.

I'm not sure what was it used for, actually. Without it I still don't get any ad/waiting screen I need to pass, and would have just disabled the add-on for this site if it was possible.

Thanks.

**Comment by Sainan** [comment]
Still getting 403 even with this rule removed, but... it's whatever

**Comment by pixelcookie11** [comment]
This latest commit is breaking something. After this I was banned from Cloudflare, google switched to the mobile view and all Anti-DDoS protections were blocking me.
