### ISSUE TITLE
Causing Chrome to be detected as a crawler/bot

### ISSUE THREAD

**Issue by dickhead420** [Sainan/Universal-Bypass#1703]
Not sure how else to explain it. Enabling it and going onto Reddit limits my connections and essentially says "You're a bot, stop connecting to us so often". Google turns into some mobile-looking view, and my e-mail becomes far more barebones. 

Checking on https://www.whatismybrowser.com/ with Universal Bypass enabled detected my browser as Googlebot 2.1, however when disabling the extension, it returns to being detected as an up-to-date Chrome 87 browser, which is correct.

**Comment by checkraisefold** [comment]
Just started happening on chrome webstore version

**Comment by konrel** [comment]
Same here with Kiwi Browser on my phone and Chrome on my PC. Disabled the extension for now.

**Comment by savageduckerino** [comment]
same problem it just started

**Comment by Salo7a** [comment]
The User-Agent changes to Googlebot, causing these problems, it changes to
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
I think this has to do with the commit of #1701, Line 217 in rules.json causes the UserAgent in all sites instead of nowhere, If I understand correctly.

**Comment by lufadriad** [comment]
> The User-Agent changes to Googlebot, causing these problems, it changes to
> Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
> I think this has to do with the commit of #1701, Line 217 in rules.json causes the UserAgent in all sites instead of nowhere, If I understand correctly.

i was thinking the same.

**Comment by K-E-N-W-A-Y** [comment]
yes, looks like commit fb6056ed692a4e1250bd89ea06f896023bbac0d9 causing the this issue.

**Comment by kvn1351** [comment]
Same, after a few minutes Google even requests captchas each time now..
