### ISSUE TITLE
Universal Bypass causes centered chrome

### ISSUE THREAD

**Issue by Rhinozz** [Sainan/Universal-Bypass#1704]
This isn't a problem with a specific bypass, but with Chrome itself (Google Chrome version 87.0.4280.141 64-bit). The problem occurs on google.com, the [Google search results page](https://www.google.com/search?q=test&rlz=1C1CHBF_enUS832US832&oq=test&aqs=chrome.0.69i59j0i67j0i433j0l3j69i60l2.3343j0j7&sourceid=chrome&ie=UTF-8), and every page that has bot or DDOS protection (such as [Reddit](https://www.reddit.com/)). When Universal Bypass is off, I get normal pages - going to the websites mentioned earlier will give you an idea of what they are supposed to look like. However, with Universal Bypass on, the pages look like this.
![image](https://user-images.githubusercontent.com/68926744/104140131-c9683800-537d-11eb-9062-20aab630ab78.png)
![image](https://user-images.githubusercontent.com/68926744/104140135-d8e78100-537d-11eb-91ac-4001b0b63316.png)
![image](https://user-images.githubusercontent.com/68926744/104140138-e1d85280-537d-11eb-9e91-cd087b2fb8b7.png)
It is not a problem with just the extension, but with the "Enable website bypasses" option within it. With the extension enabled but that option disabled, the pages function just fine. With it enabled, the problem occurs. Is there a way to get around this or a new version to download? Thanks in advance :)

**Comment by savageduckerino** [comment]
same problem it just started

**Comment by SESNut** [comment]
browser is being identified as googlebot2.1
![Screenshot 2021-01-10 200442](https://user-images.githubusercontent.com/27609765/104140345-1d275100-537f-11eb-9fb9-e9abc3749615.jpg)

**Comment by Salo7a** [comment]
The User-Agent changes to Googlebot, causing these problems, it changes to
`Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
I think this has to do with #1701, Line 217 in rules.json causes the UserAgent in all sites instead of nowhere, If I understand correctly.

**Comment by lufadriad** [comment]
same here.

**Comment by Viniuau** [comment]
Same problem here. I was freaking out about what it might be. Then this is showing
![image](https://user-images.githubusercontent.com/19510529/104140697-6d0f1380-5391-11eb-8059-133f637ed1be.png)

**Comment by DyonR** [comment]
Can also confirm

**Comment by LEx66** [comment]
yeah, my browser is being identified as a google bot

**Comment by jehbe5** [comment]
Yes same here, it looks like it loads old versions of the websites. Even my facebook website is all messed up, + google wouldn't let me login since it says I am using an unsecured browser. My browser is Brave

**Comment by kainjinez** [comment]
I'm using Microsoft Edge also experience the same problem. Not even Google, Shopee also failed to load resources and also other sites. After turn off Universal Bypass then it works well.

**Comment by nathangv** [comment]
Change your user agent to something else using an extension. It's a temporary workaround until a fix comes but it works.
For Edge: https://microsoftedge.microsoft.com/addons/detail/useragent-switcher/npjnioaeoicmjokbdpfiecnbildopjad?hl=en-US
For Chrome: https://chrome.google.com/webstore/detail/user-agent-switcher/iojaoainolpgkpojokmeclhidjolocci/related

This is what I set it to on Edge:
![image](https://user-images.githubusercontent.com/77255376/104142721-b134ff00-53f7-11eb-92f5-ded1566f3263.png)

And this is what I set it to on Chrome:
![image](https://user-images.githubusercontent.com/77255376/104142768-e6d9e800-53f7-11eb-82ac-63d27f02dfa4.png)
