### ISSUE TITLE
Change the look of google

### ISSUE THREAD

**Issue by Kimitaku** [Sainan/Universal-Bypass#1706]
Before it gave me no problem, today I went to google and a google something different than usual appeared and with a black line, when deactivating universal bypass that weird google no longer appears. Note: (I am Spanish, I used the translator)
Image: https://imgur.com/a/ftDgCad

**Comment by ahfidbilal** [comment]
Also, blocked from Cloudflare


"Sorry, you have been blocked
You are unable to access"

**Comment by sitiom** [comment]
Duplicate of #1704
