### ISSUE TITLE
Universal Bypass is officially blacklisted from Cloudflare

### ISSUE THREAD

**Issue by brian6932** [Sainan/Universal-Bypass#1708]
This breaks a number of websites
For example, it switches Google's UI:
![image](https://user-images.githubusercontent.com/18603393/104142167-587a4d80-5388-11eb-84d2-2d73b3df1251.png)
Makes sites secured by Cloudflare inaccessible:
![image](https://user-images.githubusercontent.com/18603393/104142193-721b9500-5388-11eb-8f29-d3423fa358a2.png)
Certain sites like Reddit are accessible, however, they show a splash screen before access:
![image](https://user-images.githubusercontent.com/18603393/104142215-8fe8fa00-5388-11eb-99e7-074a6670f355.png)

**Comment by Sarpar12** [comment]
mentioned in the last 4-5 issues #1707 #1704 #1706 #1703 . The workaround is by changing your useragent to something else rather than google bot 2.1
