### ISSUE TITLE
Please provide .crx so people who use Chromium Web Store has access to update checking.

### ISSUE THREAD

**Issue by raisehero** [Sainan/Universal-Bypass#1709]
Please see https://github.com/NeverDecaf/chromium-web-store/commit/0464d762a6ee6073906e6550d975a12e0901502c for instructions. This way, people who sideload and use Chromium Web Store has access to updates.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/104145849-a164ed00-53ee-11eb-9a06-8d6eb3b207c1.png)
You cannot install a CRX file.

**Comment by Sainan** [comment]
Shame.

**Comment by raisehero** [comment]
https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq
People who use Chromium has no problems with this.

**Comment by FireMasterK** [comment]
Judging from the filename, that looks like that crx is from the chrome webstore. If I'm not wrong, extension ids in the chrome website are excluded from the check.

**Comment by raisehero** [comment]
@FireMasterK Oh, really? https://streamable.com/bkm05k

**Comment by FireMasterK** [comment]
Interesting, in this case I guess it's worth considering this. However, it's still disappointing that only ungoogled-chromium supports this.

**Comment by Sainan** [comment]
I have to be honest, Ungoogled Chromium looks like software made by idiots -- first question in their FAQ is about their unreasonable defaults.

**Comment by raisehero** [comment]
Chromium binaries from here also can take CRX sideloading: https://chromium.woolyss.com/
