### ISSUE TITLE
Universal bypass, make cloud fire trigger 

### ISSUE THREAD

**Issue by Arkadio918** [Sainan/Universal-Bypass#1710]
Unversal bypass after the last update? make trigger cloudfire protection and cant bypass https://stayonline.pro/l/qJpq2/
Making it trigger an error :/

**Comment by Arkadio918** [comment]
Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.

What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.

Cloudflare Ray ID: XXfbXXffXXXdXXXX • Your IP: XXXX:bXX:XXXb:XdXe:XcbX:eXaX:XXaX:Xaae • Performance & security by Cloudflare

**Comment by Gotischer** [comment]
same her and google load worng

**Comment by MarvNC** [comment]
I got the same issue on lots of sites, Reddit, Google, and lots of sites that use cloudflare and the like. Gave me quite the scare until I went through to my extensions, Universal Bypass was the culprit.

![](https://i.fiery.me/6UFNs.png)

**Comment by SegFault-Verm** [comment]
Recent commit is setting Googlebot useragent in all cases #1704 , so all websites think you're Google's Crawler.
