### ISSUE TITLE
The Extension has change layout of the google search (BUG)

### ISSUE THREAD

**Issue by Alberiansyah** [Sainan/Universal-Bypass#1712]
Hello, just wanna tell you, i find a problem from your extension. Your extension has changing layout of the google search
just like this..

https://user-images.githubusercontent.com/46961588/104143017-767b9880-53f0-11eb-9ee3-445611cf5220.mp4

**Comment by GeorgeV220** [comment]
Please before you open a new issue check the old ones.

**Comment by Turi04470** [comment]
hello I have the same problem, do you know if I can install an older version of the extension?

**Comment by Alberiansyah** [comment]
> Please before you open a new issue check the old ones.

sorry i dont see the olf post :(

**Comment by Alberiansyah** [comment]
> hello I have the same problem, do you know if I can install an older version of the extension?

no i dont

**Comment by Alberiansyah** [comment]
because the old post already had a same problem, i close this issue :)
