### ISSUE TITLE
Al tener activada la extensión me carga las búsquedas de Google como si estuviera en un celular

### ISSUE THREAD

**Issue by Turi04470** [Sainan/Universal-Bypass#1713]
Cuando la extensión esta habilitada y hago una búsqueda (cualquiera) en el navegador Google Chrome me carga los resultados como si estuviera en un celular y no carga la vista clásica de una computadora ya hasta intente reinstalar el navegador la extensión desde otro ordenador y nada sigue igual solo se soluciona cuando desactivo la extensión

**Comment by Luadih** [comment]
Duplicado de #1706 (y varios mas)
Y ya se esta intentando arreglar en #1712
