### ISSUE TITLE
Extension broken on Microsoft Edge

### ISSUE THREAD

**Issue by Sirosky** [Sainan/Universal-Bypass#1717]
[Extension is broken on Edge](https://i.imgur.com/3tFt1s7.png). I also got a warning when browsing Reddit with the extension activated that I was sending too many requests. Not sure if the problem has been fixed yet, but opening a new issue for now.

**Comment by FireMasterK** [comment]
Click on "Check for Updates" in the options

**Comment by Sirosky** [comment]
Thanks, haven't been seeing any bugs. Problem appears to be fixed.
