### ISSUE TITLE
https://semawur.com/SfQERvl

### ISSUE THREAD

**Issue by ModooMarble** [Sainan/Universal-Bypass#1721]
https://semawur.com/SfQERvl
please fix it

**Comment by unknown4849** [comment]
this work fine , so what problem ?

**Comment by BarehSolok** [comment]
> 
> 
> this work fine , so what problem ?

it's not 
![Screenshot_2](https://user-images.githubusercontent.com/83990509/132087558-821b4065-1e9e-4ed8-8ad6-fb413abb0b76.png)
please add support
