### ISSUE TITLE
extension broken by itself

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1725]
![image](https://user-images.githubusercontent.com/19517680/104827821-939ee400-5894-11eb-8c74-e4c0c04a7327.png)

Google Chrome is up to date
Version 88.0.4324.87 (Official Build) beta (64-bit)

**Comment by Sainan** [comment]
Steps to reproduce?

**Comment by 3xploiton3** [comment]
i dont know, i reinstall from github again, now work,
