### ISSUE TITLE
adshrink.it

### ISSUE THREAD

**Issue by minanagehsalalma** [Sainan/Universal-Bypass#1726]
![image](https://user-images.githubusercontent.com/20546638/104938751-284e3280-59b8-11eb-8444-e41f3771b4e8.png)

it stopped working ... even thought the link is too easy to bypass ... the real url in base64 encoded after the domain.
![image](https://user-images.githubusercontent.com/20546638/104938844-4f0c6900-59b8-11eb-9fe2-917eec472b10.png)

**Comment by Sainan** [comment]
Invalid. Please provide an actual example link.

**Comment by minanagehsalalma** [comment]
> Invalid. Please provide an actual example link.

@Sainan  here [you go ](https://adshrink.it/MzE5MzQ=/aHR0cHM6Ly93d3cud29ybGRzcmMubmV0L2Rvd25sb2FkLz90PWdhbWUmaT0xODg3Jm49NmNhNjFjNl9Xb3JsZFNyYy5vcmdfX01hZmlhRGVmaW5pdGl2ZV9FZGl0aW9uLnppcA==)
