### ISSUE TITLE
www.googleadservices.com

### ISSUE THREAD

**Issue by Games-Crack** [Sainan/Universal-Bypass#1729]
Before you report a website that isn't bypassed yet, please use the search function to ensure that the site wasn't already reported: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE

If that is not the case, please **provide an example link.** We need to be able to see what there is to be bypassed, otherwise there can't be a bypass.

(in My Network www.googleadservices.com is blocked thats why i want a bypass)
You encounter such links if you search on google and go to shopping

Example : 
[link.txt](https://github.com/Sainan/Universal-Bypass/files/5837303/link.txt)

**Comment by Sainan** [comment]
Install an adblocker or don't click on ads?

**Comment by Games-Crack** [comment]
I have an adblocker too

**Comment by Sainan** [comment]
Then get an adblocker that works.

**Comment by Games-Crack** [comment]
it does work but this site is blocked by my DNS Server

but ok if you dont wana do a bypass then i will not bug you anymore

**Comment by Sainan** [comment]
Seriously, I use uBlock Origin and I never encounter googleadservices.com.
