### ISSUE TITLE
[Wait-code] devdrive.cloud

### ISSUE THREAD

**Issue by Cyberavater** [Sainan/Universal-Bypass#1731]
Eg link: https://devdrive.cloud/444e79f1b30ad3f7/Setup_Miracle_Thunder_Edition_3.12_MobileRdx.com.rar

**Comment by RobbyAJM** [comment]
```
domainBypass("devdrive.cloud", () => {
    ensureDomLoaded(() => {
        var functionString = display.toString();
        var regex = /href='(.*)'><span/;
        var match = regex.exec(functionString);
        console.log(match[1]);
        // safelyNavigate(match[1]);
    })
})
```
The website has server-sided validation, so no matter if you were able to bypass on the client-side, they will catch you on the server-side.
Once the "not ready" links is navigated, it will expire. And you have to wait again.

Meaning, waiting for the counter is a **must**.

**Comment by Sainan** [comment]
`infoFileHoster` could still be provided: https://github.com/Sainan/Universal-Bypass/blob/master/injection_script.js#L755

**Comment by RobbyAJM** [comment]
I don't know about that, how do `infoFileHoster` works?

Do you mean, I should use `infoFileHoster` to inform the user that the website isn't bypassable?

**Comment by Sainan** [comment]
Look at the line of code I provided. It's just a big regex of file hosters which injects the file hoster message so the user knows that it can't be bypassed.
