### ISSUE TITLE
Sh.st (Shorte.st)

### ISSUE THREAD

**Issue by albertaparicio** [Sainan/Universal-Bypass#1733]
The [example link](http://sh.st/wVGYZ) for `Sh.st (Shorte.st)` in the [Example Links page](https://universal-bypass.org/example-links) does not bypass

**Comment by Sainan** [comment]
Except it does?

**Comment by Darkmaster006** [comment]
> 
> 
> Except it does?

It does not. In fact, no link from shorte.st in any of its domains bypasses. My version is '13.15.1.3' updated Jan 27. Is this the last one?
