### ISSUE TITLE
Stolen tempered extension on the Firefox store.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Sainan/Universal-Bypass#1744]
Upon checking the Firefox extension store, I´ve noticed one particular user who stolen two popular extensions, A version of buster detailed here : https://github.com/dessant/buster/issues/268 And a version of your extension, renamed as ¨Universal-bypassed¨.
However, while the previous extension only had just a manifest change, this one seems to have modifications, to the : 
background.js
content_scripts.js
injection_scripts.js
rules.json
And manifest.json (Obviously) after a diff check.

Their copy of your extension claim to be version 13.15.2.1 from a month ago (Despite your current version, being 13.15.1.2 from only 18 days ago). 
The changes aren´t even upstreamed from your repo as they are still different from checking the injection_scripts.js.
It does contain some merged commits thought as commit 61fb394 being there.

As the author of this reposted extension has been confirmed to have stolen the previously mentionned buster extension, I´ll suggest taking a look at it, and try to take it down. 
I´ve already reported it and will do the necessary steps to be taken down by Mozilla.

https://addons.mozilla.org/en-US/firefox/addon/universal-bypassed/

**Comment by Sainan** [comment]
I strongly believe that copyright is for cowards. Universal Bypass is published under the Unlicense and anyone is able to do what they want with the source code. Unless there are violations of the terms of service for AMO, this is not an issue. And in any case, this is not an issue for me.

**Comment by PoorPocketsMcNewHold** [comment]
Still different than the WTFPL license that is, nor the power you have on ensuring no loss of donations or decredibility can be done by someone who isn´t yourself.

**Comment by Sainan** [comment]
I don't care. Copyright is a system for the rich to get richer, and I'm not taking part in it.
