### ISSUE TITLE
sh.st

### ISSUE THREAD

**Issue by FreyaFriday** [Sainan/Universal-Bypass#1746]
This is an alternative link for shorte.st
Example link: http://sh.st/JfYUS

**Comment by Sainan** [comment]
Already bypassed. Update Universal Bypass.

**Comment by Darkmaster006** [comment]
> 
> 
> Already bypassed. Update Universal Bypass.

I cannot bypass it either. My version is '13.15.1.3' updated Jan 27, I am using Firefox.
