### ISSUE TITLE
docs.google.com

### ISSUE THREAD

**Issue by halotroop2288** [Sainan/Universal-Bypass#1751]
Google Drive download pages always crash (at least once) before downloading the file.
Google Drive links should have an exception made for them so this does not happen.

As it is impossible to retrieve direct links, I will provide links which lead to the download page.
Hopefully you'll be able to figure it out for yourself.

[Quackberry SFX (Preview page)](https://drive.google.com/file/d/1qZeYCcj4hqv_8dFPteeFTaXpbry_Xgow/view?usp=sharing)

https://user-images.githubusercontent.com/30361266/105768634-824b7c80-5f11-11eb-9029-8c0cee06bbcf.mp4

[A Goofy Movie Fandub (Preview page)](https://drive.google.com/file/d/1MJbTa7fK7rhFLwKEh1u_y9qUtJ-EcJC6/view)

https://user-images.githubusercontent.com/30361266/105768697-97c0a680-5f11-11eb-8bfe-97994506d53a.mp4

**Comment by Sainan** [comment]
Can't reproduce in Chrome or Firefox. Second link needs access. Ensure your UB is up-to-date.
