### ISSUE TITLE
exe.io

### ISSUE THREAD

**Issue by KINGSMM** [Sainan/Universal-Bypass#1753]

**Comment by KINGSMM** [comment]
Eg link: exe.app/HLOMT4

**Comment by Sainan** [comment]
404. Where did you get that link from?

**Comment by KINGSMM** [comment]
New Link 1 Exe.io: https://exe.io/newtestbyps
New Link 2 Exe.app: https://exe.app/newtestbyps

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.
