### ISSUE TITLE
t.ly

### ISSUE THREAD

**Issue by IDON-TEXIST** [Sainan/Universal-Bypass#1754]
Example link: https://t.ly/nQjy

Note: Is an ip grabber.

**Comment by Sainan** [comment]
How is this an IP grabber?

**Comment by IDON-TEXIST** [comment]
![tly](https://user-images.githubusercontent.com/73442356/107386462-cb8ff480-6aeb-11eb-8390-09481c5aeefd.png)

**Comment by Sainan** [comment]
> the link I posted [...] isn't a grabber

Okay, then please don't waste my time.

**Comment by IDON-TEXIST** [comment]
???
