### ISSUE TITLE
http://aporasal.net/

### ISSUE THREAD

**Issue by CloutNinja** [Sainan/Universal-Bypass#1761]
http://aporasal.net/ad/locked?rndad=1204639476-1611931594&url=7CBa&t=s&subid=16597707&h=89878

found at: https://thatnovelcorner.com/penguindrum/
only shows up if there are more than 1 download tabs open

also seems to cause an error
![Capture](https://user-images.githubusercontent.com/54197644/106289647-c33fdb80-6206-11eb-99ce-e225f268ab09.PNG)

**Comment by Sainan** [comment]
I don't see the issue here.
