### ISSUE TITLE
[SoundCloud] gate.sc

### ISSUE THREAD

**Issue by DRSDavidSoft** [Sainan/Universal-Bypass#1765]
This domain is used in SoundCloud (**gate.sc**).

### Example
```
https://gate.sc/?url=https%3A%2F%2Ffox-wedding.bandcamp.com%2Ftrack%2Ftoo-little-too-late&token=3b4dc-1-1610897412436
```

### Results
```
https://fox-wedding.bandcamp.com/track/too-little-too-late
```

**Comment by Sainan** [comment]
What is there to be bypassed?

**Comment by DRSDavidSoft** [comment]
@Sainan The `https://gate.sc/?url=https%3A%2F%2Ffox-wedding.bandcamp.com%2Ftrack%2Ftoo-little-too-late&token=3b4dc-1-1610897412436` url should be redirected to `https://fox-wedding.bandcamp.com/track/too-little-too-late`, thanks!

**Comment by Sainan** [comment]
but this is the behaviour that I am already observing.

**Comment by DRSDavidSoft** [comment]
Yes, but it's not intercepted by Universal Bypass, as it is for domains such as `anonymz.com` are.  The redirect is happening on the server side (SoundCloud) -- rather than on the client (by Universal Bypass).
