### ISSUE TITLE
need push update for ms edge

### ISSUE THREAD

**Issue by 3xploiton3** [Sainan/Universal-Bypass#1789]
![image](https://user-images.githubusercontent.com/19517680/107143139-ee909c00-6965-11eb-956e-54096c346a2a.png)

![image](https://user-images.githubusercontent.com/19517680/107143151-fd774e80-6965-11eb-9ed4-6d38e6e41cce.png)

**Comment by Sainan** [comment]
I have pushed the update when I released 13.15.2, and it seems it has passed the "review process" as of now.

**Comment by Sainan** [comment]
I seem to have misread the page, it is still "pending review":
![image](https://user-images.githubusercontent.com/63328889/107184786-841d4180-69e1-11eb-9a7c-a8be73e26693.png)
