### ISSUE TITLE
https://sourceforge.net/ (Infinite redirect)

### ISSUE THREAD

**Issue by Hexcede** [Sainan/Universal-Bypass#1791]
Version 13.15.1
Definitions: `d0d6837`

When downloading any file from SourceForge, UniversalBypass redirects in an infinite loop, usually causing a frozen page followed by a too many requests error.
This issue appears to have been previously fixed, but is occurring in the version and the definitions from above.

**Comment by Sainan** [comment]
Can't reproduce. You're also not using the latest extension version.

**Comment by Hexcede** [comment]
> Can't reproduce. You're also not using the latest extension version.
This is because I'm using the extension from the Edge store which is not updated.
Anyways, I found the issue, it was residual from an older version of the extension or the bypass definitions (it was an HTTP 301 cache to be more specific)

**Comment by Sainan** [comment]
You're the second person to say it's not updated for edge: #1789
