### ISSUE TITLE
Universal Bypass randomly uninstalls

### ISSUE THREAD

**Issue by GameCenterJerry** [Sainan/Universal-Bypass#1801]
It happens randomly, I used to drop the .ZIP file onto the `chrome://extentions` but they told me to drop the FOLDER (refer to #1387). I dropped the folder of Universal Bypass but it still randomly uninstalls.

System Information:
macOS Catalina 10.15.3
1.6 GHz Dual-Core Intel Core i5

**Comment by Sainan** [comment]
Are you deleting the folder after you drop it into Chrome?

**Comment by GameCenterJerry** [comment]
Yes

**Comment by Sainan** [comment]
Well, guess that answered the problem.
