### ISSUE TITLE
majorgeeks.com

### ISSUE THREAD

**Issue by FinderID** [Sainan/Universal-Bypass#1804]
error / cannot acces when try to download at :

Download Microsoft .NET Framework from Author Site Download@Authors Site (.Net Framework 32-Bit)
Download Microsoft .NET Framework from Author Site Download@Authors Site (.Net Framework 64-Bit)

example link :
https://m.majorgeeks.com/files/details/microsoft_net_framework_4_5_final.html

**Comment by Sainan** [comment]
Seems to work fine.
