### ISSUE TITLE
https://kutt.io/

### ISSUE THREAD

**Issue by etintos** [Sainan/Universal-Bypass#1813]
can you add this site?? 

example 
https://kutt.io/FlqUWl

**Comment by chris01b** [comment]
#1817

**Comment by Sainan** [comment]
This is already bypassed by crowd bypass, which means you don't have to wait if someone has already waited on it.

**Comment by chris01b** [comment]
@Sainan I'm aware. My addition makes it so the website only requires one click to bypass.
