### ISSUE TITLE
The extension doesn't work when I add the community bypasses

### ISSUE THREAD

**Issue by Trunks8257** [Sainan/Universal-Bypass#1814]
Hello, I started using Universal Bypass and I read that you can add more bypasses, so I added https://github.com/Sainan/Universal-Bypass/blob/master/injection_script.js into my custom evasion and it stopped working. I checked the errors and I saw that it got one in the line 633 of background.js, and it says that safe_in is undefined. My browser is Opera GX. Thanks in advance

**Comment by Sainan** [comment]
The injection script is included with Universal Bypass; duplicating it is wholly pointless.

**Comment by Trunks8257** [comment]
oh I didn't know that, ty
