### ISSUE TITLE
https://newrepublic.com/

### ISSUE THREAD

**Issue by pafase** [Sainan/Universal-Bypass#1816]
Only 3 free articles. Removing cookies works.

Three examples:
https://newrepublic.com/article/161467/unholy-alliance-fuels-american-nativism
https://newrepublic.com/article/161457/literature-philosophy-awkward-match
https://newrepublic.com/article/161469/dominion-mike-lindell-right-wing-lie

**Comment by Sainan** [comment]
Out of scope.
