### ISSUE TITLE
anthargo.com (adfly)

### ISSUE THREAD

**Issue by PeacefulPotato** [Sainan/Universal-Bypass#1819]
http://anthargo.com/1bxo (redirects to example.com)
Edit: And now they're being especially evil and trying to hit you with ad notifications

**Comment by PeacefulPotato** [comment]
adfly skipper and redirect bypasser had the same problem so don't worry

**Comment by PeacefulPotato** [comment]
Alright, it looks like it may be an issue on my end because none of the links seem to work.

**Comment by Sainan** [comment]
Probably something wrong with your installation, although adfly even is bypassed by uBlock Origin.
