### ISSUE TITLE
UB worked once, then stopped working(I think bypass got busted)

### ISSUE THREAD

**Issue by 2Icoldinate** [Sainan/Universal-Bypass#1847]
Before you report a website that detects Universal Bypass, please use the search function to ensure that there are no other open issues regarding that site: https://github.com/Sainan/Universal-Bypass/issues?utf8=%E2%9C%93&q=ENTER+DOMAIN+HERE
I know it can be frustrating, but creating 10 issues regarding the same problem doesn't help.
**already checked it XD**

If that is not the case, please **provide an example link.** We need to be able to see what has gone wrong in order to fix it.
----

Same [file](https://k2s.cc/file/6a990555d8900/Test.txt) in [this issue](https://github.com/Sainan/Universal-Bypass/issues/313) 

**I only use these extension beside UB **: ublock origin, buster

Only guess I can make rn Is... I think I ***got busted***

**Example behaviour 1**:
![aaaa](https://user-images.githubusercontent.com/43439016/110545370-58bc7c80-8170-11eb-9f8f-2a0fba267ee4.gif)
*(Keep counting again and again and agai... dang it!)*

**Example behaviour 2**:
![avbc](https://user-images.githubusercontent.com/43439016/110545476-81dd0d00-8170-11eb-982d-af0adcb9c0fa.gif)
*(It says that captcha is incorrect XD)*

 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  
 
 
 
 
  

--------

# **Now... let me ask you... can you help me?**

![asdfsdasdfasdfasdfafsdf](https://user-images.githubusercontent.com/43439016/110545899-1e071400-8171-11eb-88d1-d7f79e9c8374.gif)
*(I mean... spamming cute innocent-looking kitten gif always works tho!!!)*

**Comment by 2Icoldinate** [comment]
**Daymnnn** guys. It was ip problem. Using different vpn ip at every trial of downloading file works. Btw, do you guys have any ip changer tool recommendation in this situation? XD

**Comment by 2Icoldinate** [comment]
ayy no replies?

**Comment by 2Icoldinate** [comment]
@Sainan ayy no replies?

**Comment by Sainan** [comment]
Take your medication.

**Comment by 2Icoldinate** [comment]
@Sainan lol.. no need to insult bro
