### ISSUE TITLE
New Site for Universal Bypass

### ISSUE THREAD

**Issue by ELEduDeLaGente** [Sainan/Universal-Bypass#1861]
https://fc.lc/

Sorry for the inconvenience and I hope that it is useful that you now know this site

**Comment by Sainan** [comment]
Example link?

**Comment by ELEduDeLaGente** [comment]
https://fc.lc/Kxy2g3

**Comment by Sainan** [comment]
Duplicate of #1841

**Comment by ELEduDeLaGente** [comment]
Ahh? Sorry I'm so dummy, but i don't understand
