### ISSUE TITLE
Automatically remove parent frame on preview.codecanyon.net

### ISSUE THREAD

**Issue by Dipdive** [Sainan/Universal-Bypass#1869]
Hi,

I'm annoyed with how Preview links on CodeCanyon are always shown as iframes within a container. They used to have a "Close" button to close the container and go directly to the demo but now every time I have to manually right click and select This Frme > Only Show This Frame.

I've tried writing a custom bypass script but I couldn't figure it out at all.

The way I want it to work is every time I open a site with the host preview.codecanyon.net, I want it to automatically open the URL in the iframe (class full-screen-preview__frame)

Example page: http://preview.codecanyon.net/item/fullevents-event-plugin-wordpress/full_screen_preview/31232652

Is this possible at all? Could you provide a custom bypass for this? Thanks

**Comment by Sainan** [comment]
You could just find the iframe src and `safelyAssign` it

**Comment by Dipdive** [comment]
Yes, but I don't know how to write that. Can you help?

**Comment by Dipdive** [comment]
@Sainan Yes, but I don't know how to write that. Can you help?

**Comment by Sainan** [comment]
With Universal Bypass' functions, it should be as easy as
```
ifElement("iframe",i=>safelyAssign(iframe.src))
```
