### ISSUE TITLE
Instantly take me to destinations of trackers issue...

### ISSUE THREAD

**Issue by siscang** [Sainan/Universal-Bypass#1870]
Hi there, just want know why "Instantly take me to destinations of trackers" option cannot be unchecked (it won't even let me modify this option by ticking or un-ticking it) on version 13.15.2 ?

Thanks!

**Comment by Sainan** [comment]
Install the extension properly.

**Comment by siscang** [comment]
sorry for the late reply... anyway, all 3 PCs that have this extension installed on all have this issue and most importantly all installed only on Chrome latest version (Version 89.0.4389.90 (Official Build)). Two PCs have that installed long time ago from Chrome web store (with old version of extension 13.12.0) and one PC from your official website (latest version and followed every instruction there carefully). All "Instantly take me to destinations of trackers" checkbox options were greyed out on all 3 PCs now no matter what i've done (unticked on two PCs with old version of extension and default ticked on the PC which i got the extension directly from your official website) before and i couldn't modify that option anymore now.

Cheers!

**Comment by Sainan** [comment]
This might be due to the logic of it. It only has an effect if your normal bypass settings are not set to instant or if the tracker bypass is disabled.

**Comment by siscang** [comment]
> This might be due to the logic of it. It only has an effect if your normal bypass settings are not set to instant or if the tracker bypass is disabled.

I'm really a noob person as well as newbie on using any browser extension and even have little to none experience on how to use them or any other programs on Windows, so it's indeed very hard for me to understand what you've told me.
Could you please simplify it may be by using graph if possible on how to un-greyed the checkbox so that I can tick or untick it ? I will really appreciate your help. 
Cheers!
