### ISSUE TITLE
URLTeam integration?

### ISSUE THREAD

**Issue by jtagcat** [Sainan/Universal-Bypass#1885]
https://wiki.archiveteam.org/index.php/URLTeam

URLTeam archives link shorteners. Thoughts about archiving the crowdsourcings etc, and using the archives?

**Comment by andrewarchi** [comment]
My [urlhero](https://github.com/andrewarchi/urlhero) side project downloads and parses the incremental URLTeam releases. Currently, the XZ-compressed releases sum to about 500GB. Once I have more time on my hands, I hope to contribute to or fork an extension like Universal Bypass to pull from this database in the browser.

**Comment by Sainan** [comment]
It seems like URLTeam is focused on the "direct redirect" kind of link shorteners, which isn't really where Universal Bypass operates (for the most part).
