### ISSUE TITLE
Another way of installing to google chrome

### ISSUE THREAD

**Issue by ethanaobrien** [Sainan/Universal-Bypass#1904]
Hello, the way you have of installing on google chrome browsers is very - messy. It leaves unnecessary files around the users computer. Another way you could do it is to go to chrome://extensions, turn on developer mode, and then pack the extension. Have users download the .crx file you made, tell them to go to chrome://extensions, tell them to turn on developer mode, tell them to reload the page (required) and then drag and drop the .crx file onto the page. It installs the packed extension instead of leaving the extension unpacked. You could also leave the .zip download for developers.

**Comment by Sainan** [comment]
This would also leave unecessary files on the computer, no? And I do think Chrome will throw a fit if the crx is not signed, and you guessed it, there's only one company with the authority to sign them.

**Comment by ethanaobrien** [comment]
@Sainan 
I build chrome extensions for fun and I pack them and drag them to the extensions page, like I said, and the only thing google chrome says is "do you want to install (extension name)" I packed the universal bypass folder and it installed fine. Just try it.

**Comment by Sainan** [comment]
It works on your machine, but does it work on another's?

**Comment by ethanaobrien** [comment]
Yes, all google chrome browsers work this way. If you would like to see this download the Universal Bypass .crx I made from here
https://drive.google.com/file/d/1JbSnG5ZF3S9SHkaL_abtSWigDEwOa7Ds/view?usp=sharing

If you want more examples than universal bypass then try to install this other one I made. Its just a game.

https://drive.google.com/file/d/1nSioB3CVKuBxGWJojzbXbcqb-a2xrIjq/view?usp=sharing

Let me know of the results

**Comment by Sainan** [comment]
but what about other Chromium-based browsers?

**Comment by ethanaobrien** [comment]
@Sainan  I use the raw build of chromium for testing for some of my apps and chromium supports this. I would assume most do.

**Comment by Sainan** [comment]
Hm, okay, I'll look into it.

**Comment by Cyberavater** [comment]
> @Sainan
> Yes, all google chrome browsers work this way. If you would like to see this download the Universal Bypass .crx I made from here
> https://drive.google.com/file/d/1JbSnG5ZF3S9SHkaL_abtSWigDEwOa7Ds/view?usp=sharing
> 
> If you want more examples than universal bypass then try to install this other one I made. Its just a game.
> 
> https://drive.google.com/file/d/1nSioB3CVKuBxGWJojzbXbcqb-a2xrIjq/view?usp=sharing
> 
> Let me know of the results

When I try to install from your link, I get this error; Package is invalid 'CRX_REQUIRED_PROOF_MISSING'

https://stackoverflow.com/questions/57425449/chrome-extension-says-crx-required-proof-missing-while-installing

**Comment by ethanaobrien** [comment]
@Cyberavater What is your os and what version of google chrome are you on?

**Comment by Cyberavater** [comment]
Windows 10, Chome latest.

**Comment by ethanaobrien** [comment]
@Cyberavater 

Did you install the crx from `chrome://extensions/` by enabling developer mode, refreshing the page, and dragging and dropping the `.crx` or did you go to `C:\Users\Username\Desktop\extension.crx`?

**Comment by Hunam6** [comment]
https://developer.chrome.com/docs/extensions/mv3/external_extensions
![image](https://user-images.githubusercontent.com/38606542/115129180-9e742c80-9fdb-11eb-9acf-4e64c8d7dc13.png)
Seems like only Linux users can use this method.

**Comment by ethanaobrien** [comment]
@Sainan 
I just tested on my windows 10 computer (on a clean install of google chrome) and I had no such errors. It just asked me 'would you like to install this extension'

**Comment by Cyberavater** [comment]
> @Sainan
I just tested on my windows 10 computer (on a clean install of google chrome) and I had no such errors. It just asked me 'would you like to install this extension'

Which one? The 2nd link you provided is dead.

**Comment by ethanaobrien** [comment]
@Cyberavater 
Sorry, I was cleaning my gogle drive the other day. This is the .crx I used 

https://drive.google.com/file/d/1OCCaZ2R5-Uy7PR15pXMifD9ZKXI_nNC4/view?usp=sharing

**Comment by Cyberavater** [comment]
> @Cyberavater
> Sorry, I was cleaning my gogle drive the other day. This is the .crx I used
> 
> https://drive.google.com/file/d/1OCCaZ2R5-Uy7PR15pXMifD9ZKXI_nNC4/view?usp=sharing

Why you repeatedly sharing dead/invalid links, bro?

**Comment by ethanaobrien** [comment]
nvm - google drive wont let me share it

**Comment by Cyberavater** [comment]
> nvm - google drive wont let me share it

Well, I'm eager to test it, if you wanna share it through some other hosters.

**Comment by ethanaobrien** [comment]
@Cyberavater https://mega.nz/file/xhlH3AII#LPcnUdBcPkZMHGEVwaFb4O4PKLCyy8mp4-x6J3a1UNs

**Comment by Cyberavater** [comment]
> @Cyberavater https://mega.nz/file/xhlH3AII#LPcnUdBcPkZMHGEVwaFb4O4PKLCyy8mp4-x6J3a1UNs

![Screenshot (7)](https://user-images.githubusercontent.com/32187927/115156519-67b71880-a0a6-11eb-88ce-a9d283e1d643.png)

https://support.google.com/chrome_webstore/answer/2811969?visit_id=637543671379838380-154295593&p=ui_remove_non_cws_extensions&hl=en&rd=2

**Comment by ethanaobrien** [comment]
@Cyberavater I guess you really cant

**Comment by ethanaobrien** [comment]
@Cyberavater Just wondering - Could this be blocked because of an antivirus on the computer?
