### ISSUE TITLE
Trouble with installing in Android- Kiwi

### ISSUE THREAD

**Issue by pras92** [Sainan/Universal-Bypass#1950]
Using the latest UB and Kiwi, unable to select a folder while trying to load extension. Only choosing a file is possible. Selecting content_script.js loads an addon but with "extensions.file.user.js" title, empty logo and such. It has no reference to UB. 

Can anyone using UB in Kiwi shed some details on how you made it work?

**Comment by iribilangboshahay** [comment]
Load as zip file

**Comment by pras92** [comment]
Thank you, that worked.
