### ISSUE TITLE
shirosafe.web.id bypass detected

### ISSUE THREAD

**Issue by Recehan-Slayer** [Sainan/Universal-Bypass#900]
https://shirosafe.web.id/id/l6SLp
https://shirosafe.web.id/id/HpZ7d

`https://jouganime.com/haikyuu-season-4-to-the-top-episode-4-subtitle-indonesia/`

<details>

![Untitled4](https://user-images.githubusercontent.com/9379770/73586445-d0d16100-44df-11ea-81dd-9449783c09eb.png)

**Comment by Recehan-Slayer** [comment]
@timmyRS they changed their code again

**Comment by Recehan-Slayer** [comment]
they change it again

**Comment by Recehan-Slayer** [comment]
they always watching this thread or/and the commit.

**Comment by ikancupang** [comment]
@timmyRS Sorry for always improving shirosafe.web.id bypass, because Universal Bypass is getting more popular, so some websites like shirosafe.web.id always quickly negate the bypass.

**Comment by timmyRS** [comment]
No problem, that's what the auto-updating is for.

**Comment by Recehan-Slayer** [comment]
@timmyRS need update

**Comment by Recehan-Slayer** [comment]
breakage

**Comment by Recehan-Slayer** [comment]
<details> <summary>Token Miss Match</summary>

![Untitled](https://user-images.githubusercontent.com/9379770/74052460-7b7bdf00-4a0c-11ea-8381-160869bda3ec.png)

**Comment by timmyRS** [comment]
900 is such a nice number tho

**Comment by Recehan-Slayer** [comment]
i thought so. <sup> ~~and here we go again~~ </sup> . brought back to the "miss" page again

**Comment by Recehan-Slayer** [comment]
@timmyRS need update the countdown or bypass if possible
and also detect if out of focus

**Comment by Recehan-Slayer** [comment]
@timmyRS now leading to 404

**Comment by timmyRS** [comment]
I'm not gonna mention #900 anymore.

**Comment by Recehan-Slayer** [comment]
@timmyRS update

**Comment by Recehan-Slayer** [comment]
@timmyRS redirect to the home page

**Comment by Recehan-Slayer** [comment]
@timmyRS need update

**Comment by Recehan-Slayer** [comment]
@timmyRS need update

**Comment by Recehan-Slayer** [comment]
they come back again. need update

**Comment by Recehan-Slayer** [comment]
@timmyRS  token miss match

<details>

![Annotation 2020-02-17 192743](https://user-images.githubusercontent.com/9379770/74653919-c68bb400-51bb-11ea-9760-601acd18ce76.png)

**Comment by Recehan-Slayer** [comment]
they negate the bypass again.

**Comment by Recehan-Slayer** [comment]
@Sainan need update https://shirosafe.web.id/id/3iZBU
